/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OptimizationResult } from './OptimizationResult';
import {
    OptimizationResultFromJSON,
    OptimizationResultFromJSONTyped,
    OptimizationResultToJSON,
    OptimizationResultToJSONTyped,
} from './OptimizationResult';

/**
 * 
 * @export
 * @interface AdjustRulesResponse
 */
export interface AdjustRulesResponse {
    /**
     * 
     * @type {string}
     * @memberof AdjustRulesResponse
     */
    message?: string;
    /**
     * 
     * @type {OptimizationResult}
     * @memberof AdjustRulesResponse
     */
    result?: OptimizationResult;
}

/**
 * Check if a given object implements the AdjustRulesResponse interface.
 */
export function instanceOfAdjustRulesResponse(value: object): value is AdjustRulesResponse {
    return true;
}

export function AdjustRulesResponseFromJSON(json: any): AdjustRulesResponse {
    return AdjustRulesResponseFromJSONTyped(json, false);
}

export function AdjustRulesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdjustRulesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : OptimizationResultFromJSON(json['result']),
    };
}

export function AdjustRulesResponseToJSON(json: any): AdjustRulesResponse {
    return AdjustRulesResponseToJSONTyped(json, false);
}

export function AdjustRulesResponseToJSONTyped(value?: AdjustRulesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'result': OptimizationResultToJSON(value['result']),
    };
}

