/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OptimizationMode } from './OptimizationMode';
import {
    OptimizationModeFromJSON,
    OptimizationModeFromJSONTyped,
    OptimizationModeToJSON,
    OptimizationModeToJSONTyped,
} from './OptimizationMode';

/**
 * 
 * @export
 * @interface AdjustRulesRequest
 */
export interface AdjustRulesRequest {
    /**
     * 
     * @type {number}
     * @memberof AdjustRulesRequest
     */
    confidenceThreshold?: number;
    /**
     * 
     * @type {number}
     * @memberof AdjustRulesRequest
     */
    maxIterations?: number;
    /**
     * 
     * @type {OptimizationMode}
     * @memberof AdjustRulesRequest
     */
    mode: OptimizationMode;
    /**
     * 
     * @type {AdjustRulesRequestOptimizationGoalEnum}
     * @memberof AdjustRulesRequest
     */
    optimizationGoal: AdjustRulesRequestOptimizationGoalEnum;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AdjustRulesRequest
     */
    parameters?: { [key: string]: any; };
}

/**
* @export
* @enum {string}
*/
export enum AdjustRulesRequestOptimizationGoalEnum {
    MaximizeProfit = 'MAXIMIZE_PROFIT',
    MinimizeRisk = 'MINIMIZE_RISK',
    BalanceSharpe = 'BALANCE_SHARPE'
}


/**
 * Check if a given object implements the AdjustRulesRequest interface.
 */
export function instanceOfAdjustRulesRequest(value: object): value is AdjustRulesRequest {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('optimizationGoal' in value) || value['optimizationGoal'] === undefined) return false;
    return true;
}

export function AdjustRulesRequestFromJSON(json: any): AdjustRulesRequest {
    return AdjustRulesRequestFromJSONTyped(json, false);
}

export function AdjustRulesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdjustRulesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'confidenceThreshold': json['confidenceThreshold'] == null ? undefined : json['confidenceThreshold'],
        'maxIterations': json['maxIterations'] == null ? undefined : json['maxIterations'],
        'mode': OptimizationModeFromJSON(json['mode']),
        'optimizationGoal': json['optimizationGoal'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
    };
}

export function AdjustRulesRequestToJSON(json: any): AdjustRulesRequest {
    return AdjustRulesRequestToJSONTyped(json, false);
}

export function AdjustRulesRequestToJSONTyped(value?: AdjustRulesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'confidenceThreshold': value['confidenceThreshold'],
        'maxIterations': value['maxIterations'],
        'mode': OptimizationModeToJSON(value['mode']),
        'optimizationGoal': value['optimizationGoal'],
        'parameters': value['parameters'],
    };
}

