/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminAssignPlanRequest
 */
export interface AdminAssignPlanRequest {
    /**
     * 
     * @type {number}
     * @memberof AdminAssignPlanRequest
     */
    planId: number;
    /**
     * 
     * @type {number}
     * @memberof AdminAssignPlanRequest
     */
    planPricingId: number;
}

/**
 * Check if a given object implements the AdminAssignPlanRequest interface.
 */
export function instanceOfAdminAssignPlanRequest(value: object): value is AdminAssignPlanRequest {
    if (!('planId' in value) || value['planId'] === undefined) return false;
    if (!('planPricingId' in value) || value['planPricingId'] === undefined) return false;
    return true;
}

export function AdminAssignPlanRequestFromJSON(json: any): AdminAssignPlanRequest {
    return AdminAssignPlanRequestFromJSONTyped(json, false);
}

export function AdminAssignPlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAssignPlanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'planId': json['planId'],
        'planPricingId': json['planPricingId'],
    };
}

export function AdminAssignPlanRequestToJSON(json: any): AdminAssignPlanRequest {
    return AdminAssignPlanRequestToJSONTyped(json, false);
}

export function AdminAssignPlanRequestToJSONTyped(value?: AdminAssignPlanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'planId': value['planId'],
        'planPricingId': value['planPricingId'],
    };
}

