/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Permission } from './Permission';
import {
    PermissionFromJSON,
    PermissionFromJSONTyped,
    PermissionToJSON,
    PermissionToJSONTyped,
} from './Permission';

/**
 * 
 * @export
 * @interface APIKey
 */
export interface APIKey {
    /**
     * 
     * @type {string}
     * @memberof APIKey
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof APIKey
     */
    createdBy?: number;
    /**
     * 
     * @type {string}
     * @memberof APIKey
     */
    expiresAt?: string;
    /**
     * 
     * @type {number}
     * @memberof APIKey
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof APIKey
     */
    isActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof APIKey
     */
    lastUsedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof APIKey
     */
    name?: string;
    /**
     * Allowed routes for this API key
     * @type {Array<Permission>}
     * @memberof APIKey
     */
    permissions?: Array<Permission>;
    /**
     * 
     * @type {string}
     * @memberof APIKey
     */
    serviceName?: string;
    /**
     * 
     * @type {string}
     * @memberof APIKey
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the APIKey interface.
 */
export function instanceOfAPIKey(value: object): value is APIKey {
    return true;
}

export function APIKeyFromJSON(json: any): APIKey {
    return APIKeyFromJSONTyped(json, false);
}

export function APIKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIKey {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'lastUsedAt': json['last_used_at'] == null ? undefined : json['last_used_at'],
        'name': json['name'] == null ? undefined : json['name'],
        'permissions': json['permissions'] == null ? undefined : ((json['permissions'] as Array<any>).map(PermissionFromJSON)),
        'serviceName': json['service_name'] == null ? undefined : json['service_name'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function APIKeyToJSON(json: any): APIKey {
    return APIKeyToJSONTyped(json, false);
}

export function APIKeyToJSONTyped(value?: APIKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'created_by': value['createdBy'],
        'expires_at': value['expiresAt'],
        'id': value['id'],
        'is_active': value['isActive'],
        'last_used_at': value['lastUsedAt'],
        'name': value['name'],
        'permissions': value['permissions'] == null ? undefined : ((value['permissions'] as Array<any>).map(PermissionToJSON)),
        'service_name': value['serviceName'],
        'updated_at': value['updatedAt'],
    };
}

