/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetDistribution
 */
export interface AssetDistribution {
    /**
     * 
     * @type {number}
     * @memberof AssetDistribution
     */
    percentage?: number;
    /**
     * 
     * @type {string}
     * @memberof AssetDistribution
     */
    symbol?: string;
    /**
     * 
     * @type {number}
     * @memberof AssetDistribution
     */
    total?: number;
}

/**
 * Check if a given object implements the AssetDistribution interface.
 */
export function instanceOfAssetDistribution(value: object): value is AssetDistribution {
    return true;
}

export function AssetDistributionFromJSON(json: any): AssetDistribution {
    return AssetDistributionFromJSONTyped(json, false);
}

export function AssetDistributionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetDistribution {
    if (json == null) {
        return json;
    }
    return {
        
        'percentage': json['percentage'] == null ? undefined : json['percentage'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function AssetDistributionToJSON(json: any): AssetDistribution {
    return AssetDistributionToJSONTyped(json, false);
}

export function AssetDistributionToJSONTyped(value?: AssetDistribution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'percentage': value['percentage'],
        'symbol': value['symbol'],
        'total': value['total'],
    };
}

