/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Language } from './Language';
import {
    LanguageFromJSON,
    LanguageFromJSONTyped,
    LanguageToJSON,
    LanguageToJSONTyped,
} from './Language';

/**
 * 
 * @export
 * @interface BaseResponseArrayLanguage
 */
export interface BaseResponseArrayLanguage {
    /**
     * 
     * @type {Array<Language>}
     * @memberof BaseResponseArrayLanguage
     */
    data?: Array<Language>;
}

/**
 * Check if a given object implements the BaseResponseArrayLanguage interface.
 */
export function instanceOfBaseResponseArrayLanguage(value: object): value is BaseResponseArrayLanguage {
    return true;
}

export function BaseResponseArrayLanguageFromJSON(json: any): BaseResponseArrayLanguage {
    return BaseResponseArrayLanguageFromJSONTyped(json, false);
}

export function BaseResponseArrayLanguageFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseArrayLanguage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(LanguageFromJSON)),
    };
}

export function BaseResponseArrayLanguageToJSON(json: any): BaseResponseArrayLanguage {
    return BaseResponseArrayLanguageToJSONTyped(json, false);
}

export function BaseResponseArrayLanguageToJSONTyped(value?: BaseResponseArrayLanguage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(LanguageToJSON)),
    };
}

