/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Brokerage } from './Brokerage';
import {
    BrokerageFromJSON,
    BrokerageFromJSONTyped,
    BrokerageToJSON,
    BrokerageToJSONTyped,
} from './Brokerage';

/**
 * 
 * @export
 * @interface BaseResponseArrayBrokerage
 */
export interface BaseResponseArrayBrokerage {
    /**
     * 
     * @type {Array<Brokerage>}
     * @memberof BaseResponseArrayBrokerage
     */
    data?: Array<Brokerage>;
}

/**
 * Check if a given object implements the BaseResponseArrayBrokerage interface.
 */
export function instanceOfBaseResponseArrayBrokerage(value: object): value is BaseResponseArrayBrokerage {
    return true;
}

export function BaseResponseArrayBrokerageFromJSON(json: any): BaseResponseArrayBrokerage {
    return BaseResponseArrayBrokerageFromJSONTyped(json, false);
}

export function BaseResponseArrayBrokerageFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseArrayBrokerage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(BrokerageFromJSON)),
    };
}

export function BaseResponseArrayBrokerageToJSON(json: any): BaseResponseArrayBrokerage {
    return BaseResponseArrayBrokerageToJSONTyped(json, false);
}

export function BaseResponseArrayBrokerageToJSONTyped(value?: BaseResponseArrayBrokerage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(BrokerageToJSON)),
    };
}

