/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseResponseNotificationPaginationInfo
 */
export interface BaseResponseNotificationPaginationInfo {
    /**
     * 
     * @type {number}
     * @memberof BaseResponseNotificationPaginationInfo
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseNotificationPaginationInfo
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseNotificationPaginationInfo
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseNotificationPaginationInfo
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the BaseResponseNotificationPaginationInfo interface.
 */
export function instanceOfBaseResponseNotificationPaginationInfo(value: object): value is BaseResponseNotificationPaginationInfo {
    return true;
}

export function BaseResponseNotificationPaginationInfoFromJSON(json: any): BaseResponseNotificationPaginationInfo {
    return BaseResponseNotificationPaginationInfoFromJSONTyped(json, false);
}

export function BaseResponseNotificationPaginationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseNotificationPaginationInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'perPage': json['perPage'] == null ? undefined : json['perPage'],
        'total': json['total'] == null ? undefined : json['total'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function BaseResponseNotificationPaginationInfoToJSON(json: any): BaseResponseNotificationPaginationInfo {
    return BaseResponseNotificationPaginationInfoToJSONTyped(json, false);
}

export function BaseResponseNotificationPaginationInfoToJSONTyped(value?: BaseResponseNotificationPaginationInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPage': value['currentPage'],
        'perPage': value['perPage'],
        'total': value['total'],
        'totalPages': value['totalPages'],
    };
}

