/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoreWorkloadTransportHttpStopWorkloadResponse } from './CoreWorkloadTransportHttpStopWorkloadResponse';
import {
    CoreWorkloadTransportHttpStopWorkloadResponseFromJSON,
    CoreWorkloadTransportHttpStopWorkloadResponseFromJSONTyped,
    CoreWorkloadTransportHttpStopWorkloadResponseToJSON,
    CoreWorkloadTransportHttpStopWorkloadResponseToJSONTyped,
} from './CoreWorkloadTransportHttpStopWorkloadResponse';

/**
 * 
 * @export
 * @interface BaseResponseStopWorkloadResponse
 */
export interface BaseResponseStopWorkloadResponse {
    /**
     * 
     * @type {CoreWorkloadTransportHttpStopWorkloadResponse}
     * @memberof BaseResponseStopWorkloadResponse
     */
    data?: CoreWorkloadTransportHttpStopWorkloadResponse;
}

/**
 * Check if a given object implements the BaseResponseStopWorkloadResponse interface.
 */
export function instanceOfBaseResponseStopWorkloadResponse(value: object): value is BaseResponseStopWorkloadResponse {
    return true;
}

export function BaseResponseStopWorkloadResponseFromJSON(json: any): BaseResponseStopWorkloadResponse {
    return BaseResponseStopWorkloadResponseFromJSONTyped(json, false);
}

export function BaseResponseStopWorkloadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseStopWorkloadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : CoreWorkloadTransportHttpStopWorkloadResponseFromJSON(json['data']),
    };
}

export function BaseResponseStopWorkloadResponseToJSON(json: any): BaseResponseStopWorkloadResponse {
    return BaseResponseStopWorkloadResponseToJSONTyped(json, false);
}

export function BaseResponseStopWorkloadResponseToJSONTyped(value?: BaseResponseStopWorkloadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CoreWorkloadTransportHttpStopWorkloadResponseToJSON(value['data']),
    };
}

