/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserWithConfiguration } from './UserWithConfiguration';
import {
    UserWithConfigurationFromJSON,
    UserWithConfigurationFromJSONTyped,
    UserWithConfigurationToJSON,
    UserWithConfigurationToJSONTyped,
} from './UserWithConfiguration';

/**
 * 
 * @export
 * @interface BaseResponseUserWithConfiguration
 */
export interface BaseResponseUserWithConfiguration {
    /**
     * 
     * @type {UserWithConfiguration}
     * @memberof BaseResponseUserWithConfiguration
     */
    data?: UserWithConfiguration;
}

/**
 * Check if a given object implements the BaseResponseUserWithConfiguration interface.
 */
export function instanceOfBaseResponseUserWithConfiguration(value: object): value is BaseResponseUserWithConfiguration {
    return true;
}

export function BaseResponseUserWithConfigurationFromJSON(json: any): BaseResponseUserWithConfiguration {
    return BaseResponseUserWithConfigurationFromJSONTyped(json, false);
}

export function BaseResponseUserWithConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseUserWithConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : UserWithConfigurationFromJSON(json['data']),
    };
}

export function BaseResponseUserWithConfigurationToJSON(json: any): BaseResponseUserWithConfiguration {
    return BaseResponseUserWithConfigurationToJSONTyped(json, false);
}

export function BaseResponseUserWithConfigurationToJSONTyped(value?: BaseResponseUserWithConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': UserWithConfigurationToJSON(value['data']),
    };
}

