/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoreBacktestTransportHttpSyncBacktestResponse } from './CoreBacktestTransportHttpSyncBacktestResponse';
import {
    CoreBacktestTransportHttpSyncBacktestResponseFromJSON,
    CoreBacktestTransportHttpSyncBacktestResponseFromJSONTyped,
    CoreBacktestTransportHttpSyncBacktestResponseToJSON,
    CoreBacktestTransportHttpSyncBacktestResponseToJSONTyped,
} from './CoreBacktestTransportHttpSyncBacktestResponse';

/**
 * 
 * @export
 * @interface BaseResponseSyncBacktestResponse
 */
export interface BaseResponseSyncBacktestResponse {
    /**
     * 
     * @type {CoreBacktestTransportHttpSyncBacktestResponse}
     * @memberof BaseResponseSyncBacktestResponse
     */
    data?: CoreBacktestTransportHttpSyncBacktestResponse;
}

/**
 * Check if a given object implements the BaseResponseSyncBacktestResponse interface.
 */
export function instanceOfBaseResponseSyncBacktestResponse(value: object): value is BaseResponseSyncBacktestResponse {
    return true;
}

export function BaseResponseSyncBacktestResponseFromJSON(json: any): BaseResponseSyncBacktestResponse {
    return BaseResponseSyncBacktestResponseFromJSONTyped(json, false);
}

export function BaseResponseSyncBacktestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseSyncBacktestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : CoreBacktestTransportHttpSyncBacktestResponseFromJSON(json['data']),
    };
}

export function BaseResponseSyncBacktestResponseToJSON(json: any): BaseResponseSyncBacktestResponse {
    return BaseResponseSyncBacktestResponseToJSONTyped(json, false);
}

export function BaseResponseSyncBacktestResponseToJSONTyped(value?: BaseResponseSyncBacktestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CoreBacktestTransportHttpSyncBacktestResponseToJSON(value['data']),
    };
}

