/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StockItemWatchList } from './StockItemWatchList';
import {
    StockItemWatchListFromJSON,
    StockItemWatchListFromJSONTyped,
    StockItemWatchListToJSON,
    StockItemWatchListToJSONTyped,
} from './StockItemWatchList';

/**
 * 
 * @export
 * @interface BaseResponseArrayStockItemWatchList
 */
export interface BaseResponseArrayStockItemWatchList {
    /**
     * 
     * @type {Array<StockItemWatchList>}
     * @memberof BaseResponseArrayStockItemWatchList
     */
    data?: Array<StockItemWatchList>;
}

/**
 * Check if a given object implements the BaseResponseArrayStockItemWatchList interface.
 */
export function instanceOfBaseResponseArrayStockItemWatchList(value: object): value is BaseResponseArrayStockItemWatchList {
    return true;
}

export function BaseResponseArrayStockItemWatchListFromJSON(json: any): BaseResponseArrayStockItemWatchList {
    return BaseResponseArrayStockItemWatchListFromJSONTyped(json, false);
}

export function BaseResponseArrayStockItemWatchListFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseArrayStockItemWatchList {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(StockItemWatchListFromJSON)),
    };
}

export function BaseResponseArrayStockItemWatchListToJSON(json: any): BaseResponseArrayStockItemWatchList {
    return BaseResponseArrayStockItemWatchListToJSONTyped(json, false);
}

export function BaseResponseArrayStockItemWatchListToJSONTyped(value?: BaseResponseArrayStockItemWatchList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(StockItemWatchListToJSON)),
    };
}

