/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SyncPortfolioResponse } from './SyncPortfolioResponse';
import {
    SyncPortfolioResponseFromJSON,
    SyncPortfolioResponseFromJSONTyped,
    SyncPortfolioResponseToJSON,
    SyncPortfolioResponseToJSONTyped,
} from './SyncPortfolioResponse';

/**
 * 
 * @export
 * @interface BaseResponseSyncPortfolioResponse
 */
export interface BaseResponseSyncPortfolioResponse {
    /**
     * 
     * @type {SyncPortfolioResponse}
     * @memberof BaseResponseSyncPortfolioResponse
     */
    data?: SyncPortfolioResponse;
}

/**
 * Check if a given object implements the BaseResponseSyncPortfolioResponse interface.
 */
export function instanceOfBaseResponseSyncPortfolioResponse(value: object): value is BaseResponseSyncPortfolioResponse {
    return true;
}

export function BaseResponseSyncPortfolioResponseFromJSON(json: any): BaseResponseSyncPortfolioResponse {
    return BaseResponseSyncPortfolioResponseFromJSONTyped(json, false);
}

export function BaseResponseSyncPortfolioResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseSyncPortfolioResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : SyncPortfolioResponseFromJSON(json['data']),
    };
}

export function BaseResponseSyncPortfolioResponseToJSON(json: any): BaseResponseSyncPortfolioResponse {
    return BaseResponseSyncPortfolioResponseToJSONTyped(json, false);
}

export function BaseResponseSyncPortfolioResponseToJSONTyped(value?: BaseResponseSyncPortfolioResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SyncPortfolioResponseToJSON(value['data']),
    };
}

