/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseResponseBrokerageaccountBrokerageInfo
 */
export interface BaseResponseBrokerageaccountBrokerageInfo {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseBrokerageaccountBrokerageInfo
     */
    code?: string;
    /**
     * Display name of the brokerage
     * @type {string}
     * @memberof BaseResponseBrokerageaccountBrokerageInfo
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseBrokerageaccountBrokerageInfo
     */
    logoFullDark?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseBrokerageaccountBrokerageInfo
     */
    logoFullLight?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseBrokerageaccountBrokerageInfo
     */
    logoShortDark?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseBrokerageaccountBrokerageInfo
     */
    logoShortLight?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseBrokerageaccountBrokerageInfo
     */
    name?: string;
}

/**
 * Check if a given object implements the BaseResponseBrokerageaccountBrokerageInfo interface.
 */
export function instanceOfBaseResponseBrokerageaccountBrokerageInfo(value: object): value is BaseResponseBrokerageaccountBrokerageInfo {
    return true;
}

export function BaseResponseBrokerageaccountBrokerageInfoFromJSON(json: any): BaseResponseBrokerageaccountBrokerageInfo {
    return BaseResponseBrokerageaccountBrokerageInfoFromJSONTyped(json, false);
}

export function BaseResponseBrokerageaccountBrokerageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseBrokerageaccountBrokerageInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'logoFullDark': json['logoFullDark'] == null ? undefined : json['logoFullDark'],
        'logoFullLight': json['logoFullLight'] == null ? undefined : json['logoFullLight'],
        'logoShortDark': json['logoShortDark'] == null ? undefined : json['logoShortDark'],
        'logoShortLight': json['logoShortLight'] == null ? undefined : json['logoShortLight'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function BaseResponseBrokerageaccountBrokerageInfoToJSON(json: any): BaseResponseBrokerageaccountBrokerageInfo {
    return BaseResponseBrokerageaccountBrokerageInfoToJSONTyped(json, false);
}

export function BaseResponseBrokerageaccountBrokerageInfoToJSONTyped(value?: BaseResponseBrokerageaccountBrokerageInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'display_name': value['displayName'],
        'logoFullDark': value['logoFullDark'],
        'logoFullLight': value['logoFullLight'],
        'logoShortDark': value['logoShortDark'],
        'logoShortLight': value['logoShortLight'],
        'name': value['name'],
    };
}

