/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Workload } from './Workload';
import {
    WorkloadFromJSON,
    WorkloadFromJSONTyped,
    WorkloadToJSON,
    WorkloadToJSONTyped,
} from './Workload';

/**
 * 
 * @export
 * @interface BaseResponseWorkload
 */
export interface BaseResponseWorkload {
    /**
     * 
     * @type {Workload}
     * @memberof BaseResponseWorkload
     */
    data?: Workload;
}

/**
 * Check if a given object implements the BaseResponseWorkload interface.
 */
export function instanceOfBaseResponseWorkload(value: object): value is BaseResponseWorkload {
    return true;
}

export function BaseResponseWorkloadFromJSON(json: any): BaseResponseWorkload {
    return BaseResponseWorkloadFromJSONTyped(json, false);
}

export function BaseResponseWorkloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseWorkload {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : WorkloadFromJSON(json['data']),
    };
}

export function BaseResponseWorkloadToJSON(json: any): BaseResponseWorkload {
    return BaseResponseWorkloadToJSONTyped(json, false);
}

export function BaseResponseWorkloadToJSONTyped(value?: BaseResponseWorkload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': WorkloadToJSON(value['data']),
    };
}

