/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum BaseResponseNotificationType {
    TypeAlert = 'ALERT',
    TypeBacktest = 'BACKTEST',
    TypeCustomBacktest = 'CUSTOM_BACKTEST',
    TypeCustomLiveTrade = 'CUSTOM_LIVE_TRADE'
}


export function instanceOfBaseResponseNotificationType(value: any): boolean {
    for (const key in BaseResponseNotificationType) {
        if (Object.prototype.hasOwnProperty.call(BaseResponseNotificationType, key)) {
            if (BaseResponseNotificationType[key as keyof typeof BaseResponseNotificationType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BaseResponseNotificationTypeFromJSON(json: any): BaseResponseNotificationType {
    return BaseResponseNotificationTypeFromJSONTyped(json, false);
}

export function BaseResponseNotificationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseNotificationType {
    return json as BaseResponseNotificationType;
}

export function BaseResponseNotificationTypeToJSON(value?: BaseResponseNotificationType | null): any {
    return value as any;
}

export function BaseResponseNotificationTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): BaseResponseNotificationType {
    return value as BaseResponseNotificationType;
}

