/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TradingClientListItem } from './TradingClientListItem';
import {
    TradingClientListItemFromJSON,
    TradingClientListItemFromJSONTyped,
    TradingClientListItemToJSON,
    TradingClientListItemToJSONTyped,
} from './TradingClientListItem';

/**
 * 
 * @export
 * @interface BaseResponseArrayTradingClientListItem
 */
export interface BaseResponseArrayTradingClientListItem {
    /**
     * 
     * @type {Array<TradingClientListItem>}
     * @memberof BaseResponseArrayTradingClientListItem
     */
    data?: Array<TradingClientListItem>;
}

/**
 * Check if a given object implements the BaseResponseArrayTradingClientListItem interface.
 */
export function instanceOfBaseResponseArrayTradingClientListItem(value: object): value is BaseResponseArrayTradingClientListItem {
    return true;
}

export function BaseResponseArrayTradingClientListItemFromJSON(json: any): BaseResponseArrayTradingClientListItem {
    return BaseResponseArrayTradingClientListItemFromJSONTyped(json, false);
}

export function BaseResponseArrayTradingClientListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseArrayTradingClientListItem {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TradingClientListItemFromJSON)),
    };
}

export function BaseResponseArrayTradingClientListItemToJSON(json: any): BaseResponseArrayTradingClientListItem {
    return BaseResponseArrayTradingClientListItemToJSONTyped(json, false);
}

export function BaseResponseArrayTradingClientListItemToJSONTyped(value?: BaseResponseArrayTradingClientListItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TradingClientListItemToJSON)),
    };
}

