/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TradingRun } from './TradingRun';
import {
    TradingRunFromJSON,
    TradingRunFromJSONTyped,
    TradingRunToJSON,
    TradingRunToJSONTyped,
} from './TradingRun';

/**
 * 
 * @export
 * @interface BaseResponseTradingRun
 */
export interface BaseResponseTradingRun {
    /**
     * 
     * @type {TradingRun}
     * @memberof BaseResponseTradingRun
     */
    data?: TradingRun;
}

/**
 * Check if a given object implements the BaseResponseTradingRun interface.
 */
export function instanceOfBaseResponseTradingRun(value: object): value is BaseResponseTradingRun {
    return true;
}

export function BaseResponseTradingRunFromJSON(json: any): BaseResponseTradingRun {
    return BaseResponseTradingRunFromJSONTyped(json, false);
}

export function BaseResponseTradingRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseTradingRun {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : TradingRunFromJSON(json['data']),
    };
}

export function BaseResponseTradingRunToJSON(json: any): BaseResponseTradingRun {
    return BaseResponseTradingRunToJSONTyped(json, false);
}

export function BaseResponseTradingRunToJSONTyped(value?: BaseResponseTradingRun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TradingRunToJSON(value['data']),
    };
}

