/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginResponse } from './LoginResponse';
import {
    LoginResponseFromJSON,
    LoginResponseFromJSONTyped,
    LoginResponseToJSON,
    LoginResponseToJSONTyped,
} from './LoginResponse';

/**
 * 
 * @export
 * @interface BaseResponseLoginResponse
 */
export interface BaseResponseLoginResponse {
    /**
     * 
     * @type {LoginResponse}
     * @memberof BaseResponseLoginResponse
     */
    data?: LoginResponse;
}

/**
 * Check if a given object implements the BaseResponseLoginResponse interface.
 */
export function instanceOfBaseResponseLoginResponse(value: object): value is BaseResponseLoginResponse {
    return true;
}

export function BaseResponseLoginResponseFromJSON(json: any): BaseResponseLoginResponse {
    return BaseResponseLoginResponseFromJSONTyped(json, false);
}

export function BaseResponseLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : LoginResponseFromJSON(json['data']),
    };
}

export function BaseResponseLoginResponseToJSON(json: any): BaseResponseLoginResponse {
    return BaseResponseLoginResponseToJSONTyped(json, false);
}

export function BaseResponseLoginResponseToJSONTyped(value?: BaseResponseLoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': LoginResponseToJSON(value['data']),
    };
}

