/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HttpLiveTrade } from './HttpLiveTrade';
import {
    HttpLiveTradeFromJSON,
    HttpLiveTradeFromJSONTyped,
    HttpLiveTradeToJSON,
    HttpLiveTradeToJSONTyped,
} from './HttpLiveTrade';

/**
 * 
 * @export
 * @interface BaseResponseLiveTrade
 */
export interface BaseResponseLiveTrade {
    /**
     * 
     * @type {HttpLiveTrade}
     * @memberof BaseResponseLiveTrade
     */
    data?: HttpLiveTrade;
}

/**
 * Check if a given object implements the BaseResponseLiveTrade interface.
 */
export function instanceOfBaseResponseLiveTrade(value: object): value is BaseResponseLiveTrade {
    return true;
}

export function BaseResponseLiveTradeFromJSON(json: any): BaseResponseLiveTrade {
    return BaseResponseLiveTradeFromJSONTyped(json, false);
}

export function BaseResponseLiveTradeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseLiveTrade {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : HttpLiveTradeFromJSON(json['data']),
    };
}

export function BaseResponseLiveTradeToJSON(json: any): BaseResponseLiveTrade {
    return BaseResponseLiveTradeToJSONTyped(json, false);
}

export function BaseResponseLiveTradeToJSONTyped(value?: BaseResponseLiveTrade | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': HttpLiveTradeToJSON(value['data']),
    };
}

