/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RollbackToVersionResponse } from './RollbackToVersionResponse';
import {
    RollbackToVersionResponseFromJSON,
    RollbackToVersionResponseFromJSONTyped,
    RollbackToVersionResponseToJSON,
    RollbackToVersionResponseToJSONTyped,
} from './RollbackToVersionResponse';

/**
 * 
 * @export
 * @interface BaseResponseRollbackToVersionResponse
 */
export interface BaseResponseRollbackToVersionResponse {
    /**
     * 
     * @type {RollbackToVersionResponse}
     * @memberof BaseResponseRollbackToVersionResponse
     */
    data?: RollbackToVersionResponse;
}

/**
 * Check if a given object implements the BaseResponseRollbackToVersionResponse interface.
 */
export function instanceOfBaseResponseRollbackToVersionResponse(value: object): value is BaseResponseRollbackToVersionResponse {
    return true;
}

export function BaseResponseRollbackToVersionResponseFromJSON(json: any): BaseResponseRollbackToVersionResponse {
    return BaseResponseRollbackToVersionResponseFromJSONTyped(json, false);
}

export function BaseResponseRollbackToVersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseRollbackToVersionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : RollbackToVersionResponseFromJSON(json['data']),
    };
}

export function BaseResponseRollbackToVersionResponseToJSON(json: any): BaseResponseRollbackToVersionResponse {
    return BaseResponseRollbackToVersionResponseToJSONTyped(json, false);
}

export function BaseResponseRollbackToVersionResponseToJSONTyped(value?: BaseResponseRollbackToVersionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': RollbackToVersionResponseToJSON(value['data']),
    };
}

