/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PricingPlanWithPricings } from './PricingPlanWithPricings';
import {
    PricingPlanWithPricingsFromJSON,
    PricingPlanWithPricingsFromJSONTyped,
    PricingPlanWithPricingsToJSON,
    PricingPlanWithPricingsToJSONTyped,
} from './PricingPlanWithPricings';

/**
 * 
 * @export
 * @interface BaseResponsePricingPlanWithPricings
 */
export interface BaseResponsePricingPlanWithPricings {
    /**
     * 
     * @type {PricingPlanWithPricings}
     * @memberof BaseResponsePricingPlanWithPricings
     */
    data?: PricingPlanWithPricings;
}

/**
 * Check if a given object implements the BaseResponsePricingPlanWithPricings interface.
 */
export function instanceOfBaseResponsePricingPlanWithPricings(value: object): value is BaseResponsePricingPlanWithPricings {
    return true;
}

export function BaseResponsePricingPlanWithPricingsFromJSON(json: any): BaseResponsePricingPlanWithPricings {
    return BaseResponsePricingPlanWithPricingsFromJSONTyped(json, false);
}

export function BaseResponsePricingPlanWithPricingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponsePricingPlanWithPricings {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PricingPlanWithPricingsFromJSON(json['data']),
    };
}

export function BaseResponsePricingPlanWithPricingsToJSON(json: any): BaseResponsePricingPlanWithPricings {
    return BaseResponsePricingPlanWithPricingsToJSONTyped(json, false);
}

export function BaseResponsePricingPlanWithPricingsToJSONTyped(value?: BaseResponsePricingPlanWithPricings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PricingPlanWithPricingsToJSON(value['data']),
    };
}

