/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BillingPeriod } from './BillingPeriod';
import {
    BillingPeriodFromJSON,
    BillingPeriodFromJSONTyped,
    BillingPeriodToJSON,
    BillingPeriodToJSONTyped,
} from './BillingPeriod';

/**
 * 
 * @export
 * @interface BaseResponseArrayBillingPeriod
 */
export interface BaseResponseArrayBillingPeriod {
    /**
     * 
     * @type {Array<BillingPeriod>}
     * @memberof BaseResponseArrayBillingPeriod
     */
    data?: Array<BillingPeriod>;
}

/**
 * Check if a given object implements the BaseResponseArrayBillingPeriod interface.
 */
export function instanceOfBaseResponseArrayBillingPeriod(value: object): value is BaseResponseArrayBillingPeriod {
    return true;
}

export function BaseResponseArrayBillingPeriodFromJSON(json: any): BaseResponseArrayBillingPeriod {
    return BaseResponseArrayBillingPeriodFromJSONTyped(json, false);
}

export function BaseResponseArrayBillingPeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseArrayBillingPeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(BillingPeriodFromJSON)),
    };
}

export function BaseResponseArrayBillingPeriodToJSON(json: any): BaseResponseArrayBillingPeriod {
    return BaseResponseArrayBillingPeriodToJSONTyped(json, false);
}

export function BaseResponseArrayBillingPeriodToJSONTyped(value?: BaseResponseArrayBillingPeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(BillingPeriodToJSON)),
    };
}

