/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetBotStatusResponse } from './GetBotStatusResponse';
import {
    GetBotStatusResponseFromJSON,
    GetBotStatusResponseFromJSONTyped,
    GetBotStatusResponseToJSON,
    GetBotStatusResponseToJSONTyped,
} from './GetBotStatusResponse';

/**
 * 
 * @export
 * @interface BaseResponseGetBotStatusResponse
 */
export interface BaseResponseGetBotStatusResponse {
    /**
     * 
     * @type {GetBotStatusResponse}
     * @memberof BaseResponseGetBotStatusResponse
     */
    data?: GetBotStatusResponse;
}

/**
 * Check if a given object implements the BaseResponseGetBotStatusResponse interface.
 */
export function instanceOfBaseResponseGetBotStatusResponse(value: object): value is BaseResponseGetBotStatusResponse {
    return true;
}

export function BaseResponseGetBotStatusResponseFromJSON(json: any): BaseResponseGetBotStatusResponse {
    return BaseResponseGetBotStatusResponseFromJSONTyped(json, false);
}

export function BaseResponseGetBotStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseGetBotStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : GetBotStatusResponseFromJSON(json['data']),
    };
}

export function BaseResponseGetBotStatusResponseToJSON(json: any): BaseResponseGetBotStatusResponse {
    return BaseResponseGetBotStatusResponseToJSONTyped(json, false);
}

export function BaseResponseGetBotStatusResponseToJSONTyped(value?: BaseResponseGetBotStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GetBotStatusResponseToJSON(value['data']),
    };
}

