/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bot } from './Bot';
import {
    BotFromJSON,
    BotFromJSONTyped,
    BotToJSON,
    BotToJSONTyped,
} from './Bot';

/**
 * 
 * @export
 * @interface BaseResponseBot
 */
export interface BaseResponseBot {
    /**
     * 
     * @type {Bot}
     * @memberof BaseResponseBot
     */
    data?: Bot;
}

/**
 * Check if a given object implements the BaseResponseBot interface.
 */
export function instanceOfBaseResponseBot(value: object): value is BaseResponseBot {
    return true;
}

export function BaseResponseBotFromJSON(json: any): BaseResponseBot {
    return BaseResponseBotFromJSONTyped(json, false);
}

export function BaseResponseBotFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseBot {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : BotFromJSON(json['data']),
    };
}

export function BaseResponseBotToJSON(json: any): BaseResponseBot {
    return BaseResponseBotToJSONTyped(json, false);
}

export function BaseResponseBotToJSONTyped(value?: BaseResponseBot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': BotToJSON(value['data']),
    };
}

