/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseResponseTradeproviderBrokerageInfo
 */
export interface BaseResponseTradeproviderBrokerageInfo {
    /**
     * 
     * @type {number}
     * @memberof BaseResponseTradeproviderBrokerageInfo
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseTradeproviderBrokerageInfo
     */
    logoFullDark?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseTradeproviderBrokerageInfo
     */
    logoFullLight?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseTradeproviderBrokerageInfo
     */
    logoShortDark?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseTradeproviderBrokerageInfo
     */
    logoShortLight?: string;
}

/**
 * Check if a given object implements the BaseResponseTradeproviderBrokerageInfo interface.
 */
export function instanceOfBaseResponseTradeproviderBrokerageInfo(value: object): value is BaseResponseTradeproviderBrokerageInfo {
    return true;
}

export function BaseResponseTradeproviderBrokerageInfoFromJSON(json: any): BaseResponseTradeproviderBrokerageInfo {
    return BaseResponseTradeproviderBrokerageInfoFromJSONTyped(json, false);
}

export function BaseResponseTradeproviderBrokerageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseTradeproviderBrokerageInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'logoFullDark': json['logo_full_dark'] == null ? undefined : json['logo_full_dark'],
        'logoFullLight': json['logo_full_light'] == null ? undefined : json['logo_full_light'],
        'logoShortDark': json['logo_short_dark'] == null ? undefined : json['logo_short_dark'],
        'logoShortLight': json['logo_short_light'] == null ? undefined : json['logo_short_light'],
    };
}

export function BaseResponseTradeproviderBrokerageInfoToJSON(json: any): BaseResponseTradeproviderBrokerageInfo {
    return BaseResponseTradeproviderBrokerageInfoToJSONTyped(json, false);
}

export function BaseResponseTradeproviderBrokerageInfoToJSONTyped(value?: BaseResponseTradeproviderBrokerageInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'logo_full_dark': value['logoFullDark'],
        'logo_full_light': value['logoFullLight'],
        'logo_short_dark': value['logoShortDark'],
        'logo_short_light': value['logoShortLight'],
    };
}

