/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Role } from './Role';
import {
    RoleFromJSON,
    RoleFromJSONTyped,
    RoleToJSON,
    RoleToJSONTyped,
} from './Role';
import type { BaseResponseUserStatus } from './BaseResponseUserStatus';
import {
    BaseResponseUserStatusFromJSON,
    BaseResponseUserStatusFromJSONTyped,
    BaseResponseUserStatusToJSON,
    BaseResponseUserStatusToJSONTyped,
} from './BaseResponseUserStatus';
import type { BaseResponseUserType } from './BaseResponseUserType';
import {
    BaseResponseUserTypeFromJSON,
    BaseResponseUserTypeFromJSONTyped,
    BaseResponseUserTypeToJSON,
    BaseResponseUserTypeToJSONTyped,
} from './BaseResponseUserType';
import type { Provider } from './Provider';
import {
    ProviderFromJSON,
    ProviderFromJSONTyped,
    ProviderToJSON,
    ProviderToJSONTyped,
} from './Provider';

/**
 * 
 * @export
 * @interface BaseResponseUserUser
 */
export interface BaseResponseUserUser {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserUser
     */
    auth0Id?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserUser
     */
    avatar?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserUser
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserUser
     */
    datePlanEnd?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserUser
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseUserUser
     */
    emailVerified?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserUser
     */
    gender?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseUserUser
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserUser
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserUser
     */
    phone?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseUserUser
     */
    planId?: number;
    /**
     * 
     * @type {Provider}
     * @memberof BaseResponseUserUser
     */
    provider?: Provider;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserUser
     */
    providerId?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserUser
     */
    region?: string;
    /**
     * 
     * @type {Role}
     * @memberof BaseResponseUserUser
     */
    role?: Role;
    /**
     * 
     * @type {BaseResponseUserStatus}
     * @memberof BaseResponseUserUser
     */
    status?: BaseResponseUserStatus;
    /**
     * 
     * @type {BaseResponseUserType}
     * @memberof BaseResponseUserUser
     */
    type?: BaseResponseUserType;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserUser
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserUser
     */
    userName?: string;
}



/**
 * Check if a given object implements the BaseResponseUserUser interface.
 */
export function instanceOfBaseResponseUserUser(value: object): value is BaseResponseUserUser {
    return true;
}

export function BaseResponseUserUserFromJSON(json: any): BaseResponseUserUser {
    return BaseResponseUserUserFromJSONTyped(json, false);
}

export function BaseResponseUserUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseUserUser {
    if (json == null) {
        return json;
    }
    return {
        
        'auth0Id': json['auth0Id'] == null ? undefined : json['auth0Id'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'datePlanEnd': json['datePlanEnd'] == null ? undefined : json['datePlanEnd'],
        'email': json['email'] == null ? undefined : json['email'],
        'emailVerified': json['emailVerified'] == null ? undefined : json['emailVerified'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'id': json['id'] == null ? undefined : json['id'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'planId': json['planId'] == null ? undefined : json['planId'],
        'provider': json['provider'] == null ? undefined : ProviderFromJSON(json['provider']),
        'providerId': json['providerId'] == null ? undefined : json['providerId'],
        'region': json['region'] == null ? undefined : json['region'],
        'role': json['role'] == null ? undefined : RoleFromJSON(json['role']),
        'status': json['status'] == null ? undefined : BaseResponseUserStatusFromJSON(json['status']),
        'type': json['type'] == null ? undefined : BaseResponseUserTypeFromJSON(json['type']),
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'userName': json['userName'] == null ? undefined : json['userName'],
    };
}

export function BaseResponseUserUserToJSON(json: any): BaseResponseUserUser {
    return BaseResponseUserUserToJSONTyped(json, false);
}

export function BaseResponseUserUserToJSONTyped(value?: BaseResponseUserUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auth0Id': value['auth0Id'],
        'avatar': value['avatar'],
        'createdAt': value['createdAt'],
        'datePlanEnd': value['datePlanEnd'],
        'email': value['email'],
        'emailVerified': value['emailVerified'],
        'firstName': value['firstName'],
        'gender': value['gender'],
        'id': value['id'],
        'lastName': value['lastName'],
        'phone': value['phone'],
        'planId': value['planId'],
        'provider': ProviderToJSON(value['provider']),
        'providerId': value['providerId'],
        'region': value['region'],
        'role': RoleToJSON(value['role']),
        'status': BaseResponseUserStatusToJSON(value['status']),
        'type': BaseResponseUserTypeToJSON(value['type']),
        'updatedAt': value['updatedAt'],
        'userName': value['userName'],
    };
}

