/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum BotAdvancedOrderStatus {
    BotStatusInit = 'INIT',
    BotStatusRunning = 'RUNNING',
    BotStatusCompleted = 'COMPLETED',
    BotStatusStopped = 'STOPPED',
    BotStatusFailed = 'FAILED'
}


export function instanceOfBotAdvancedOrderStatus(value: any): boolean {
    for (const key in BotAdvancedOrderStatus) {
        if (Object.prototype.hasOwnProperty.call(BotAdvancedOrderStatus, key)) {
            if (BotAdvancedOrderStatus[key as keyof typeof BotAdvancedOrderStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BotAdvancedOrderStatusFromJSON(json: any): BotAdvancedOrderStatus {
    return BotAdvancedOrderStatusFromJSONTyped(json, false);
}

export function BotAdvancedOrderStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BotAdvancedOrderStatus {
    return json as BotAdvancedOrderStatus;
}

export function BotAdvancedOrderStatusToJSON(value?: BotAdvancedOrderStatus | null): any {
    return value as any;
}

export function BotAdvancedOrderStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): BotAdvancedOrderStatus {
    return value as BotAdvancedOrderStatus;
}

