/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum BotAdvancedOrderType {
    BotTypeDCA = 'DCA',
    BotTypeGRID = 'GRID',
    BotTypeTWAP = 'TWAP',
    BotTypeRebalancingSpot = 'REBALANCING_SPOT'
}


export function instanceOfBotAdvancedOrderType(value: any): boolean {
    for (const key in BotAdvancedOrderType) {
        if (Object.prototype.hasOwnProperty.call(BotAdvancedOrderType, key)) {
            if (BotAdvancedOrderType[key as keyof typeof BotAdvancedOrderType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BotAdvancedOrderTypeFromJSON(json: any): BotAdvancedOrderType {
    return BotAdvancedOrderTypeFromJSONTyped(json, false);
}

export function BotAdvancedOrderTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BotAdvancedOrderType {
    return json as BotAdvancedOrderType;
}

export function BotAdvancedOrderTypeToJSON(value?: BotAdvancedOrderType | null): any {
    return value as any;
}

export function BotAdvancedOrderTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): BotAdvancedOrderType {
    return value as BotAdvancedOrderType;
}

