/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BotLevel
 */
export interface BotLevel {
    /**
     * 
     * @type {string}
     * @memberof BotLevel
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof BotLevel
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof BotLevel
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof BotLevel
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BotLevel
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof BotLevel
     */
    priority?: number;
    /**
     * 
     * @type {string}
     * @memberof BotLevel
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the BotLevel interface.
 */
export function instanceOfBotLevel(value: object): value is BotLevel {
    return true;
}

export function BotLevelFromJSON(json: any): BotLevel {
    return BotLevelFromJSONTyped(json, false);
}

export function BotLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BotLevel {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function BotLevelToJSON(json: any): BotLevel {
    return BotLevelToJSONTyped(json, false);
}

export function BotLevelToJSONTyped(value?: BotLevel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'created_at': value['createdAt'],
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'priority': value['priority'],
        'updated_at': value['updatedAt'],
    };
}

