/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountStatus } from './AccountStatus';
import {
    AccountStatusFromJSON,
    AccountStatusFromJSONTyped,
    AccountStatusToJSON,
    AccountStatusToJSONTyped,
} from './AccountStatus';
import type { Credential } from './Credential';
import {
    CredentialFromJSON,
    CredentialFromJSONTyped,
    CredentialToJSON,
    CredentialToJSONTyped,
} from './Credential';
import type { BaseResponseBrokerageaccountBrokerageInfo } from './BaseResponseBrokerageaccountBrokerageInfo';
import {
    BaseResponseBrokerageaccountBrokerageInfoFromJSON,
    BaseResponseBrokerageaccountBrokerageInfoFromJSONTyped,
    BaseResponseBrokerageaccountBrokerageInfoToJSON,
    BaseResponseBrokerageaccountBrokerageInfoToJSONTyped,
} from './BaseResponseBrokerageaccountBrokerageInfo';

/**
 * 
 * @export
 * @interface BrokerageAccount
 */
export interface BrokerageAccount {
    /**
     * Brokerage information with image and displayName
     * @type {BaseResponseBrokerageaccountBrokerageInfo}
     * @memberof BrokerageAccount
     */
    brokerage?: BaseResponseBrokerageaccountBrokerageInfo;
    /**
     * 
     * @type {number}
     * @memberof BrokerageAccount
     */
    brokerageId?: number;
    /**
     * 
     * @type {string}
     * @memberof BrokerageAccount
     */
    createdAt?: string;
    /**
     * 
     * @type {Array<Credential>}
     * @memberof BrokerageAccount
     */
    credentials?: Array<Credential>;
    /**
     * Free assets for this account (from PortfolioSummary)
     * @type {number}
     * @memberof BrokerageAccount
     */
    freeAssets?: number;
    /**
     * 
     * @type {number}
     * @memberof BrokerageAccount
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BrokerageAccount
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof BrokerageAccount
     */
    providerUserId?: string;
    /**
     * 
     * @type {AccountStatus}
     * @memberof BrokerageAccount
     */
    status?: AccountStatus;
    /**
     * Array of tags for categorization
     * @type {Array<string>}
     * @memberof BrokerageAccount
     */
    tags?: Array<string>;
    /**
     * Related trading client (avoid circular import)
     * @type {object}
     * @memberof BrokerageAccount
     */
    tradingClient?: object;
    /**
     * Foreign key to trading_clients
     * @type {number}
     * @memberof BrokerageAccount
     */
    tradingClientId?: number;
    /**
     * 
     * @type {string}
     * @memberof BrokerageAccount
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof BrokerageAccount
     */
    userId?: number;
}



/**
 * Check if a given object implements the BrokerageAccount interface.
 */
export function instanceOfBrokerageAccount(value: object): value is BrokerageAccount {
    return true;
}

export function BrokerageAccountFromJSON(json: any): BrokerageAccount {
    return BrokerageAccountFromJSONTyped(json, false);
}

export function BrokerageAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrokerageAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'brokerage': json['brokerage'] == null ? undefined : BaseResponseBrokerageaccountBrokerageInfoFromJSON(json['brokerage']),
        'brokerageId': json['brokerage_id'] == null ? undefined : json['brokerage_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'credentials': json['credentials'] == null ? undefined : ((json['credentials'] as Array<any>).map(CredentialFromJSON)),
        'freeAssets': json['free_assets'] == null ? undefined : json['free_assets'],
        'id': json['id'] == null ? undefined : json['id'],
        'label': json['label'] == null ? undefined : json['label'],
        'providerUserId': json['provider_user_id'] == null ? undefined : json['provider_user_id'],
        'status': json['status'] == null ? undefined : AccountStatusFromJSON(json['status']),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'tradingClient': json['trading_client'] == null ? undefined : json['trading_client'],
        'tradingClientId': json['trading_client_id'] == null ? undefined : json['trading_client_id'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function BrokerageAccountToJSON(json: any): BrokerageAccount {
    return BrokerageAccountToJSONTyped(json, false);
}

export function BrokerageAccountToJSONTyped(value?: BrokerageAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'brokerage': BaseResponseBrokerageaccountBrokerageInfoToJSON(value['brokerage']),
        'brokerage_id': value['brokerageId'],
        'created_at': value['createdAt'],
        'credentials': value['credentials'] == null ? undefined : ((value['credentials'] as Array<any>).map(CredentialToJSON)),
        'free_assets': value['freeAssets'],
        'id': value['id'],
        'label': value['label'],
        'provider_user_id': value['providerUserId'],
        'status': AccountStatusToJSON(value['status']),
        'tags': value['tags'],
        'trading_client': value['tradingClient'],
        'trading_client_id': value['tradingClientId'],
        'updated_at': value['updatedAt'],
        'user_id': value['userId'],
    };
}

