/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CandlestickPattern
 */
export interface CandlestickPattern {
    /**
     * 
     * @type {string}
     * @memberof CandlestickPattern
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof CandlestickPattern
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CandlestickPattern
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CandlestickPattern
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof CandlestickPattern
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof CandlestickPattern
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the CandlestickPattern interface.
 */
export function instanceOfCandlestickPattern(value: object): value is CandlestickPattern {
    return true;
}

export function CandlestickPatternFromJSON(json: any): CandlestickPattern {
    return CandlestickPatternFromJSONTyped(json, false);
}

export function CandlestickPatternFromJSONTyped(json: any, ignoreDiscriminator: boolean): CandlestickPattern {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'label': json['label'] == null ? undefined : json['label'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function CandlestickPatternToJSON(json: any): CandlestickPattern {
    return CandlestickPatternToJSONTyped(json, false);
}

export function CandlestickPatternToJSONTyped(value?: CandlestickPattern | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'description': value['description'],
        'id': value['id'],
        'key': value['key'],
        'label': value['label'],
        'updatedAt': value['updatedAt'],
    };
}

