/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoreSocketTransportHttpBroadcastRequest
 */
export interface CoreSocketTransportHttpBroadcastRequest {
    /**
     * 
     * @type {object}
     * @memberof CoreSocketTransportHttpBroadcastRequest
     */
    data: object;
    /**
     * 
     * @type {string}
     * @memberof CoreSocketTransportHttpBroadcastRequest
     */
    event: string;
    /**
     * 
     * @type {string}
     * @memberof CoreSocketTransportHttpBroadcastRequest
     */
    room: string;
}

/**
 * Check if a given object implements the CoreSocketTransportHttpBroadcastRequest interface.
 */
export function instanceOfCoreSocketTransportHttpBroadcastRequest(value: object): value is CoreSocketTransportHttpBroadcastRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('event' in value) || value['event'] === undefined) return false;
    if (!('room' in value) || value['room'] === undefined) return false;
    return true;
}

export function CoreSocketTransportHttpBroadcastRequestFromJSON(json: any): CoreSocketTransportHttpBroadcastRequest {
    return CoreSocketTransportHttpBroadcastRequestFromJSONTyped(json, false);
}

export function CoreSocketTransportHttpBroadcastRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreSocketTransportHttpBroadcastRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'event': json['event'],
        'room': json['room'],
    };
}

export function CoreSocketTransportHttpBroadcastRequestToJSON(json: any): CoreSocketTransportHttpBroadcastRequest {
    return CoreSocketTransportHttpBroadcastRequestToJSONTyped(json, false);
}

export function CoreSocketTransportHttpBroadcastRequestToJSONTyped(value?: CoreSocketTransportHttpBroadcastRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'event': value['event'],
        'room': value['room'],
    };
}

