/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoreMarketplaceTransportHttpSearchKey
 */
export interface CoreMarketplaceTransportHttpSearchKey {
    /**
     * 
     * @type {string}
     * @memberof CoreMarketplaceTransportHttpSearchKey
     */
    dataType?: string;
    /**
     * 
     * @type {number}
     * @memberof CoreMarketplaceTransportHttpSearchKey
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CoreMarketplaceTransportHttpSearchKey
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof CoreMarketplaceTransportHttpSearchKey
     */
    localName?: string;
    /**
     * 
     * @type {string}
     * @memberof CoreMarketplaceTransportHttpSearchKey
     */
    namespace?: string;
}

/**
 * Check if a given object implements the CoreMarketplaceTransportHttpSearchKey interface.
 */
export function instanceOfCoreMarketplaceTransportHttpSearchKey(value: object): value is CoreMarketplaceTransportHttpSearchKey {
    return true;
}

export function CoreMarketplaceTransportHttpSearchKeyFromJSON(json: any): CoreMarketplaceTransportHttpSearchKey {
    return CoreMarketplaceTransportHttpSearchKeyFromJSONTyped(json, false);
}

export function CoreMarketplaceTransportHttpSearchKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreMarketplaceTransportHttpSearchKey {
    if (json == null) {
        return json;
    }
    return {
        
        'dataType': json['dataType'] == null ? undefined : json['dataType'],
        'id': json['id'] == null ? undefined : json['id'],
        'label': json['label'] == null ? undefined : json['label'],
        'localName': json['localName'] == null ? undefined : json['localName'],
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
    };
}

export function CoreMarketplaceTransportHttpSearchKeyToJSON(json: any): CoreMarketplaceTransportHttpSearchKey {
    return CoreMarketplaceTransportHttpSearchKeyToJSONTyped(json, false);
}

export function CoreMarketplaceTransportHttpSearchKeyToJSONTyped(value?: CoreMarketplaceTransportHttpSearchKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dataType': value['dataType'],
        'id': value['id'],
        'label': value['label'],
        'localName': value['localName'],
        'namespace': value['namespace'],
    };
}

