/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoreAlertTransportHttpDeleteAlertResponse
 */
export interface CoreAlertTransportHttpDeleteAlertResponse {
    /**
     * 
     * @type {object}
     * @memberof CoreAlertTransportHttpDeleteAlertResponse
     */
    data?: object;
}

/**
 * Check if a given object implements the CoreAlertTransportHttpDeleteAlertResponse interface.
 */
export function instanceOfCoreAlertTransportHttpDeleteAlertResponse(value: object): value is CoreAlertTransportHttpDeleteAlertResponse {
    return true;
}

export function CoreAlertTransportHttpDeleteAlertResponseFromJSON(json: any): CoreAlertTransportHttpDeleteAlertResponse {
    return CoreAlertTransportHttpDeleteAlertResponseFromJSONTyped(json, false);
}

export function CoreAlertTransportHttpDeleteAlertResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreAlertTransportHttpDeleteAlertResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function CoreAlertTransportHttpDeleteAlertResponseToJSON(json: any): CoreAlertTransportHttpDeleteAlertResponse {
    return CoreAlertTransportHttpDeleteAlertResponseToJSONTyped(json, false);
}

export function CoreAlertTransportHttpDeleteAlertResponseToJSONTyped(value?: CoreAlertTransportHttpDeleteAlertResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

