/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoreMarketplaceTransportHttpMarketplaceItem } from './CoreMarketplaceTransportHttpMarketplaceItem';
import {
    CoreMarketplaceTransportHttpMarketplaceItemFromJSON,
    CoreMarketplaceTransportHttpMarketplaceItemFromJSONTyped,
    CoreMarketplaceTransportHttpMarketplaceItemToJSON,
    CoreMarketplaceTransportHttpMarketplaceItemToJSONTyped,
} from './CoreMarketplaceTransportHttpMarketplaceItem';

/**
 * 
 * @export
 * @interface CoreMarketplaceTransportHttpUpdateMarketplaceItemResponse
 */
export interface CoreMarketplaceTransportHttpUpdateMarketplaceItemResponse {
    /**
     * 
     * @type {CoreMarketplaceTransportHttpMarketplaceItem}
     * @memberof CoreMarketplaceTransportHttpUpdateMarketplaceItemResponse
     */
    data?: CoreMarketplaceTransportHttpMarketplaceItem;
}

/**
 * Check if a given object implements the CoreMarketplaceTransportHttpUpdateMarketplaceItemResponse interface.
 */
export function instanceOfCoreMarketplaceTransportHttpUpdateMarketplaceItemResponse(value: object): value is CoreMarketplaceTransportHttpUpdateMarketplaceItemResponse {
    return true;
}

export function CoreMarketplaceTransportHttpUpdateMarketplaceItemResponseFromJSON(json: any): CoreMarketplaceTransportHttpUpdateMarketplaceItemResponse {
    return CoreMarketplaceTransportHttpUpdateMarketplaceItemResponseFromJSONTyped(json, false);
}

export function CoreMarketplaceTransportHttpUpdateMarketplaceItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreMarketplaceTransportHttpUpdateMarketplaceItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : CoreMarketplaceTransportHttpMarketplaceItemFromJSON(json['data']),
    };
}

export function CoreMarketplaceTransportHttpUpdateMarketplaceItemResponseToJSON(json: any): CoreMarketplaceTransportHttpUpdateMarketplaceItemResponse {
    return CoreMarketplaceTransportHttpUpdateMarketplaceItemResponseToJSONTyped(json, false);
}

export function CoreMarketplaceTransportHttpUpdateMarketplaceItemResponseToJSONTyped(value?: CoreMarketplaceTransportHttpUpdateMarketplaceItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CoreMarketplaceTransportHttpMarketplaceItemToJSON(value['data']),
    };
}

