/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WatchList } from './WatchList';
import {
    WatchListFromJSON,
    WatchListFromJSONTyped,
    WatchListToJSON,
    WatchListToJSONTyped,
} from './WatchList';

/**
 * 
 * @export
 * @interface CoreWatchlistTransportHttpUpdateWatchListResponse
 */
export interface CoreWatchlistTransportHttpUpdateWatchListResponse {
    /**
     * 
     * @type {WatchList}
     * @memberof CoreWatchlistTransportHttpUpdateWatchListResponse
     */
    data?: WatchList;
}

/**
 * Check if a given object implements the CoreWatchlistTransportHttpUpdateWatchListResponse interface.
 */
export function instanceOfCoreWatchlistTransportHttpUpdateWatchListResponse(value: object): value is CoreWatchlistTransportHttpUpdateWatchListResponse {
    return true;
}

export function CoreWatchlistTransportHttpUpdateWatchListResponseFromJSON(json: any): CoreWatchlistTransportHttpUpdateWatchListResponse {
    return CoreWatchlistTransportHttpUpdateWatchListResponseFromJSONTyped(json, false);
}

export function CoreWatchlistTransportHttpUpdateWatchListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreWatchlistTransportHttpUpdateWatchListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : WatchListFromJSON(json['data']),
    };
}

export function CoreWatchlistTransportHttpUpdateWatchListResponseToJSON(json: any): CoreWatchlistTransportHttpUpdateWatchListResponse {
    return CoreWatchlistTransportHttpUpdateWatchListResponseToJSONTyped(json, false);
}

export function CoreWatchlistTransportHttpUpdateWatchListResponseToJSONTyped(value?: CoreWatchlistTransportHttpUpdateWatchListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': WatchListToJSON(value['data']),
    };
}

