/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoreWatchlistTransportHttpReorderItemsRequest
 */
export interface CoreWatchlistTransportHttpReorderItemsRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof CoreWatchlistTransportHttpReorderItemsRequest
     */
    itemIds: Array<number>;
}

/**
 * Check if a given object implements the CoreWatchlistTransportHttpReorderItemsRequest interface.
 */
export function instanceOfCoreWatchlistTransportHttpReorderItemsRequest(value: object): value is CoreWatchlistTransportHttpReorderItemsRequest {
    if (!('itemIds' in value) || value['itemIds'] === undefined) return false;
    return true;
}

export function CoreWatchlistTransportHttpReorderItemsRequestFromJSON(json: any): CoreWatchlistTransportHttpReorderItemsRequest {
    return CoreWatchlistTransportHttpReorderItemsRequestFromJSONTyped(json, false);
}

export function CoreWatchlistTransportHttpReorderItemsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreWatchlistTransportHttpReorderItemsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'itemIds': json['itemIds'],
    };
}

export function CoreWatchlistTransportHttpReorderItemsRequestToJSON(json: any): CoreWatchlistTransportHttpReorderItemsRequest {
    return CoreWatchlistTransportHttpReorderItemsRequestToJSONTyped(json, false);
}

export function CoreWatchlistTransportHttpReorderItemsRequestToJSONTyped(value?: CoreWatchlistTransportHttpReorderItemsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemIds': value['itemIds'],
    };
}

