/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoreBacktestTransportHttpSyncBacktestRequest
 */
export interface CoreBacktestTransportHttpSyncBacktestRequest {
    /**
     * 
     * @type {string}
     * @memberof CoreBacktestTransportHttpSyncBacktestRequest
     */
    tradingRunId: string;
}

/**
 * Check if a given object implements the CoreBacktestTransportHttpSyncBacktestRequest interface.
 */
export function instanceOfCoreBacktestTransportHttpSyncBacktestRequest(value: object): value is CoreBacktestTransportHttpSyncBacktestRequest {
    if (!('tradingRunId' in value) || value['tradingRunId'] === undefined) return false;
    return true;
}

export function CoreBacktestTransportHttpSyncBacktestRequestFromJSON(json: any): CoreBacktestTransportHttpSyncBacktestRequest {
    return CoreBacktestTransportHttpSyncBacktestRequestFromJSONTyped(json, false);
}

export function CoreBacktestTransportHttpSyncBacktestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreBacktestTransportHttpSyncBacktestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tradingRunId': json['trading_run_id'],
    };
}

export function CoreBacktestTransportHttpSyncBacktestRequestToJSON(json: any): CoreBacktestTransportHttpSyncBacktestRequest {
    return CoreBacktestTransportHttpSyncBacktestRequestToJSONTyped(json, false);
}

export function CoreBacktestTransportHttpSyncBacktestRequestToJSONTyped(value?: CoreBacktestTransportHttpSyncBacktestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trading_run_id': value['tradingRunId'],
    };
}

