/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoreAlertTransportHttpForceStopContainersResponse
 */
export interface CoreAlertTransportHttpForceStopContainersResponse {
    /**
     * 
     * @type {object}
     * @memberof CoreAlertTransportHttpForceStopContainersResponse
     */
    data?: object;
}

/**
 * Check if a given object implements the CoreAlertTransportHttpForceStopContainersResponse interface.
 */
export function instanceOfCoreAlertTransportHttpForceStopContainersResponse(value: object): value is CoreAlertTransportHttpForceStopContainersResponse {
    return true;
}

export function CoreAlertTransportHttpForceStopContainersResponseFromJSON(json: any): CoreAlertTransportHttpForceStopContainersResponse {
    return CoreAlertTransportHttpForceStopContainersResponseFromJSONTyped(json, false);
}

export function CoreAlertTransportHttpForceStopContainersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreAlertTransportHttpForceStopContainersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function CoreAlertTransportHttpForceStopContainersResponseToJSON(json: any): CoreAlertTransportHttpForceStopContainersResponse {
    return CoreAlertTransportHttpForceStopContainersResponseToJSONTyped(json, false);
}

export function CoreAlertTransportHttpForceStopContainersResponseToJSONTyped(value?: CoreAlertTransportHttpForceStopContainersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

