/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InitializeContainersResponse } from './InitializeContainersResponse';
import {
    InitializeContainersResponseFromJSON,
    InitializeContainersResponseFromJSONTyped,
    InitializeContainersResponseToJSON,
    InitializeContainersResponseToJSONTyped,
} from './InitializeContainersResponse';

/**
 * 
 * @export
 * @interface CoreAlertcontainerTransportHttpInitializeContainersResponse
 */
export interface CoreAlertcontainerTransportHttpInitializeContainersResponse {
    /**
     * 
     * @type {InitializeContainersResponse}
     * @memberof CoreAlertcontainerTransportHttpInitializeContainersResponse
     */
    data?: InitializeContainersResponse;
}

/**
 * Check if a given object implements the CoreAlertcontainerTransportHttpInitializeContainersResponse interface.
 */
export function instanceOfCoreAlertcontainerTransportHttpInitializeContainersResponse(value: object): value is CoreAlertcontainerTransportHttpInitializeContainersResponse {
    return true;
}

export function CoreAlertcontainerTransportHttpInitializeContainersResponseFromJSON(json: any): CoreAlertcontainerTransportHttpInitializeContainersResponse {
    return CoreAlertcontainerTransportHttpInitializeContainersResponseFromJSONTyped(json, false);
}

export function CoreAlertcontainerTransportHttpInitializeContainersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreAlertcontainerTransportHttpInitializeContainersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : InitializeContainersResponseFromJSON(json['data']),
    };
}

export function CoreAlertcontainerTransportHttpInitializeContainersResponseToJSON(json: any): CoreAlertcontainerTransportHttpInitializeContainersResponse {
    return CoreAlertcontainerTransportHttpInitializeContainersResponseToJSONTyped(json, false);
}

export function CoreAlertcontainerTransportHttpInitializeContainersResponseToJSONTyped(value?: CoreAlertcontainerTransportHttpInitializeContainersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': InitializeContainersResponseToJSON(value['data']),
    };
}

