/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoreMarketplaceTransportHttpMarketplaceItem } from './CoreMarketplaceTransportHttpMarketplaceItem';
import {
    CoreMarketplaceTransportHttpMarketplaceItemFromJSON,
    CoreMarketplaceTransportHttpMarketplaceItemFromJSONTyped,
    CoreMarketplaceTransportHttpMarketplaceItemToJSON,
    CoreMarketplaceTransportHttpMarketplaceItemToJSONTyped,
} from './CoreMarketplaceTransportHttpMarketplaceItem';

/**
 * 
 * @export
 * @interface CoreMarketplaceTransportHttpCreateMarketplaceItemResponse
 */
export interface CoreMarketplaceTransportHttpCreateMarketplaceItemResponse {
    /**
     * 
     * @type {CoreMarketplaceTransportHttpMarketplaceItem}
     * @memberof CoreMarketplaceTransportHttpCreateMarketplaceItemResponse
     */
    data?: CoreMarketplaceTransportHttpMarketplaceItem;
}

/**
 * Check if a given object implements the CoreMarketplaceTransportHttpCreateMarketplaceItemResponse interface.
 */
export function instanceOfCoreMarketplaceTransportHttpCreateMarketplaceItemResponse(value: object): value is CoreMarketplaceTransportHttpCreateMarketplaceItemResponse {
    return true;
}

export function CoreMarketplaceTransportHttpCreateMarketplaceItemResponseFromJSON(json: any): CoreMarketplaceTransportHttpCreateMarketplaceItemResponse {
    return CoreMarketplaceTransportHttpCreateMarketplaceItemResponseFromJSONTyped(json, false);
}

export function CoreMarketplaceTransportHttpCreateMarketplaceItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreMarketplaceTransportHttpCreateMarketplaceItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : CoreMarketplaceTransportHttpMarketplaceItemFromJSON(json['data']),
    };
}

export function CoreMarketplaceTransportHttpCreateMarketplaceItemResponseToJSON(json: any): CoreMarketplaceTransportHttpCreateMarketplaceItemResponse {
    return CoreMarketplaceTransportHttpCreateMarketplaceItemResponseToJSONTyped(json, false);
}

export function CoreMarketplaceTransportHttpCreateMarketplaceItemResponseToJSONTyped(value?: CoreMarketplaceTransportHttpCreateMarketplaceItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CoreMarketplaceTransportHttpMarketplaceItemToJSON(value['data']),
    };
}

