/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Alert } from './Alert';
import {
    AlertFromJSON,
    AlertFromJSONTyped,
    AlertToJSON,
    AlertToJSONTyped,
} from './Alert';

/**
 * 
 * @export
 * @interface CoreAlertTransportHttpCreateAlertResponse
 */
export interface CoreAlertTransportHttpCreateAlertResponse {
    /**
     * 
     * @type {Alert}
     * @memberof CoreAlertTransportHttpCreateAlertResponse
     */
    data?: Alert;
}

/**
 * Check if a given object implements the CoreAlertTransportHttpCreateAlertResponse interface.
 */
export function instanceOfCoreAlertTransportHttpCreateAlertResponse(value: object): value is CoreAlertTransportHttpCreateAlertResponse {
    return true;
}

export function CoreAlertTransportHttpCreateAlertResponseFromJSON(json: any): CoreAlertTransportHttpCreateAlertResponse {
    return CoreAlertTransportHttpCreateAlertResponseFromJSONTyped(json, false);
}

export function CoreAlertTransportHttpCreateAlertResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreAlertTransportHttpCreateAlertResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AlertFromJSON(json['data']),
    };
}

export function CoreAlertTransportHttpCreateAlertResponseToJSON(json: any): CoreAlertTransportHttpCreateAlertResponse {
    return CoreAlertTransportHttpCreateAlertResponseToJSONTyped(json, false);
}

export function CoreAlertTransportHttpCreateAlertResponseToJSONTyped(value?: CoreAlertTransportHttpCreateAlertResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AlertToJSON(value['data']),
    };
}

