/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoreAlertTransportHttpTriggerAlertRequest
 */
export interface CoreAlertTransportHttpTriggerAlertRequest {
    /**
     * 
     * @type {number}
     * @memberof CoreAlertTransportHttpTriggerAlertRequest
     */
    alertId: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CoreAlertTransportHttpTriggerAlertRequest
     */
    condition: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof CoreAlertTransportHttpTriggerAlertRequest
     */
    userId: number;
}

/**
 * Check if a given object implements the CoreAlertTransportHttpTriggerAlertRequest interface.
 */
export function instanceOfCoreAlertTransportHttpTriggerAlertRequest(value: object): value is CoreAlertTransportHttpTriggerAlertRequest {
    if (!('alertId' in value) || value['alertId'] === undefined) return false;
    if (!('condition' in value) || value['condition'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function CoreAlertTransportHttpTriggerAlertRequestFromJSON(json: any): CoreAlertTransportHttpTriggerAlertRequest {
    return CoreAlertTransportHttpTriggerAlertRequestFromJSONTyped(json, false);
}

export function CoreAlertTransportHttpTriggerAlertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreAlertTransportHttpTriggerAlertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'alertId': json['alert_id'],
        'condition': json['condition'],
        'userId': json['user_id'],
    };
}

export function CoreAlertTransportHttpTriggerAlertRequestToJSON(json: any): CoreAlertTransportHttpTriggerAlertRequest {
    return CoreAlertTransportHttpTriggerAlertRequestToJSONTyped(json, false);
}

export function CoreAlertTransportHttpTriggerAlertRequestToJSONTyped(value?: CoreAlertTransportHttpTriggerAlertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alert_id': value['alertId'],
        'condition': value['condition'],
        'user_id': value['userId'],
    };
}

