/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationInfo } from './PaginationInfo';
import {
    PaginationInfoFromJSON,
    PaginationInfoFromJSONTyped,
    PaginationInfoToJSON,
    PaginationInfoToJSONTyped,
} from './PaginationInfo';
import type { WatchList } from './WatchList';
import {
    WatchListFromJSON,
    WatchListFromJSONTyped,
    WatchListToJSON,
    WatchListToJSONTyped,
} from './WatchList';

/**
 * 
 * @export
 * @interface CoreWatchlistTransportHttpListWatchListsResponse
 */
export interface CoreWatchlistTransportHttpListWatchListsResponse {
    /**
     * 
     * @type {Array<WatchList>}
     * @memberof CoreWatchlistTransportHttpListWatchListsResponse
     */
    data?: Array<WatchList>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof CoreWatchlistTransportHttpListWatchListsResponse
     */
    pagination?: PaginationInfo;
}

/**
 * Check if a given object implements the CoreWatchlistTransportHttpListWatchListsResponse interface.
 */
export function instanceOfCoreWatchlistTransportHttpListWatchListsResponse(value: object): value is CoreWatchlistTransportHttpListWatchListsResponse {
    return true;
}

export function CoreWatchlistTransportHttpListWatchListsResponseFromJSON(json: any): CoreWatchlistTransportHttpListWatchListsResponse {
    return CoreWatchlistTransportHttpListWatchListsResponseFromJSONTyped(json, false);
}

export function CoreWatchlistTransportHttpListWatchListsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreWatchlistTransportHttpListWatchListsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(WatchListFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationInfoFromJSON(json['pagination']),
    };
}

export function CoreWatchlistTransportHttpListWatchListsResponseToJSON(json: any): CoreWatchlistTransportHttpListWatchListsResponse {
    return CoreWatchlistTransportHttpListWatchListsResponseToJSONTyped(json, false);
}

export function CoreWatchlistTransportHttpListWatchListsResponseToJSONTyped(value?: CoreWatchlistTransportHttpListWatchListsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(WatchListToJSON)),
        'pagination': PaginationInfoToJSON(value['pagination']),
    };
}

