/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlertContainer } from './AlertContainer';
import {
    AlertContainerFromJSON,
    AlertContainerFromJSONTyped,
    AlertContainerToJSON,
    AlertContainerToJSONTyped,
} from './AlertContainer';

/**
 * 
 * @export
 * @interface CoreAlertcontainerTransportHttpGetContainerResponse
 */
export interface CoreAlertcontainerTransportHttpGetContainerResponse {
    /**
     * 
     * @type {AlertContainer}
     * @memberof CoreAlertcontainerTransportHttpGetContainerResponse
     */
    data?: AlertContainer;
}

/**
 * Check if a given object implements the CoreAlertcontainerTransportHttpGetContainerResponse interface.
 */
export function instanceOfCoreAlertcontainerTransportHttpGetContainerResponse(value: object): value is CoreAlertcontainerTransportHttpGetContainerResponse {
    return true;
}

export function CoreAlertcontainerTransportHttpGetContainerResponseFromJSON(json: any): CoreAlertcontainerTransportHttpGetContainerResponse {
    return CoreAlertcontainerTransportHttpGetContainerResponseFromJSONTyped(json, false);
}

export function CoreAlertcontainerTransportHttpGetContainerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreAlertcontainerTransportHttpGetContainerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AlertContainerFromJSON(json['data']),
    };
}

export function CoreAlertcontainerTransportHttpGetContainerResponseToJSON(json: any): CoreAlertcontainerTransportHttpGetContainerResponse {
    return CoreAlertcontainerTransportHttpGetContainerResponseToJSONTyped(json, false);
}

export function CoreAlertcontainerTransportHttpGetContainerResponseToJSONTyped(value?: CoreAlertcontainerTransportHttpGetContainerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AlertContainerToJSON(value['data']),
    };
}

