/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoreWatchlistTransportHttpUpdateItemRequest
 */
export interface CoreWatchlistTransportHttpUpdateItemRequest {
    /**
     * 
     * @type {string}
     * @memberof CoreWatchlistTransportHttpUpdateItemRequest
     */
    market?: string;
    /**
     * 
     * @type {string}
     * @memberof CoreWatchlistTransportHttpUpdateItemRequest
     */
    securityType?: string;
    /**
     * 
     * @type {string}
     * @memberof CoreWatchlistTransportHttpUpdateItemRequest
     */
    stock?: string;
}

/**
 * Check if a given object implements the CoreWatchlistTransportHttpUpdateItemRequest interface.
 */
export function instanceOfCoreWatchlistTransportHttpUpdateItemRequest(value: object): value is CoreWatchlistTransportHttpUpdateItemRequest {
    return true;
}

export function CoreWatchlistTransportHttpUpdateItemRequestFromJSON(json: any): CoreWatchlistTransportHttpUpdateItemRequest {
    return CoreWatchlistTransportHttpUpdateItemRequestFromJSONTyped(json, false);
}

export function CoreWatchlistTransportHttpUpdateItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreWatchlistTransportHttpUpdateItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'market': json['market'] == null ? undefined : json['market'],
        'securityType': json['securityType'] == null ? undefined : json['securityType'],
        'stock': json['stock'] == null ? undefined : json['stock'],
    };
}

export function CoreWatchlistTransportHttpUpdateItemRequestToJSON(json: any): CoreWatchlistTransportHttpUpdateItemRequest {
    return CoreWatchlistTransportHttpUpdateItemRequestToJSONTyped(json, false);
}

export function CoreWatchlistTransportHttpUpdateItemRequestToJSONTyped(value?: CoreWatchlistTransportHttpUpdateItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'market': value['market'],
        'securityType': value['securityType'],
        'stock': value['stock'],
    };
}

