/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateContainerResponse } from './CreateContainerResponse';
import {
    CreateContainerResponseFromJSON,
    CreateContainerResponseFromJSONTyped,
    CreateContainerResponseToJSON,
    CreateContainerResponseToJSONTyped,
} from './CreateContainerResponse';

/**
 * 
 * @export
 * @interface CoreAlertcontainerTransportHttpCreateContainerResponse
 */
export interface CoreAlertcontainerTransportHttpCreateContainerResponse {
    /**
     * 
     * @type {CreateContainerResponse}
     * @memberof CoreAlertcontainerTransportHttpCreateContainerResponse
     */
    data?: CreateContainerResponse;
}

/**
 * Check if a given object implements the CoreAlertcontainerTransportHttpCreateContainerResponse interface.
 */
export function instanceOfCoreAlertcontainerTransportHttpCreateContainerResponse(value: object): value is CoreAlertcontainerTransportHttpCreateContainerResponse {
    return true;
}

export function CoreAlertcontainerTransportHttpCreateContainerResponseFromJSON(json: any): CoreAlertcontainerTransportHttpCreateContainerResponse {
    return CoreAlertcontainerTransportHttpCreateContainerResponseFromJSONTyped(json, false);
}

export function CoreAlertcontainerTransportHttpCreateContainerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreAlertcontainerTransportHttpCreateContainerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : CreateContainerResponseFromJSON(json['data']),
    };
}

export function CoreAlertcontainerTransportHttpCreateContainerResponseToJSON(json: any): CoreAlertcontainerTransportHttpCreateContainerResponse {
    return CoreAlertcontainerTransportHttpCreateContainerResponseToJSONTyped(json, false);
}

export function CoreAlertcontainerTransportHttpCreateContainerResponseToJSONTyped(value?: CoreAlertcontainerTransportHttpCreateContainerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CreateContainerResponseToJSON(value['data']),
    };
}

