/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseResponseMarketplaceAlgoResult } from './BaseResponseMarketplaceAlgoResult';
import {
    BaseResponseMarketplaceAlgoResultFromJSON,
    BaseResponseMarketplaceAlgoResultFromJSONTyped,
    BaseResponseMarketplaceAlgoResultToJSON,
    BaseResponseMarketplaceAlgoResultToJSONTyped,
} from './BaseResponseMarketplaceAlgoResult';
import type { BaseResponseMarketplaceUser } from './BaseResponseMarketplaceUser';
import {
    BaseResponseMarketplaceUserFromJSON,
    BaseResponseMarketplaceUserFromJSONTyped,
    BaseResponseMarketplaceUserToJSON,
    BaseResponseMarketplaceUserToJSONTyped,
} from './BaseResponseMarketplaceUser';

/**
 * 
 * @export
 * @interface CoreMarketplaceTransportHttpMarketplaceItemDetail
 */
export interface CoreMarketplaceTransportHttpMarketplaceItemDetail {
    /**
     * 
     * @type {BaseResponseMarketplaceAlgoResult}
     * @memberof CoreMarketplaceTransportHttpMarketplaceItemDetail
     */
    algoResult?: BaseResponseMarketplaceAlgoResult;
    /**
     * 
     * @type {number}
     * @memberof CoreMarketplaceTransportHttpMarketplaceItemDetail
     */
    algoMasterId?: number;
    /**
     * 
     * @type {number}
     * @memberof CoreMarketplaceTransportHttpMarketplaceItemDetail
     */
    algoResultId?: number;
    /**
     * 
     * @type {string}
     * @memberof CoreMarketplaceTransportHttpMarketplaceItemDetail
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof CoreMarketplaceTransportHttpMarketplaceItemDetail
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CoreMarketplaceTransportHttpMarketplaceItemDetail
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CoreMarketplaceTransportHttpMarketplaceItemDetail
     */
    imageUrl?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CoreMarketplaceTransportHttpMarketplaceItemDetail
     */
    indicators?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof CoreMarketplaceTransportHttpMarketplaceItemDetail
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CoreMarketplaceTransportHttpMarketplaceItemDetail
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CoreMarketplaceTransportHttpMarketplaceItemDetail
     */
    updatedAt?: string;
    /**
     * 
     * @type {BaseResponseMarketplaceUser}
     * @memberof CoreMarketplaceTransportHttpMarketplaceItemDetail
     */
    user?: BaseResponseMarketplaceUser;
    /**
     * 
     * @type {number}
     * @memberof CoreMarketplaceTransportHttpMarketplaceItemDetail
     */
    userId?: number;
}

/**
 * Check if a given object implements the CoreMarketplaceTransportHttpMarketplaceItemDetail interface.
 */
export function instanceOfCoreMarketplaceTransportHttpMarketplaceItemDetail(value: object): value is CoreMarketplaceTransportHttpMarketplaceItemDetail {
    return true;
}

export function CoreMarketplaceTransportHttpMarketplaceItemDetailFromJSON(json: any): CoreMarketplaceTransportHttpMarketplaceItemDetail {
    return CoreMarketplaceTransportHttpMarketplaceItemDetailFromJSONTyped(json, false);
}

export function CoreMarketplaceTransportHttpMarketplaceItemDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreMarketplaceTransportHttpMarketplaceItemDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'algoResult': json['algoResult'] == null ? undefined : BaseResponseMarketplaceAlgoResultFromJSON(json['algoResult']),
        'algoMasterId': json['algo_master_id'] == null ? undefined : json['algo_master_id'],
        'algoResultId': json['algo_result_id'] == null ? undefined : json['algo_result_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'indicators': json['indicators'] == null ? undefined : json['indicators'],
        'isDeleted': json['is_deleted'] == null ? undefined : json['is_deleted'],
        'name': json['name'] == null ? undefined : json['name'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'user': json['user'] == null ? undefined : BaseResponseMarketplaceUserFromJSON(json['user']),
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function CoreMarketplaceTransportHttpMarketplaceItemDetailToJSON(json: any): CoreMarketplaceTransportHttpMarketplaceItemDetail {
    return CoreMarketplaceTransportHttpMarketplaceItemDetailToJSONTyped(json, false);
}

export function CoreMarketplaceTransportHttpMarketplaceItemDetailToJSONTyped(value?: CoreMarketplaceTransportHttpMarketplaceItemDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'algoResult': BaseResponseMarketplaceAlgoResultToJSON(value['algoResult']),
        'algo_master_id': value['algoMasterId'],
        'algo_result_id': value['algoResultId'],
        'created_at': value['createdAt'],
        'description': value['description'],
        'id': value['id'],
        'image_url': value['imageUrl'],
        'indicators': value['indicators'],
        'is_deleted': value['isDeleted'],
        'name': value['name'],
        'updated_at': value['updatedAt'],
        'user': BaseResponseMarketplaceUserToJSON(value['user']),
        'user_id': value['userId'],
    };
}

