/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoreMarketplaceTransportHttpClonedStrategy } from './CoreMarketplaceTransportHttpClonedStrategy';
import {
    CoreMarketplaceTransportHttpClonedStrategyFromJSON,
    CoreMarketplaceTransportHttpClonedStrategyFromJSONTyped,
    CoreMarketplaceTransportHttpClonedStrategyToJSON,
    CoreMarketplaceTransportHttpClonedStrategyToJSONTyped,
} from './CoreMarketplaceTransportHttpClonedStrategy';

/**
 * 
 * @export
 * @interface CoreMarketplaceTransportHttpCloneStrategyResponse
 */
export interface CoreMarketplaceTransportHttpCloneStrategyResponse {
    /**
     * 
     * @type {CoreMarketplaceTransportHttpClonedStrategy}
     * @memberof CoreMarketplaceTransportHttpCloneStrategyResponse
     */
    data?: CoreMarketplaceTransportHttpClonedStrategy;
}

/**
 * Check if a given object implements the CoreMarketplaceTransportHttpCloneStrategyResponse interface.
 */
export function instanceOfCoreMarketplaceTransportHttpCloneStrategyResponse(value: object): value is CoreMarketplaceTransportHttpCloneStrategyResponse {
    return true;
}

export function CoreMarketplaceTransportHttpCloneStrategyResponseFromJSON(json: any): CoreMarketplaceTransportHttpCloneStrategyResponse {
    return CoreMarketplaceTransportHttpCloneStrategyResponseFromJSONTyped(json, false);
}

export function CoreMarketplaceTransportHttpCloneStrategyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreMarketplaceTransportHttpCloneStrategyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : CoreMarketplaceTransportHttpClonedStrategyFromJSON(json['data']),
    };
}

export function CoreMarketplaceTransportHttpCloneStrategyResponseToJSON(json: any): CoreMarketplaceTransportHttpCloneStrategyResponse {
    return CoreMarketplaceTransportHttpCloneStrategyResponseToJSONTyped(json, false);
}

export function CoreMarketplaceTransportHttpCloneStrategyResponseToJSONTyped(value?: CoreMarketplaceTransportHttpCloneStrategyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CoreMarketplaceTransportHttpClonedStrategyToJSON(value['data']),
    };
}

