/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ForceStopContainersResponse } from './ForceStopContainersResponse';
import {
    ForceStopContainersResponseFromJSON,
    ForceStopContainersResponseFromJSONTyped,
    ForceStopContainersResponseToJSON,
    ForceStopContainersResponseToJSONTyped,
} from './ForceStopContainersResponse';

/**
 * 
 * @export
 * @interface CoreAlertcontainerTransportHttpForceStopContainersResponse
 */
export interface CoreAlertcontainerTransportHttpForceStopContainersResponse {
    /**
     * 
     * @type {ForceStopContainersResponse}
     * @memberof CoreAlertcontainerTransportHttpForceStopContainersResponse
     */
    data?: ForceStopContainersResponse;
}

/**
 * Check if a given object implements the CoreAlertcontainerTransportHttpForceStopContainersResponse interface.
 */
export function instanceOfCoreAlertcontainerTransportHttpForceStopContainersResponse(value: object): value is CoreAlertcontainerTransportHttpForceStopContainersResponse {
    return true;
}

export function CoreAlertcontainerTransportHttpForceStopContainersResponseFromJSON(json: any): CoreAlertcontainerTransportHttpForceStopContainersResponse {
    return CoreAlertcontainerTransportHttpForceStopContainersResponseFromJSONTyped(json, false);
}

export function CoreAlertcontainerTransportHttpForceStopContainersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreAlertcontainerTransportHttpForceStopContainersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ForceStopContainersResponseFromJSON(json['data']),
    };
}

export function CoreAlertcontainerTransportHttpForceStopContainersResponseToJSON(json: any): CoreAlertcontainerTransportHttpForceStopContainersResponse {
    return CoreAlertcontainerTransportHttpForceStopContainersResponseToJSONTyped(json, false);
}

export function CoreAlertcontainerTransportHttpForceStopContainersResponseToJSONTyped(value?: CoreAlertcontainerTransportHttpForceStopContainersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ForceStopContainersResponseToJSON(value['data']),
    };
}

