/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateStockItemRequest } from './CreateStockItemRequest';
import {
    CreateStockItemRequestFromJSON,
    CreateStockItemRequestFromJSONTyped,
    CreateStockItemRequestToJSON,
    CreateStockItemRequestToJSONTyped,
} from './CreateStockItemRequest';

/**
 * 
 * @export
 * @interface CoreWatchlistTransportHttpBulkCreateItemsRequest
 */
export interface CoreWatchlistTransportHttpBulkCreateItemsRequest {
    /**
     * 
     * @type {Array<CreateStockItemRequest>}
     * @memberof CoreWatchlistTransportHttpBulkCreateItemsRequest
     */
    items: Array<CreateStockItemRequest>;
}

/**
 * Check if a given object implements the CoreWatchlistTransportHttpBulkCreateItemsRequest interface.
 */
export function instanceOfCoreWatchlistTransportHttpBulkCreateItemsRequest(value: object): value is CoreWatchlistTransportHttpBulkCreateItemsRequest {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function CoreWatchlistTransportHttpBulkCreateItemsRequestFromJSON(json: any): CoreWatchlistTransportHttpBulkCreateItemsRequest {
    return CoreWatchlistTransportHttpBulkCreateItemsRequestFromJSONTyped(json, false);
}

export function CoreWatchlistTransportHttpBulkCreateItemsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreWatchlistTransportHttpBulkCreateItemsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(CreateStockItemRequestFromJSON)),
    };
}

export function CoreWatchlistTransportHttpBulkCreateItemsRequestToJSON(json: any): CoreWatchlistTransportHttpBulkCreateItemsRequest {
    return CoreWatchlistTransportHttpBulkCreateItemsRequestToJSONTyped(json, false);
}

export function CoreWatchlistTransportHttpBulkCreateItemsRequestToJSONTyped(value?: CoreWatchlistTransportHttpBulkCreateItemsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(CreateStockItemRequestToJSON)),
    };
}

