/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoreMarketplaceTransportHttpPaginatedMarketplaceResponse } from './CoreMarketplaceTransportHttpPaginatedMarketplaceResponse';
import {
    CoreMarketplaceTransportHttpPaginatedMarketplaceResponseFromJSON,
    CoreMarketplaceTransportHttpPaginatedMarketplaceResponseFromJSONTyped,
    CoreMarketplaceTransportHttpPaginatedMarketplaceResponseToJSON,
    CoreMarketplaceTransportHttpPaginatedMarketplaceResponseToJSONTyped,
} from './CoreMarketplaceTransportHttpPaginatedMarketplaceResponse';

/**
 * 
 * @export
 * @interface CoreMarketplaceTransportHttpListMarketplaceStrategiesResponse
 */
export interface CoreMarketplaceTransportHttpListMarketplaceStrategiesResponse {
    /**
     * 
     * @type {CoreMarketplaceTransportHttpPaginatedMarketplaceResponse}
     * @memberof CoreMarketplaceTransportHttpListMarketplaceStrategiesResponse
     */
    data?: CoreMarketplaceTransportHttpPaginatedMarketplaceResponse;
}

/**
 * Check if a given object implements the CoreMarketplaceTransportHttpListMarketplaceStrategiesResponse interface.
 */
export function instanceOfCoreMarketplaceTransportHttpListMarketplaceStrategiesResponse(value: object): value is CoreMarketplaceTransportHttpListMarketplaceStrategiesResponse {
    return true;
}

export function CoreMarketplaceTransportHttpListMarketplaceStrategiesResponseFromJSON(json: any): CoreMarketplaceTransportHttpListMarketplaceStrategiesResponse {
    return CoreMarketplaceTransportHttpListMarketplaceStrategiesResponseFromJSONTyped(json, false);
}

export function CoreMarketplaceTransportHttpListMarketplaceStrategiesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreMarketplaceTransportHttpListMarketplaceStrategiesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : CoreMarketplaceTransportHttpPaginatedMarketplaceResponseFromJSON(json['data']),
    };
}

export function CoreMarketplaceTransportHttpListMarketplaceStrategiesResponseToJSON(json: any): CoreMarketplaceTransportHttpListMarketplaceStrategiesResponse {
    return CoreMarketplaceTransportHttpListMarketplaceStrategiesResponseToJSONTyped(json, false);
}

export function CoreMarketplaceTransportHttpListMarketplaceStrategiesResponseToJSONTyped(value?: CoreMarketplaceTransportHttpListMarketplaceStrategiesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CoreMarketplaceTransportHttpPaginatedMarketplaceResponseToJSON(value['data']),
    };
}

