/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StrategyAlert } from './StrategyAlert';
import {
    StrategyAlertFromJSON,
    StrategyAlertFromJSONTyped,
    StrategyAlertToJSON,
    StrategyAlertToJSONTyped,
} from './StrategyAlert';

/**
 * 
 * @export
 * @interface CreateAlertResponse
 */
export interface CreateAlertResponse {
    /**
     * 
     * @type {StrategyAlert}
     * @memberof CreateAlertResponse
     */
    alert?: StrategyAlert;
    /**
     * 
     * @type {string}
     * @memberof CreateAlertResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the CreateAlertResponse interface.
 */
export function instanceOfCreateAlertResponse(value: object): value is CreateAlertResponse {
    return true;
}

export function CreateAlertResponseFromJSON(json: any): CreateAlertResponse {
    return CreateAlertResponseFromJSONTyped(json, false);
}

export function CreateAlertResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAlertResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'alert': json['alert'] == null ? undefined : StrategyAlertFromJSON(json['alert']),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function CreateAlertResponseToJSON(json: any): CreateAlertResponse {
    return CreateAlertResponseToJSONTyped(json, false);
}

export function CreateAlertResponseToJSONTyped(value?: CreateAlertResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alert': StrategyAlertToJSON(value['alert']),
        'message': value['message'],
    };
}

