/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionRequest } from './PermissionRequest';
import {
    PermissionRequestFromJSON,
    PermissionRequestFromJSONTyped,
    PermissionRequestToJSON,
    PermissionRequestToJSONTyped,
} from './PermissionRequest';

/**
 * 
 * @export
 * @interface CreateAPIKeyRequest
 */
export interface CreateAPIKeyRequest {
    /**
     * 
     * @type {Date}
     * @memberof CreateAPIKeyRequest
     */
    expiresAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateAPIKeyRequest
     */
    name: string;
    /**
     * At least one permission is required
     * @type {Array<PermissionRequest>}
     * @memberof CreateAPIKeyRequest
     */
    permissions: Array<PermissionRequest>;
    /**
     * 
     * @type {string}
     * @memberof CreateAPIKeyRequest
     */
    serviceName?: string;
}

/**
 * Check if a given object implements the CreateAPIKeyRequest interface.
 */
export function instanceOfCreateAPIKeyRequest(value: object): value is CreateAPIKeyRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function CreateAPIKeyRequestFromJSON(json: any): CreateAPIKeyRequest {
    return CreateAPIKeyRequestFromJSONTyped(json, false);
}

export function CreateAPIKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAPIKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'name': json['name'],
        'permissions': ((json['permissions'] as Array<any>).map(PermissionRequestFromJSON)),
        'serviceName': json['service_name'] == null ? undefined : json['service_name'],
    };
}

export function CreateAPIKeyRequestToJSON(json: any): CreateAPIKeyRequest {
    return CreateAPIKeyRequestToJSONTyped(json, false);
}

export function CreateAPIKeyRequestToJSONTyped(value?: CreateAPIKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'name': value['name'],
        'permissions': ((value['permissions'] as Array<any>).map(PermissionRequestToJSON)),
        'service_name': value['serviceName'],
    };
}

