/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCheckoutSessionRequest
 */
export interface CreateCheckoutSessionRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateCheckoutSessionRequest
     */
    billingPeriodId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCheckoutSessionRequest
     */
    cancelUrl: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCheckoutSessionRequest
     */
    planId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCheckoutSessionRequest
     */
    successUrl: string;
}

/**
 * Check if a given object implements the CreateCheckoutSessionRequest interface.
 */
export function instanceOfCreateCheckoutSessionRequest(value: object): value is CreateCheckoutSessionRequest {
    if (!('billingPeriodId' in value) || value['billingPeriodId'] === undefined) return false;
    if (!('cancelUrl' in value) || value['cancelUrl'] === undefined) return false;
    if (!('planId' in value) || value['planId'] === undefined) return false;
    if (!('successUrl' in value) || value['successUrl'] === undefined) return false;
    return true;
}

export function CreateCheckoutSessionRequestFromJSON(json: any): CreateCheckoutSessionRequest {
    return CreateCheckoutSessionRequestFromJSONTyped(json, false);
}

export function CreateCheckoutSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCheckoutSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'billingPeriodId': json['billing_period_id'],
        'cancelUrl': json['cancel_url'],
        'planId': json['plan_id'],
        'successUrl': json['success_url'],
    };
}

export function CreateCheckoutSessionRequestToJSON(json: any): CreateCheckoutSessionRequest {
    return CreateCheckoutSessionRequestToJSONTyped(json, false);
}

export function CreateCheckoutSessionRequestToJSONTyped(value?: CreateCheckoutSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'billing_period_id': value['billingPeriodId'],
        'cancel_url': value['cancelUrl'],
        'plan_id': value['planId'],
        'success_url': value['successUrl'],
    };
}

