/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCheckoutSessionResponse
 */
export interface CreateCheckoutSessionResponse {
    /**
     * 
     * @type {number}
     * @memberof CreateCheckoutSessionResponse
     */
    billingPeriodId?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCheckoutSessionResponse
     */
    checkoutUrl?: string;
}

/**
 * Check if a given object implements the CreateCheckoutSessionResponse interface.
 */
export function instanceOfCreateCheckoutSessionResponse(value: object): value is CreateCheckoutSessionResponse {
    return true;
}

export function CreateCheckoutSessionResponseFromJSON(json: any): CreateCheckoutSessionResponse {
    return CreateCheckoutSessionResponseFromJSONTyped(json, false);
}

export function CreateCheckoutSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCheckoutSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'billingPeriodId': json['billing_period_id'] == null ? undefined : json['billing_period_id'],
        'checkoutUrl': json['checkout_url'] == null ? undefined : json['checkout_url'],
    };
}

export function CreateCheckoutSessionResponseToJSON(json: any): CreateCheckoutSessionResponse {
    return CreateCheckoutSessionResponseToJSONTyped(json, false);
}

export function CreateCheckoutSessionResponseToJSONTyped(value?: CreateCheckoutSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'billing_period_id': value['billingPeriodId'],
        'checkout_url': value['checkoutUrl'],
    };
}

