/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APIKey } from './APIKey';
import {
    APIKeyFromJSON,
    APIKeyFromJSONTyped,
    APIKeyToJSON,
    APIKeyToJSONTyped,
} from './APIKey';

/**
 * 
 * @export
 * @interface CreateAPIKeyResponse
 */
export interface CreateAPIKeyResponse {
    /**
     * 
     * @type {APIKey}
     * @memberof CreateAPIKeyResponse
     */
    apiKey?: APIKey;
    /**
     * Only returned once during creation
     * @type {string}
     * @memberof CreateAPIKeyResponse
     */
    plaintextKey?: string;
}

/**
 * Check if a given object implements the CreateAPIKeyResponse interface.
 */
export function instanceOfCreateAPIKeyResponse(value: object): value is CreateAPIKeyResponse {
    return true;
}

export function CreateAPIKeyResponseFromJSON(json: any): CreateAPIKeyResponse {
    return CreateAPIKeyResponseFromJSONTyped(json, false);
}

export function CreateAPIKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAPIKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['api_key'] == null ? undefined : APIKeyFromJSON(json['api_key']),
        'plaintextKey': json['plaintext_key'] == null ? undefined : json['plaintext_key'],
    };
}

export function CreateAPIKeyResponseToJSON(json: any): CreateAPIKeyResponse {
    return CreateAPIKeyResponseToJSONTyped(json, false);
}

export function CreateAPIKeyResponseToJSONTyped(value?: CreateAPIKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_key': APIKeyToJSON(value['apiKey']),
        'plaintext_key': value['plaintextKey'],
    };
}

