/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BillingPeriodDetail } from './BillingPeriodDetail';
import {
    BillingPeriodDetailFromJSON,
    BillingPeriodDetailFromJSONTyped,
    BillingPeriodDetailToJSON,
    BillingPeriodDetailToJSONTyped,
} from './BillingPeriodDetail';

/**
 * 
 * @export
 * @interface CurrentPlan
 */
export interface CurrentPlan {
    /**
     * 
     * @type {BillingPeriodDetail}
     * @memberof CurrentPlan
     */
    billingPeriod?: BillingPeriodDetail;
    /**
     * 
     * @type {string}
     * @memberof CurrentPlan
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentPlan
     */
    expiryDate?: string;
    /**
     * 
     * @type {number}
     * @memberof CurrentPlan
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CurrentPlan
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof CurrentPlan
     */
    planPricingId?: number;
}

/**
 * Check if a given object implements the CurrentPlan interface.
 */
export function instanceOfCurrentPlan(value: object): value is CurrentPlan {
    return true;
}

export function CurrentPlanFromJSON(json: any): CurrentPlan {
    return CurrentPlanFromJSONTyped(json, false);
}

export function CurrentPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentPlan {
    if (json == null) {
        return json;
    }
    return {
        
        'billingPeriod': json['billing_period'] == null ? undefined : BillingPeriodDetailFromJSON(json['billing_period']),
        'code': json['code'] == null ? undefined : json['code'],
        'expiryDate': json['expiry_date'] == null ? undefined : json['expiry_date'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'planPricingId': json['plan_pricing_id'] == null ? undefined : json['plan_pricing_id'],
    };
}

export function CurrentPlanToJSON(json: any): CurrentPlan {
    return CurrentPlanToJSONTyped(json, false);
}

export function CurrentPlanToJSONTyped(value?: CurrentPlan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'billing_period': BillingPeriodDetailToJSON(value['billingPeriod']),
        'code': value['code'],
        'expiry_date': value['expiryDate'],
        'id': value['id'],
        'name': value['name'],
        'plan_pricing_id': value['planPricingId'],
    };
}

