/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlertContainer } from './AlertContainer';
import {
    AlertContainerFromJSON,
    AlertContainerFromJSONTyped,
    AlertContainerToJSON,
    AlertContainerToJSONTyped,
} from './AlertContainer';

/**
 * 
 * @export
 * @interface ForceStopContainersResponse
 */
export interface ForceStopContainersResponse {
    /**
     * 
     * @type {Array<AlertContainer>}
     * @memberof ForceStopContainersResponse
     */
    containers?: Array<AlertContainer>;
    /**
     * 
     * @type {number}
     * @memberof ForceStopContainersResponse
     */
    failed?: number;
    /**
     * 
     * @type {number}
     * @memberof ForceStopContainersResponse
     */
    stopped?: number;
    /**
     * 
     * @type {number}
     * @memberof ForceStopContainersResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the ForceStopContainersResponse interface.
 */
export function instanceOfForceStopContainersResponse(value: object): value is ForceStopContainersResponse {
    return true;
}

export function ForceStopContainersResponseFromJSON(json: any): ForceStopContainersResponse {
    return ForceStopContainersResponseFromJSONTyped(json, false);
}

export function ForceStopContainersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForceStopContainersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'containers': json['containers'] == null ? undefined : ((json['containers'] as Array<any>).map(AlertContainerFromJSON)),
        'failed': json['failed'] == null ? undefined : json['failed'],
        'stopped': json['stopped'] == null ? undefined : json['stopped'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ForceStopContainersResponseToJSON(json: any): ForceStopContainersResponse {
    return ForceStopContainersResponseToJSONTyped(json, false);
}

export function ForceStopContainersResponseToJSONTyped(value?: ForceStopContainersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'containers': value['containers'] == null ? undefined : ((value['containers'] as Array<any>).map(AlertContainerToJSON)),
        'failed': value['failed'],
        'stopped': value['stopped'],
        'total': value['total'],
    };
}

