/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TradingRun } from './TradingRun';
import {
    TradingRunFromJSON,
    TradingRunFromJSONTyped,
    TradingRunToJSON,
    TradingRunToJSONTyped,
} from './TradingRun';
import type { RunStatus } from './RunStatus';
import {
    RunStatusFromJSON,
    RunStatusFromJSONTyped,
    RunStatusToJSON,
    RunStatusToJSONTyped,
} from './RunStatus';

/**
 * 
 * @export
 * @interface GetBotStatusResponse
 */
export interface GetBotStatusResponse {
    /**
     * 
     * @type {number}
     * @memberof GetBotStatusResponse
     */
    botId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetBotStatusResponse
     */
    isRunning?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetBotStatusResponse
     */
    message?: string;
    /**
     * 
     * @type {RunStatus}
     * @memberof GetBotStatusResponse
     */
    status?: RunStatus;
    /**
     * Latest trading run
     * @type {TradingRun}
     * @memberof GetBotStatusResponse
     */
    tradingRun?: TradingRun;
    /**
     * 
     * @type {string}
     * @memberof GetBotStatusResponse
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof GetBotStatusResponse
     */
    userId?: number;
}



/**
 * Check if a given object implements the GetBotStatusResponse interface.
 */
export function instanceOfGetBotStatusResponse(value: object): value is GetBotStatusResponse {
    return true;
}

export function GetBotStatusResponseFromJSON(json: any): GetBotStatusResponse {
    return GetBotStatusResponseFromJSONTyped(json, false);
}

export function GetBotStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBotStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'botId': json['bot_id'] == null ? undefined : json['bot_id'],
        'isRunning': json['isRunning'] == null ? undefined : json['isRunning'],
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : RunStatusFromJSON(json['status']),
        'tradingRun': json['tradingRun'] == null ? undefined : TradingRunFromJSON(json['tradingRun']),
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function GetBotStatusResponseToJSON(json: any): GetBotStatusResponse {
    return GetBotStatusResponseToJSONTyped(json, false);
}

export function GetBotStatusResponseToJSONTyped(value?: GetBotStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bot_id': value['botId'],
        'isRunning': value['isRunning'],
        'message': value['message'],
        'status': RunStatusToJSON(value['status']),
        'tradingRun': TradingRunToJSON(value['tradingRun']),
        'updated_at': value['updatedAt'],
        'user_id': value['userId'],
    };
}

