/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPresignedUploadURLRequest
 */
export interface GetPresignedUploadURLRequest {
    /**
     * 
     * @type {string}
     * @memberof GetPresignedUploadURLRequest
     */
    extension: string;
    /**
     * 
     * @type {GetPresignedUploadURLRequestFolderEnum}
     * @memberof GetPresignedUploadURLRequest
     */
    folder: GetPresignedUploadURLRequestFolderEnum;
}

/**
* @export
* @enum {string}
*/
export enum GetPresignedUploadURLRequestFolderEnum {
    Marketplace = 'marketplace',
    Avatar = 'avatar',
    Bot = 'bot',
    Strategy = 'strategy',
    Documents = 'documents'
}


/**
 * Check if a given object implements the GetPresignedUploadURLRequest interface.
 */
export function instanceOfGetPresignedUploadURLRequest(value: object): value is GetPresignedUploadURLRequest {
    if (!('extension' in value) || value['extension'] === undefined) return false;
    if (!('folder' in value) || value['folder'] === undefined) return false;
    return true;
}

export function GetPresignedUploadURLRequestFromJSON(json: any): GetPresignedUploadURLRequest {
    return GetPresignedUploadURLRequestFromJSONTyped(json, false);
}

export function GetPresignedUploadURLRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPresignedUploadURLRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'extension': json['extension'],
        'folder': json['folder'],
    };
}

export function GetPresignedUploadURLRequestToJSON(json: any): GetPresignedUploadURLRequest {
    return GetPresignedUploadURLRequestToJSONTyped(json, false);
}

export function GetPresignedUploadURLRequestToJSONTyped(value?: GetPresignedUploadURLRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'extension': value['extension'],
        'folder': value['folder'],
    };
}

