/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HTTPSubmitResearchRequest
 */
export interface HTTPSubmitResearchRequest {
    /**
     * 
     * @type {string}
     * @memberof HTTPSubmitResearchRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof HTTPSubmitResearchRequest
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof HTTPSubmitResearchRequest
     */
    tags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof HTTPSubmitResearchRequest
     */
    treeJson: string;
}

/**
 * Check if a given object implements the HTTPSubmitResearchRequest interface.
 */
export function instanceOfHTTPSubmitResearchRequest(value: object): value is HTTPSubmitResearchRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('treeJson' in value) || value['treeJson'] === undefined) return false;
    return true;
}

export function HTTPSubmitResearchRequestFromJSON(json: any): HTTPSubmitResearchRequest {
    return HTTPSubmitResearchRequestFromJSONTyped(json, false);
}

export function HTTPSubmitResearchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HTTPSubmitResearchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'treeJson': json['treeJson'],
    };
}

export function HTTPSubmitResearchRequestToJSON(json: any): HTTPSubmitResearchRequest {
    return HTTPSubmitResearchRequestToJSONTyped(json, false);
}

export function HTTPSubmitResearchRequestToJSONTyped(value?: HTTPSubmitResearchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'tags': value['tags'],
        'treeJson': value['treeJson'],
    };
}

