/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HttpLiveTradeStatusResponse
 */
export interface HttpLiveTradeStatusResponse {
    /**
     * 
     * @type {boolean}
     * @memberof HttpLiveTradeStatusResponse
     */
    status?: boolean;
}

/**
 * Check if a given object implements the HttpLiveTradeStatusResponse interface.
 */
export function instanceOfHttpLiveTradeStatusResponse(value: object): value is HttpLiveTradeStatusResponse {
    return true;
}

export function HttpLiveTradeStatusResponseFromJSON(json: any): HttpLiveTradeStatusResponse {
    return HttpLiveTradeStatusResponseFromJSONTyped(json, false);
}

export function HttpLiveTradeStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpLiveTradeStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function HttpLiveTradeStatusResponseToJSON(json: any): HttpLiveTradeStatusResponse {
    return HttpLiveTradeStatusResponseToJSONTyped(json, false);
}

export function HttpLiveTradeStatusResponseToJSONTyped(value?: HttpLiveTradeStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

