/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum HttpTradeType {
    TradeTypeReal = 'REAL',
    TradeTypePaper = 'PAPER'
}


export function instanceOfHttpTradeType(value: any): boolean {
    for (const key in HttpTradeType) {
        if (Object.prototype.hasOwnProperty.call(HttpTradeType, key)) {
            if (HttpTradeType[key as keyof typeof HttpTradeType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function HttpTradeTypeFromJSON(json: any): HttpTradeType {
    return HttpTradeTypeFromJSONTyped(json, false);
}

export function HttpTradeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpTradeType {
    return json as HttpTradeType;
}

export function HttpTradeTypeToJSON(value?: HttpTradeType | null): any {
    return value as any;
}

export function HttpTradeTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): HttpTradeType {
    return value as HttpTradeType;
}

