/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseResponseMetadataIndicatorConfig } from './BaseResponseMetadataIndicatorConfig';
import {
    BaseResponseMetadataIndicatorConfigFromJSON,
    BaseResponseMetadataIndicatorConfigFromJSONTyped,
    BaseResponseMetadataIndicatorConfigToJSON,
    BaseResponseMetadataIndicatorConfigToJSONTyped,
} from './BaseResponseMetadataIndicatorConfig';

/**
 * 
 * @export
 * @interface IndicatorMetadata
 */
export interface IndicatorMetadata {
    /**
     * 
     * @type {string}
     * @memberof IndicatorMetadata
     */
    createdAt?: string;
    /**
     * 
     * @type {Array<BaseResponseMetadataIndicatorConfig>}
     * @memberof IndicatorMetadata
     */
    fields?: Array<BaseResponseMetadataIndicatorConfig>;
    /**
     * 
     * @type {number}
     * @memberof IndicatorMetadata
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof IndicatorMetadata
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof IndicatorMetadata
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof IndicatorMetadata
     */
    level?: string;
    /**
     * 
     * @type {string}
     * @memberof IndicatorMetadata
     */
    shortLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof IndicatorMetadata
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the IndicatorMetadata interface.
 */
export function instanceOfIndicatorMetadata(value: object): value is IndicatorMetadata {
    return true;
}

export function IndicatorMetadataFromJSON(json: any): IndicatorMetadata {
    return IndicatorMetadataFromJSONTyped(json, false);
}

export function IndicatorMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndicatorMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'fields': json['fields'] == null ? undefined : ((json['fields'] as Array<any>).map(BaseResponseMetadataIndicatorConfigFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'label': json['label'] == null ? undefined : json['label'],
        'level': json['level'] == null ? undefined : json['level'],
        'shortLabel': json['shortLabel'] == null ? undefined : json['shortLabel'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function IndicatorMetadataToJSON(json: any): IndicatorMetadata {
    return IndicatorMetadataToJSONTyped(json, false);
}

export function IndicatorMetadataToJSONTyped(value?: IndicatorMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'fields': value['fields'] == null ? undefined : ((value['fields'] as Array<any>).map(BaseResponseMetadataIndicatorConfigToJSON)),
        'id': value['id'],
        'key': value['key'],
        'label': value['label'],
        'level': value['level'],
        'shortLabel': value['shortLabel'],
        'updatedAt': value['updatedAt'],
    };
}

