/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationInfo } from './PaginationInfo';
import {
    PaginationInfoFromJSON,
    PaginationInfoFromJSONTyped,
    PaginationInfoToJSON,
    PaginationInfoToJSONTyped,
} from './PaginationInfo';
import type { TradingRun } from './TradingRun';
import {
    TradingRunFromJSON,
    TradingRunFromJSONTyped,
    TradingRunToJSON,
    TradingRunToJSONTyped,
} from './TradingRun';
import type { TradingRunsSummary } from './TradingRunsSummary';
import {
    TradingRunsSummaryFromJSON,
    TradingRunsSummaryFromJSONTyped,
    TradingRunsSummaryToJSON,
    TradingRunsSummaryToJSONTyped,
} from './TradingRunsSummary';

/**
 * 
 * @export
 * @interface ListTradingRunsResponse
 */
export interface ListTradingRunsResponse {
    /**
     * 
     * @type {Array<TradingRun>}
     * @memberof ListTradingRunsResponse
     */
    data?: Array<TradingRun>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof ListTradingRunsResponse
     */
    pagination?: PaginationInfo;
    /**
     * 
     * @type {TradingRunsSummary}
     * @memberof ListTradingRunsResponse
     */
    summary?: TradingRunsSummary;
}

/**
 * Check if a given object implements the ListTradingRunsResponse interface.
 */
export function instanceOfListTradingRunsResponse(value: object): value is ListTradingRunsResponse {
    return true;
}

export function ListTradingRunsResponseFromJSON(json: any): ListTradingRunsResponse {
    return ListTradingRunsResponseFromJSONTyped(json, false);
}

export function ListTradingRunsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTradingRunsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TradingRunFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationInfoFromJSON(json['pagination']),
        'summary': json['summary'] == null ? undefined : TradingRunsSummaryFromJSON(json['summary']),
    };
}

export function ListTradingRunsResponseToJSON(json: any): ListTradingRunsResponse {
    return ListTradingRunsResponseToJSONTyped(json, false);
}

export function ListTradingRunsResponseToJSONTyped(value?: ListTradingRunsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TradingRunToJSON)),
        'pagination': PaginationInfoToJSON(value['pagination']),
        'summary': TradingRunsSummaryToJSON(value['summary']),
    };
}

