/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarkAsReadResponse
 */
export interface MarkAsReadResponse {
    /**
     * 
     * @type {number}
     * @memberof MarkAsReadResponse
     */
    count?: number;
}

/**
 * Check if a given object implements the MarkAsReadResponse interface.
 */
export function instanceOfMarkAsReadResponse(value: object): value is MarkAsReadResponse {
    return true;
}

export function MarkAsReadResponseFromJSON(json: any): MarkAsReadResponse {
    return MarkAsReadResponseFromJSONTyped(json, false);
}

export function MarkAsReadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkAsReadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function MarkAsReadResponseToJSON(json: any): MarkAsReadResponse {
    return MarkAsReadResponseToJSONTyped(json, false);
}

export function MarkAsReadResponseToJSONTyped(value?: MarkAsReadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
    };
}

