/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OHLCVDataPoint
 */
export interface OHLCVDataPoint {
    /**
     * 
     * @type {number}
     * @memberof OHLCVDataPoint
     */
    close?: number;
    /**
     * 
     * @type {number}
     * @memberof OHLCVDataPoint
     */
    high?: number;
    /**
     * 
     * @type {number}
     * @memberof OHLCVDataPoint
     */
    low?: number;
    /**
     * 
     * @type {number}
     * @memberof OHLCVDataPoint
     */
    open?: number;
    /**
     * 
     * @type {number}
     * @memberof OHLCVDataPoint
     */
    timestamp?: number;
    /**
     * 
     * @type {number}
     * @memberof OHLCVDataPoint
     */
    volume?: number;
}

/**
 * Check if a given object implements the OHLCVDataPoint interface.
 */
export function instanceOfOHLCVDataPoint(value: object): value is OHLCVDataPoint {
    return true;
}

export function OHLCVDataPointFromJSON(json: any): OHLCVDataPoint {
    return OHLCVDataPointFromJSONTyped(json, false);
}

export function OHLCVDataPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): OHLCVDataPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'close': json['close'] == null ? undefined : json['close'],
        'high': json['high'] == null ? undefined : json['high'],
        'low': json['low'] == null ? undefined : json['low'],
        'open': json['open'] == null ? undefined : json['open'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'volume': json['volume'] == null ? undefined : json['volume'],
    };
}

export function OHLCVDataPointToJSON(json: any): OHLCVDataPoint {
    return OHLCVDataPointToJSONTyped(json, false);
}

export function OHLCVDataPointToJSONTyped(value?: OHLCVDataPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'close': value['close'],
        'high': value['high'],
        'low': value['low'],
        'open': value['open'],
        'timestamp': value['timestamp'],
        'volume': value['volume'],
    };
}

