/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum OptimizationStatus {
    OptimizationStatusPending = 'PENDING',
    OptimizationStatusRunning = 'RUNNING',
    OptimizationStatusCompleted = 'COMPLETED',
    OptimizationStatusFailed = 'FAILED'
}


export function instanceOfOptimizationStatus(value: any): boolean {
    for (const key in OptimizationStatus) {
        if (Object.prototype.hasOwnProperty.call(OptimizationStatus, key)) {
            if (OptimizationStatus[key as keyof typeof OptimizationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OptimizationStatusFromJSON(json: any): OptimizationStatus {
    return OptimizationStatusFromJSONTyped(json, false);
}

export function OptimizationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptimizationStatus {
    return json as OptimizationStatus;
}

export function OptimizationStatusToJSON(value?: OptimizationStatus | null): any {
    return value as any;
}

export function OptimizationStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): OptimizationStatus {
    return value as OptimizationStatus;
}

