/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum OptimizationMode {
    OptimizationModeShadow = 'SHADOW',
    OptimizationModeLive = 'LIVE',
    OptimizationModeBacktest = 'BACKTEST'
}


export function instanceOfOptimizationMode(value: any): boolean {
    for (const key in OptimizationMode) {
        if (Object.prototype.hasOwnProperty.call(OptimizationMode, key)) {
            if (OptimizationMode[key as keyof typeof OptimizationMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OptimizationModeFromJSON(json: any): OptimizationMode {
    return OptimizationModeFromJSONTyped(json, false);
}

export function OptimizationModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptimizationMode {
    return json as OptimizationMode;
}

export function OptimizationModeToJSON(value?: OptimizationMode | null): any {
    return value as any;
}

export function OptimizationModeToJSONTyped(value: any, ignoreDiscriminator: boolean): OptimizationMode {
    return value as OptimizationMode;
}

