/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationInfo } from './PaginationInfo';
import {
    PaginationInfoFromJSON,
    PaginationInfoFromJSONTyped,
    PaginationInfoToJSON,
    PaginationInfoToJSONTyped,
} from './PaginationInfo';
import type { IndicatorField } from './IndicatorField';
import {
    IndicatorFieldFromJSON,
    IndicatorFieldFromJSONTyped,
    IndicatorFieldToJSON,
    IndicatorFieldToJSONTyped,
} from './IndicatorField';

/**
 * 
 * @export
 * @interface PaginatedResponseIndicatorField
 */
export interface PaginatedResponseIndicatorField {
    /**
     * 
     * @type {Array<IndicatorField>}
     * @memberof PaginatedResponseIndicatorField
     */
    data?: Array<IndicatorField>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof PaginatedResponseIndicatorField
     */
    pagination?: PaginationInfo;
}

/**
 * Check if a given object implements the PaginatedResponseIndicatorField interface.
 */
export function instanceOfPaginatedResponseIndicatorField(value: object): value is PaginatedResponseIndicatorField {
    return true;
}

export function PaginatedResponseIndicatorFieldFromJSON(json: any): PaginatedResponseIndicatorField {
    return PaginatedResponseIndicatorFieldFromJSONTyped(json, false);
}

export function PaginatedResponseIndicatorFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseIndicatorField {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(IndicatorFieldFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationInfoFromJSON(json['pagination']),
    };
}

export function PaginatedResponseIndicatorFieldToJSON(json: any): PaginatedResponseIndicatorField {
    return PaginatedResponseIndicatorFieldToJSONTyped(json, false);
}

export function PaginatedResponseIndicatorFieldToJSONTyped(value?: PaginatedResponseIndicatorField | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(IndicatorFieldToJSON)),
        'pagination': PaginationInfoToJSON(value['pagination']),
    };
}

