/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BillingReason } from './BillingReason';
import {
    BillingReasonFromJSON,
    BillingReasonFromJSONTyped,
    BillingReasonToJSON,
    BillingReasonToJSONTyped,
} from './BillingReason';
import type { PaymentStatus } from './PaymentStatus';
import {
    PaymentStatusFromJSON,
    PaymentStatusFromJSONTyped,
    PaymentStatusToJSON,
    PaymentStatusToJSONTyped,
} from './PaymentStatus';

/**
 * 
 * @export
 * @interface PaymentWithDetails
 */
export interface PaymentWithDetails {
    /**
     * Payment details
     * @type {number}
     * @memberof PaymentWithDetails
     */
    amountPaid?: number;
    /**
     * Billing context
     * @type {BillingReason}
     * @memberof PaymentWithDetails
     */
    billingReason?: BillingReason;
    /**
     * Timestamps
     * @type {string}
     * @memberof PaymentWithDetails
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentWithDetails
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentWithDetails
     */
    id?: number;
    /**
     * Stripe identifiers
     * @type {string}
     * @memberof PaymentWithDetails
     */
    invoiceId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentWithDetails
     */
    invoiceNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentWithDetails
     */
    invoicePdf?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentWithDetails
     */
    invoiceUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentWithDetails
     */
    isFirstPayment?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentWithDetails
     */
    isRenewal?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PaymentWithDetails
     */
    last4Digits?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentWithDetails
     */
    paymentIntentId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentWithDetails
     */
    paymentMethodId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentWithDetails
     */
    paymentMethodType?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentWithDetails
     */
    planId?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentWithDetails
     */
    planName?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentWithDetails
     */
    planPricingId?: number;
    /**
     * Status tracking
     * @type {PaymentStatus}
     * @memberof PaymentWithDetails
     */
    status?: PaymentStatus;
    /**
     * 
     * @type {string}
     * @memberof PaymentWithDetails
     */
    subscriptionId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentWithDetails
     */
    updatedAt?: string;
    /**
     * Additional metadata
     * @type {string}
     * @memberof PaymentWithDetails
     */
    userEmail?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentWithDetails
     */
    userId?: number;
}



/**
 * Check if a given object implements the PaymentWithDetails interface.
 */
export function instanceOfPaymentWithDetails(value: object): value is PaymentWithDetails {
    return true;
}

export function PaymentWithDetailsFromJSON(json: any): PaymentWithDetails {
    return PaymentWithDetailsFromJSONTyped(json, false);
}

export function PaymentWithDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentWithDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'amountPaid': json['amount_paid'] == null ? undefined : json['amount_paid'],
        'billingReason': json['billing_reason'] == null ? undefined : BillingReasonFromJSON(json['billing_reason']),
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'id': json['id'] == null ? undefined : json['id'],
        'invoiceId': json['invoice_id'] == null ? undefined : json['invoice_id'],
        'invoiceNumber': json['invoice_number'] == null ? undefined : json['invoice_number'],
        'invoicePdf': json['invoice_pdf'] == null ? undefined : json['invoice_pdf'],
        'invoiceUrl': json['invoice_url'] == null ? undefined : json['invoice_url'],
        'isFirstPayment': json['is_first_payment'] == null ? undefined : json['is_first_payment'],
        'isRenewal': json['is_renewal'] == null ? undefined : json['is_renewal'],
        'last4Digits': json['last_4_digits'] == null ? undefined : json['last_4_digits'],
        'paymentIntentId': json['payment_intent_id'] == null ? undefined : json['payment_intent_id'],
        'paymentMethodId': json['payment_method_id'] == null ? undefined : json['payment_method_id'],
        'paymentMethodType': json['payment_method_type'] == null ? undefined : json['payment_method_type'],
        'planId': json['plan_id'] == null ? undefined : json['plan_id'],
        'planName': json['plan_name'] == null ? undefined : json['plan_name'],
        'planPricingId': json['plan_pricing_id'] == null ? undefined : json['plan_pricing_id'],
        'status': json['status'] == null ? undefined : PaymentStatusFromJSON(json['status']),
        'subscriptionId': json['subscription_id'] == null ? undefined : json['subscription_id'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'userEmail': json['user_email'] == null ? undefined : json['user_email'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function PaymentWithDetailsToJSON(json: any): PaymentWithDetails {
    return PaymentWithDetailsToJSONTyped(json, false);
}

export function PaymentWithDetailsToJSONTyped(value?: PaymentWithDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_paid': value['amountPaid'],
        'billing_reason': BillingReasonToJSON(value['billingReason']),
        'created_at': value['createdAt'],
        'currency': value['currency'],
        'id': value['id'],
        'invoice_id': value['invoiceId'],
        'invoice_number': value['invoiceNumber'],
        'invoice_pdf': value['invoicePdf'],
        'invoice_url': value['invoiceUrl'],
        'is_first_payment': value['isFirstPayment'],
        'is_renewal': value['isRenewal'],
        'last_4_digits': value['last4Digits'],
        'payment_intent_id': value['paymentIntentId'],
        'payment_method_id': value['paymentMethodId'],
        'payment_method_type': value['paymentMethodType'],
        'plan_id': value['planId'],
        'plan_name': value['planName'],
        'plan_pricing_id': value['planPricingId'],
        'status': PaymentStatusToJSON(value['status']),
        'subscription_id': value['subscriptionId'],
        'updated_at': value['updatedAt'],
        'user_email': value['userEmail'],
        'user_id': value['userId'],
    };
}

