/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanRestrictions
 */
export interface PlanRestrictions {
    /**
     * 
     * @type {boolean}
     * @memberof PlanRestrictions
     */
    canAccessPremium?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PlanRestrictions
     */
    cloneLimit?: number;
}

/**
 * Check if a given object implements the PlanRestrictions interface.
 */
export function instanceOfPlanRestrictions(value: object): value is PlanRestrictions {
    return true;
}

export function PlanRestrictionsFromJSON(json: any): PlanRestrictions {
    return PlanRestrictionsFromJSONTyped(json, false);
}

export function PlanRestrictionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanRestrictions {
    if (json == null) {
        return json;
    }
    return {
        
        'canAccessPremium': json['can_access_premium'] == null ? undefined : json['can_access_premium'],
        'cloneLimit': json['clone_limit'] == null ? undefined : json['clone_limit'],
    };
}

export function PlanRestrictionsToJSON(json: any): PlanRestrictions {
    return PlanRestrictionsToJSONTyped(json, false);
}

export function PlanRestrictionsToJSONTyped(value?: PlanRestrictions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'can_access_premium': value['canAccessPremium'],
        'clone_limit': value['cloneLimit'],
    };
}

