/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetDistribution } from './AssetDistribution';
import {
    AssetDistributionFromJSON,
    AssetDistributionFromJSONTyped,
    AssetDistributionToJSON,
    AssetDistributionToJSONTyped,
} from './AssetDistribution';

/**
 * 
 * @export
 * @interface PortfolioAnalysis
 */
export interface PortfolioAnalysis {
    /**
     * 
     * @type {string}
     * @memberof PortfolioAnalysis
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalysis
     */
    id?: number;
    /**
     * 
     * @type {Array<AssetDistribution>}
     * @memberof PortfolioAnalysis
     */
    list?: Array<AssetDistribution>;
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalysis
     */
    numberStock?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalysis
     */
    percentageProfitLossRecentMonth?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalysis
     */
    percentageProfitLossStartDay?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalysis
     */
    profitLossRecentMonth?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalysis
     */
    profitLossStartDay?: number;
    /**
     * 
     * @type {string}
     * @memberof PortfolioAnalysis
     */
    provider?: string;
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalysis
     */
    totalAssets?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalysis
     */
    totalPayable?: number;
}

/**
 * Check if a given object implements the PortfolioAnalysis interface.
 */
export function instanceOfPortfolioAnalysis(value: object): value is PortfolioAnalysis {
    return true;
}

export function PortfolioAnalysisFromJSON(json: any): PortfolioAnalysis {
    return PortfolioAnalysisFromJSONTyped(json, false);
}

export function PortfolioAnalysisFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioAnalysis {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'id': json['id'] == null ? undefined : json['id'],
        'list': json['list'] == null ? undefined : ((json['list'] as Array<any>).map(AssetDistributionFromJSON)),
        'numberStock': json['number_stock'] == null ? undefined : json['number_stock'],
        'percentageProfitLossRecentMonth': json['percentage_profit_loss_recent_month'] == null ? undefined : json['percentage_profit_loss_recent_month'],
        'percentageProfitLossStartDay': json['percentage_profit_loss_start_day'] == null ? undefined : json['percentage_profit_loss_start_day'],
        'profitLossRecentMonth': json['profit_loss_recent_month'] == null ? undefined : json['profit_loss_recent_month'],
        'profitLossStartDay': json['profit_loss_start_day'] == null ? undefined : json['profit_loss_start_day'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'totalAssets': json['total_assets'] == null ? undefined : json['total_assets'],
        'totalPayable': json['total_payable'] == null ? undefined : json['total_payable'],
    };
}

export function PortfolioAnalysisToJSON(json: any): PortfolioAnalysis {
    return PortfolioAnalysisToJSONTyped(json, false);
}

export function PortfolioAnalysisToJSONTyped(value?: PortfolioAnalysis | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'id': value['id'],
        'list': value['list'] == null ? undefined : ((value['list'] as Array<any>).map(AssetDistributionToJSON)),
        'number_stock': value['numberStock'],
        'percentage_profit_loss_recent_month': value['percentageProfitLossRecentMonth'],
        'percentage_profit_loss_start_day': value['percentageProfitLossStartDay'],
        'profit_loss_recent_month': value['profitLossRecentMonth'],
        'profit_loss_start_day': value['profitLossStartDay'],
        'provider': value['provider'],
        'total_assets': value['totalAssets'],
        'total_payable': value['totalPayable'],
    };
}

