/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PresignedUploadURLResponse
 */
export interface PresignedUploadURLResponse {
    /**
     * 
     * @type {string}
     * @memberof PresignedUploadURLResponse
     */
    bucket?: string;
    /**
     * 
     * @type {number}
     * @memberof PresignedUploadURLResponse
     */
    expiryTime?: number;
    /**
     * 
     * @type {string}
     * @memberof PresignedUploadURLResponse
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof PresignedUploadURLResponse
     */
    url?: string;
}

/**
 * Check if a given object implements the PresignedUploadURLResponse interface.
 */
export function instanceOfPresignedUploadURLResponse(value: object): value is PresignedUploadURLResponse {
    return true;
}

export function PresignedUploadURLResponseFromJSON(json: any): PresignedUploadURLResponse {
    return PresignedUploadURLResponseFromJSONTyped(json, false);
}

export function PresignedUploadURLResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresignedUploadURLResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bucket': json['bucket'] == null ? undefined : json['bucket'],
        'expiryTime': json['expiryTime'] == null ? undefined : json['expiryTime'],
        'key': json['key'] == null ? undefined : json['key'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function PresignedUploadURLResponseToJSON(json: any): PresignedUploadURLResponse {
    return PresignedUploadURLResponseToJSONTyped(json, false);
}

export function PresignedUploadURLResponseToJSONTyped(value?: PresignedUploadURLResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bucket': value['bucket'],
        'expiryTime': value['expiryTime'],
        'key': value['key'],
        'url': value['url'],
    };
}

