/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ResearchStrategyStatus {
    ResearchStrategyStatusDraft = 'DRAFT',
    ResearchStrategyStatusActive = 'ACTIVE',
    ResearchStrategyStatusPaused = 'PAUSED',
    ResearchStrategyStatusDeleted = 'DELETED'
}


export function instanceOfResearchStrategyStatus(value: any): boolean {
    for (const key in ResearchStrategyStatus) {
        if (Object.prototype.hasOwnProperty.call(ResearchStrategyStatus, key)) {
            if (ResearchStrategyStatus[key as keyof typeof ResearchStrategyStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ResearchStrategyStatusFromJSON(json: any): ResearchStrategyStatus {
    return ResearchStrategyStatusFromJSONTyped(json, false);
}

export function ResearchStrategyStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearchStrategyStatus {
    return json as ResearchStrategyStatus;
}

export function ResearchStrategyStatusToJSON(value?: ResearchStrategyStatus | null): any {
    return value as any;
}

export function ResearchStrategyStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ResearchStrategyStatus {
    return value as ResearchStrategyStatus;
}

