/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Strategy } from './Strategy';
import {
    StrategyFromJSON,
    StrategyFromJSONTyped,
    StrategyToJSON,
    StrategyToJSONTyped,
} from './Strategy';

/**
 * 
 * @export
 * @interface RollbackToVersionResponse
 */
export interface RollbackToVersionResponse {
    /**
     * 
     * @type {string}
     * @memberof RollbackToVersionResponse
     */
    message?: string;
    /**
     * 
     * @type {Strategy}
     * @memberof RollbackToVersionResponse
     */
    strategy?: Strategy;
}

/**
 * Check if a given object implements the RollbackToVersionResponse interface.
 */
export function instanceOfRollbackToVersionResponse(value: object): value is RollbackToVersionResponse {
    return true;
}

export function RollbackToVersionResponseFromJSON(json: any): RollbackToVersionResponse {
    return RollbackToVersionResponseFromJSONTyped(json, false);
}

export function RollbackToVersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RollbackToVersionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'strategy': json['strategy'] == null ? undefined : StrategyFromJSON(json['strategy']),
    };
}

export function RollbackToVersionResponseToJSON(json: any): RollbackToVersionResponse {
    return RollbackToVersionResponseToJSONTyped(json, false);
}

export function RollbackToVersionResponseToJSONTyped(value?: RollbackToVersionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'strategy': StrategyToJSON(value['strategy']),
    };
}

