/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum RunStatus {
    RunStatusPending = 'PENDING',
    RunStatusInit = 'INIT',
    RunStatusRunning = 'RUNNING',
    RunStatusStopped = 'STOPPED',
    RunStatusCompleted = 'COMPLETED',
    RunStatusFailed = 'FAILED',
    RunStatusCancelled = 'CANCELLED',
    RunStatusTimeout = 'TIMEOUT'
}


export function instanceOfRunStatus(value: any): boolean {
    for (const key in RunStatus) {
        if (Object.prototype.hasOwnProperty.call(RunStatus, key)) {
            if (RunStatus[key as keyof typeof RunStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RunStatusFromJSON(json: any): RunStatus {
    return RunStatusFromJSONTyped(json, false);
}

export function RunStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunStatus {
    return json as RunStatus;
}

export function RunStatusToJSON(value?: RunStatus | null): any {
    return value as any;
}

export function RunStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): RunStatus {
    return value as RunStatus;
}

