/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseResponseUserUser } from './BaseResponseUserUser';
import {
    BaseResponseUserUserFromJSON,
    BaseResponseUserUserFromJSONTyped,
    BaseResponseUserUserToJSON,
    BaseResponseUserUserToJSONTyped,
} from './BaseResponseUserUser';

/**
 * 
 * @export
 * @interface SignupResponse
 */
export interface SignupResponse {
    /**
     * 
     * @type {string}
     * @memberof SignupResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {number}
     * @memberof SignupResponse
     */
    expiresIn?: number;
    /**
     * 
     * @type {string}
     * @memberof SignupResponse
     */
    refreshToken?: string;
    /**
     * 
     * @type {string}
     * @memberof SignupResponse
     */
    tokenType?: string;
    /**
     * 
     * @type {BaseResponseUserUser}
     * @memberof SignupResponse
     */
    user?: BaseResponseUserUser;
}

/**
 * Check if a given object implements the SignupResponse interface.
 */
export function instanceOfSignupResponse(value: object): value is SignupResponse {
    return true;
}

export function SignupResponseFromJSON(json: any): SignupResponse {
    return SignupResponseFromJSONTyped(json, false);
}

export function SignupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'expiresIn': json['expiresIn'] == null ? undefined : json['expiresIn'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'tokenType': json['tokenType'] == null ? undefined : json['tokenType'],
        'user': json['user'] == null ? undefined : BaseResponseUserUserFromJSON(json['user']),
    };
}

export function SignupResponseToJSON(json: any): SignupResponse {
    return SignupResponseToJSONTyped(json, false);
}

export function SignupResponseToJSONTyped(value?: SignupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
        'expiresIn': value['expiresIn'],
        'refreshToken': value['refreshToken'],
        'tokenType': value['tokenType'],
        'user': BaseResponseUserUserToJSON(value['user']),
    };
}

