/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseResponseResearchPerformanceMetrics } from './BaseResponseResearchPerformanceMetrics';
import {
    BaseResponseResearchPerformanceMetricsFromJSON,
    BaseResponseResearchPerformanceMetricsFromJSONTyped,
    BaseResponseResearchPerformanceMetricsToJSON,
    BaseResponseResearchPerformanceMetricsToJSONTyped,
} from './BaseResponseResearchPerformanceMetrics';

/**
 * 
 * @export
 * @interface SubmitResearchResponse
 */
export interface SubmitResearchResponse {
    /**
     * 
     * @type {number}
     * @memberof SubmitResearchResponse
     */
    algoResultId?: number;
    /**
     * 
     * @type {string}
     * @memberof SubmitResearchResponse
     */
    backtestStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof SubmitResearchResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {BaseResponseResearchPerformanceMetrics}
     * @memberof SubmitResearchResponse
     */
    performanceMetrics?: BaseResponseResearchPerformanceMetrics;
    /**
     * 
     * @type {number}
     * @memberof SubmitResearchResponse
     */
    runtimeSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof SubmitResearchResponse
     */
    strategyId?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SubmitResearchResponse
     */
    validationDetails?: { [key: string]: any; };
}

/**
 * Check if a given object implements the SubmitResearchResponse interface.
 */
export function instanceOfSubmitResearchResponse(value: object): value is SubmitResearchResponse {
    return true;
}

export function SubmitResearchResponseFromJSON(json: any): SubmitResearchResponse {
    return SubmitResearchResponseFromJSONTyped(json, false);
}

export function SubmitResearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitResearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'algoResultId': json['algoResultId'] == null ? undefined : json['algoResultId'],
        'backtestStatus': json['backtestStatus'] == null ? undefined : json['backtestStatus'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'performanceMetrics': json['performanceMetrics'] == null ? undefined : BaseResponseResearchPerformanceMetricsFromJSON(json['performanceMetrics']),
        'runtimeSeconds': json['runtimeSeconds'] == null ? undefined : json['runtimeSeconds'],
        'strategyId': json['strategyId'] == null ? undefined : json['strategyId'],
        'validationDetails': json['validationDetails'] == null ? undefined : json['validationDetails'],
    };
}

export function SubmitResearchResponseToJSON(json: any): SubmitResearchResponse {
    return SubmitResearchResponseToJSONTyped(json, false);
}

export function SubmitResearchResponseToJSONTyped(value?: SubmitResearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'algoResultId': value['algoResultId'],
        'backtestStatus': value['backtestStatus'],
        'createdAt': value['createdAt'],
        'performanceMetrics': BaseResponseResearchPerformanceMetricsToJSON(value['performanceMetrics']),
        'runtimeSeconds': value['runtimeSeconds'],
        'strategyId': value['strategyId'],
        'validationDetails': value['validationDetails'],
    };
}

