/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestAlertRequest
 */
export interface TestAlertRequest {
    /**
     * 
     * @type {number}
     * @memberof TestAlertRequest
     */
    brokerageId: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TestAlertRequest
     */
    data: { [key: string]: any; };
}

/**
 * Check if a given object implements the TestAlertRequest interface.
 */
export function instanceOfTestAlertRequest(value: object): value is TestAlertRequest {
    if (!('brokerageId' in value) || value['brokerageId'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TestAlertRequestFromJSON(json: any): TestAlertRequest {
    return TestAlertRequestFromJSONTyped(json, false);
}

export function TestAlertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestAlertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'brokerageId': json['brokerageId'],
        'data': json['data'],
    };
}

export function TestAlertRequestToJSON(json: any): TestAlertRequest {
    return TestAlertRequestToJSONTyped(json, false);
}

export function TestAlertRequestToJSONTyped(value?: TestAlertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'brokerageId': value['brokerageId'],
        'data': value['data'],
    };
}

