/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestTelegramRequest
 */
export interface TestTelegramRequest {
    /**
     * 
     * @type {string}
     * @memberof TestTelegramRequest
     */
    telegramBotToken: string;
    /**
     * 
     * @type {string}
     * @memberof TestTelegramRequest
     */
    telegramChatId: string;
}

/**
 * Check if a given object implements the TestTelegramRequest interface.
 */
export function instanceOfTestTelegramRequest(value: object): value is TestTelegramRequest {
    if (!('telegramBotToken' in value) || value['telegramBotToken'] === undefined) return false;
    if (!('telegramChatId' in value) || value['telegramChatId'] === undefined) return false;
    return true;
}

export function TestTelegramRequestFromJSON(json: any): TestTelegramRequest {
    return TestTelegramRequestFromJSONTyped(json, false);
}

export function TestTelegramRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestTelegramRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'telegramBotToken': json['telegramBotToken'],
        'telegramChatId': json['telegramChatId'],
    };
}

export function TestTelegramRequestToJSON(json: any): TestTelegramRequest {
    return TestTelegramRequestToJSONTyped(json, false);
}

export function TestTelegramRequestToJSONTyped(value?: TestTelegramRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'telegramBotToken': value['telegramBotToken'],
        'telegramChatId': value['telegramChatId'],
    };
}

