/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TradingRunsSummary
 */
export interface TradingRunsSummary {
    /**
     * 
     * @type {number}
     * @memberof TradingRunsSummary
     */
    averagePnL?: number;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof TradingRunsSummary
     */
    botTypesOverview?: { [key: string]: number; };
    /**
     * 
     * @type {number}
     * @memberof TradingRunsSummary
     */
    completedRuns?: number;
    /**
     * 
     * @type {number}
     * @memberof TradingRunsSummary
     */
    failedRuns?: number;
    /**
     * 
     * @type {number}
     * @memberof TradingRunsSummary
     */
    totalRuns?: number;
}

/**
 * Check if a given object implements the TradingRunsSummary interface.
 */
export function instanceOfTradingRunsSummary(value: object): value is TradingRunsSummary {
    return true;
}

export function TradingRunsSummaryFromJSON(json: any): TradingRunsSummary {
    return TradingRunsSummaryFromJSONTyped(json, false);
}

export function TradingRunsSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradingRunsSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'averagePnL': json['averagePnL'] == null ? undefined : json['averagePnL'],
        'botTypesOverview': json['botTypesOverview'] == null ? undefined : json['botTypesOverview'],
        'completedRuns': json['completedRuns'] == null ? undefined : json['completedRuns'],
        'failedRuns': json['failedRuns'] == null ? undefined : json['failedRuns'],
        'totalRuns': json['totalRuns'] == null ? undefined : json['totalRuns'],
    };
}

export function TradingRunsSummaryToJSON(json: any): TradingRunsSummary {
    return TradingRunsSummaryToJSONTyped(json, false);
}

export function TradingRunsSummaryToJSONTyped(value?: TradingRunsSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'averagePnL': value['averagePnL'],
        'botTypesOverview': value['botTypesOverview'],
        'completedRuns': value['completedRuns'],
        'failedRuns': value['failedRuns'],
        'totalRuns': value['totalRuns'],
    };
}

