/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum UserPlanStatus {
    UserPlanStatusActive = 'ACTIVE',
    UserPlanStatusUpgraded = 'UPGRADED',
    UserPlanStatusExpired = 'EXPIRED'
}


export function instanceOfUserPlanStatus(value: any): boolean {
    for (const key in UserPlanStatus) {
        if (Object.prototype.hasOwnProperty.call(UserPlanStatus, key)) {
            if (UserPlanStatus[key as keyof typeof UserPlanStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserPlanStatusFromJSON(json: any): UserPlanStatus {
    return UserPlanStatusFromJSONTyped(json, false);
}

export function UserPlanStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPlanStatus {
    return json as UserPlanStatus;
}

export function UserPlanStatusToJSON(value?: UserPlanStatus | null): any {
    return value as any;
}

export function UserPlanStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): UserPlanStatus {
    return value as UserPlanStatus;
}

