/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookEventType } from './WebhookEventType';
import {
    WebhookEventTypeFromJSON,
    WebhookEventTypeFromJSONTyped,
    WebhookEventTypeToJSON,
    WebhookEventTypeToJSONTyped,
} from './WebhookEventType';

/**
 * 
 * @export
 * @interface WebhookEvent
 */
export interface WebhookEvent {
    /**
     * 
     * @type {string}
     * @memberof WebhookEvent
     */
    podName: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEvent
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof WebhookEvent
     */
    timestamp: number;
    /**
     * 
     * @type {WebhookEventType}
     * @memberof WebhookEvent
     */
    type: WebhookEventType;
    /**
     * 
     * @type {number}
     * @memberof WebhookEvent
     */
    workloadId: number;
}



/**
 * Check if a given object implements the WebhookEvent interface.
 */
export function instanceOfWebhookEvent(value: object): value is WebhookEvent {
    if (!('podName' in value) || value['podName'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('workloadId' in value) || value['workloadId'] === undefined) return false;
    return true;
}

export function WebhookEventFromJSON(json: any): WebhookEvent {
    return WebhookEventFromJSONTyped(json, false);
}

export function WebhookEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'podName': json['podName'],
        'status': json['status'] == null ? undefined : json['status'],
        'timestamp': json['timestamp'],
        'type': WebhookEventTypeFromJSON(json['type']),
        'workloadId': json['workloadId'],
    };
}

export function WebhookEventToJSON(json: any): WebhookEvent {
    return WebhookEventToJSONTyped(json, false);
}

export function WebhookEventToJSONTyped(value?: WebhookEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'podName': value['podName'],
        'status': value['status'],
        'timestamp': value['timestamp'],
        'type': WebhookEventTypeToJSON(value['type']),
        'workloadId': value['workloadId'],
    };
}

