/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum WorkloadType {
    WorkloadTypeLiveTrading = 'LIVE_TRADING',
    WorkloadTypeBacktest = 'BACKTEST',
    WorkloadTypeAdvanceOrder = 'ADVANCE_ORDER',
    WorkloadTypeLoadData = 'LOAD_DATA',
    WorkloadTypeAlert = 'ALERT',
    WorkloadTypeBotAdvancedOrder = 'BOT_ADVANCED_ORDER',
    WorkloadTypeCMD = 'CMD'
}


export function instanceOfWorkloadType(value: any): boolean {
    for (const key in WorkloadType) {
        if (Object.prototype.hasOwnProperty.call(WorkloadType, key)) {
            if (WorkloadType[key as keyof typeof WorkloadType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WorkloadTypeFromJSON(json: any): WorkloadType {
    return WorkloadTypeFromJSONTyped(json, false);
}

export function WorkloadTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkloadType {
    return json as WorkloadType;
}

export function WorkloadTypeToJSON(value?: WorkloadType | null): any {
    return value as any;
}

export function WorkloadTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): WorkloadType {
    return value as WorkloadType;
}

