/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkloadStatus } from './WorkloadStatus';
import {
    WorkloadStatusFromJSON,
    WorkloadStatusFromJSONTyped,
    WorkloadStatusToJSON,
    WorkloadStatusToJSONTyped,
} from './WorkloadStatus';
import type { WorkloadType } from './WorkloadType';
import {
    WorkloadTypeFromJSON,
    WorkloadTypeFromJSONTyped,
    WorkloadTypeToJSON,
    WorkloadTypeToJSONTyped,
} from './WorkloadType';

/**
 * 
 * @export
 * @interface Workload
 */
export interface Workload {
    /**
     * 
     * @type {string}
     * @memberof Workload
     */
    createdAt?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Workload
     */
    data?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof Workload
     */
    id?: number;
    /**
     * 
     * @type {WorkloadStatus}
     * @memberof Workload
     */
    status?: WorkloadStatus;
    /**
     * 
     * @type {WorkloadType}
     * @memberof Workload
     */
    type?: WorkloadType;
    /**
     * 
     * @type {string}
     * @memberof Workload
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof Workload
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof Workload
     */
    workloadId?: number;
}



/**
 * Check if a given object implements the Workload interface.
 */
export function instanceOfWorkload(value: object): value is Workload {
    return true;
}

export function WorkloadFromJSON(json: any): Workload {
    return WorkloadFromJSONTyped(json, false);
}

export function WorkloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): Workload {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'data': json['data'] == null ? undefined : json['data'],
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : WorkloadStatusFromJSON(json['status']),
        'type': json['type'] == null ? undefined : WorkloadTypeFromJSON(json['type']),
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'workloadId': json['workload_id'] == null ? undefined : json['workload_id'],
    };
}

export function WorkloadToJSON(json: any): Workload {
    return WorkloadToJSONTyped(json, false);
}

export function WorkloadToJSONTyped(value?: Workload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'data': value['data'],
        'id': value['id'],
        'status': WorkloadStatusToJSON(value['status']),
        'type': WorkloadTypeToJSON(value['type']),
        'updated_at': value['updatedAt'],
        'user_id': value['userId'],
        'workload_id': value['workloadId'],
    };
}

