/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BaseResponseAny,
  BaseResponseArrayAPIKey,
  BaseResponseCreateAPIKeyResponse,
  CreateAPIKeyRequest,
} from '../models/index';
import {
    BaseResponseAnyFromJSON,
    BaseResponseAnyToJSON,
    BaseResponseArrayAPIKeyFromJSON,
    BaseResponseArrayAPIKeyToJSON,
    BaseResponseCreateAPIKeyResponseFromJSON,
    BaseResponseCreateAPIKeyResponseToJSON,
    CreateAPIKeyRequestFromJSON,
    CreateAPIKeyRequestToJSON,
} from '../models/index';

export interface AdminApiKeysIdDeactivatePostRequest {
    id: number;
}

export interface AdminApiKeysPostRequest {
    request: CreateAPIKeyRequest;
}

/**
 * 
 */
export class APIKeyApi extends runtime.BaseAPI {

    /**
     * Creates request options for adminApiKeysGet without sending the request
     */
    async adminApiKeysGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/admin/api-keys`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a list of all API keys (for admin purposes). Plaintext keys are never returned.
     * List all API keys
     */
    async adminApiKeysGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseArrayAPIKey>> {
        const requestOptions = await this.adminApiKeysGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseArrayAPIKeyFromJSON(jsonValue));
    }

    /**
     * Get a list of all API keys (for admin purposes). Plaintext keys are never returned.
     * List all API keys
     */
    async adminApiKeysGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseArrayAPIKey> {
        const response = await this.adminApiKeysGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminApiKeysIdDeactivatePost without sending the request
     */
    async adminApiKeysIdDeactivatePostRequestOpts(requestParameters: AdminApiKeysIdDeactivatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling adminApiKeysIdDeactivatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/admin/api-keys/{id}/deactivate`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deactivate an API key by ID. The key will no longer be usable for authentication.
     * Deactivate an API key
     */
    async adminApiKeysIdDeactivatePostRaw(requestParameters: AdminApiKeysIdDeactivatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseAny>> {
        const requestOptions = await this.adminApiKeysIdDeactivatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseAnyFromJSON(jsonValue));
    }

    /**
     * Deactivate an API key by ID. The key will no longer be usable for authentication.
     * Deactivate an API key
     */
    async adminApiKeysIdDeactivatePost(requestParameters: AdminApiKeysIdDeactivatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseAny> {
        const response = await this.adminApiKeysIdDeactivatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminApiKeysPost without sending the request
     */
    async adminApiKeysPostRequestOpts(requestParameters: AdminApiKeysPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling adminApiKeysPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/admin/api-keys`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAPIKeyRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create a new API key for internal service authentication. The plaintext key is only returned once during creation. The `created_by` field is automatically set from the authenticated user.
     * Create a new API key
     */
    async adminApiKeysPostRaw(requestParameters: AdminApiKeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseCreateAPIKeyResponse>> {
        const requestOptions = await this.adminApiKeysPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseCreateAPIKeyResponseFromJSON(jsonValue));
    }

    /**
     * Create a new API key for internal service authentication. The plaintext key is only returned once during creation. The `created_by` field is automatically set from the authenticated user.
     * Create a new API key
     */
    async adminApiKeysPost(requestParameters: AdminApiKeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseCreateAPIKeyResponse> {
        const response = await this.adminApiKeysPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
