/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthRefreshPostRequest,
  BaseResponseAny,
  BaseResponseLoginResponse,
  BaseResponseSignupResponse,
  GoogleLoginRequest,
  LoginRequest,
  RequestPasswordResetRequest,
  ResetPasswordRequest,
  SignupRequest,
} from '../models/index';
import {
    AuthRefreshPostRequestFromJSON,
    AuthRefreshPostRequestToJSON,
    BaseResponseAnyFromJSON,
    BaseResponseAnyToJSON,
    BaseResponseLoginResponseFromJSON,
    BaseResponseLoginResponseToJSON,
    BaseResponseSignupResponseFromJSON,
    BaseResponseSignupResponseToJSON,
    GoogleLoginRequestFromJSON,
    GoogleLoginRequestToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    RequestPasswordResetRequestFromJSON,
    RequestPasswordResetRequestToJSON,
    ResetPasswordRequestFromJSON,
    ResetPasswordRequestToJSON,
    SignupRequestFromJSON,
    SignupRequestToJSON,
} from '../models/index';

export interface AuthGooglePostRequest {
    request: GoogleLoginRequest;
}

export interface AuthLoginPostRequest {
    request: LoginRequest;
}

export interface AuthRefreshPostOperationRequest {
    request: AuthRefreshPostRequest;
}

export interface AuthRequestPasswordResetPostRequest {
    request: RequestPasswordResetRequest;
}

export interface AuthResetPasswordPostRequest {
    request: ResetPasswordRequest;
}

export interface AuthSignupPostRequest {
    request: SignupRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Creates request options for authGooglePost without sending the request
     */
    async authGooglePostRequestOpts(requestParameters: AuthGooglePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling authGooglePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/google`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GoogleLoginRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Authenticate user with Google OAuth authorization code via Auth0
     * Google OAuth Login
     */
    async authGooglePostRaw(requestParameters: AuthGooglePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseLoginResponse>> {
        const requestOptions = await this.authGooglePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseLoginResponseFromJSON(jsonValue));
    }

    /**
     * Authenticate user with Google OAuth authorization code via Auth0
     * Google OAuth Login
     */
    async authGooglePost(requestParameters: AuthGooglePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseLoginResponse> {
        const response = await this.authGooglePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authLoginPost without sending the request
     */
    async authLoginPostRequestOpts(requestParameters: AuthLoginPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling authLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Authenticate user with email and password using Auth0
     * User Login
     */
    async authLoginPostRaw(requestParameters: AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseLoginResponse>> {
        const requestOptions = await this.authLoginPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseLoginResponseFromJSON(jsonValue));
    }

    /**
     * Authenticate user with email and password using Auth0
     * User Login
     */
    async authLoginPost(requestParameters: AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseLoginResponse> {
        const response = await this.authLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authRefreshPost without sending the request
     */
    async authRefreshPostRequestOpts(requestParameters: AuthRefreshPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling authRefreshPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/refresh`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthRefreshPostRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Refresh expired JWT token using refresh token
     * Refresh Token
     */
    async authRefreshPostRaw(requestParameters: AuthRefreshPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseLoginResponse>> {
        const requestOptions = await this.authRefreshPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseLoginResponseFromJSON(jsonValue));
    }

    /**
     * Refresh expired JWT token using refresh token
     * Refresh Token
     */
    async authRefreshPost(requestParameters: AuthRefreshPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseLoginResponse> {
        const response = await this.authRefreshPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authRequestPasswordResetPost without sending the request
     */
    async authRequestPasswordResetPostRequestOpts(requestParameters: AuthRequestPasswordResetPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling authRequestPasswordResetPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/request-password-reset`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestPasswordResetRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Request a password reset email (public endpoint)
     * Request Password Reset
     */
    async authRequestPasswordResetPostRaw(requestParameters: AuthRequestPasswordResetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseAny>> {
        const requestOptions = await this.authRequestPasswordResetPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseAnyFromJSON(jsonValue));
    }

    /**
     * Request a password reset email (public endpoint)
     * Request Password Reset
     */
    async authRequestPasswordResetPost(requestParameters: AuthRequestPasswordResetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseAny> {
        const response = await this.authRequestPasswordResetPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authResetPasswordPost without sending the request
     */
    async authResetPasswordPostRequestOpts(requestParameters: AuthResetPasswordPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling authResetPasswordPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/reset-password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResetPasswordRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Complete password reset with token from email (public endpoint)
     * Reset Password
     */
    async authResetPasswordPostRaw(requestParameters: AuthResetPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseAny>> {
        const requestOptions = await this.authResetPasswordPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseAnyFromJSON(jsonValue));
    }

    /**
     * Complete password reset with token from email (public endpoint)
     * Reset Password
     */
    async authResetPasswordPost(requestParameters: AuthResetPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseAny> {
        const response = await this.authResetPasswordPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authSignupPost without sending the request
     */
    async authSignupPostRequestOpts(requestParameters: AuthSignupPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling authSignupPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/signup`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignupRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Register a new user account using Auth0
     * User Signup
     */
    async authSignupPostRaw(requestParameters: AuthSignupPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseSignupResponse>> {
        const requestOptions = await this.authSignupPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseSignupResponseFromJSON(jsonValue));
    }

    /**
     * Register a new user account using Auth0
     * User Signup
     */
    async authSignupPost(requestParameters: AuthSignupPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseSignupResponse> {
        const response = await this.authSignupPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
