/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BaseResponseAny,
  BaseResponseArrayBotAdvancedOrder,
  BaseResponseBotAdvancedOrder,
  BotAdvancedOrder,
} from '../models/index';
import {
    BaseResponseAnyFromJSON,
    BaseResponseAnyToJSON,
    BaseResponseArrayBotAdvancedOrderFromJSON,
    BaseResponseArrayBotAdvancedOrderToJSON,
    BaseResponseBotAdvancedOrderFromJSON,
    BaseResponseBotAdvancedOrderToJSON,
    BotAdvancedOrderFromJSON,
    BotAdvancedOrderToJSON,
} from '../models/index';

export interface BotAdvancedOrdersIdGetRequest {
    id: number;
}

export interface BotAdvancedOrdersPostRequest {
    request: BotAdvancedOrder;
}

/**
 * 
 */
export class BotAdvancedOrdersApi extends runtime.BaseAPI {

    /**
     * Creates request options for botAdvancedOrdersGet without sending the request
     */
    async botAdvancedOrdersGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/bot-advanced-orders`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all bot advanced orders for authenticated user
     * List Bot Advanced Orders
     */
    async botAdvancedOrdersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseArrayBotAdvancedOrder>> {
        const requestOptions = await this.botAdvancedOrdersGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseArrayBotAdvancedOrderFromJSON(jsonValue));
    }

    /**
     * Get all bot advanced orders for authenticated user
     * List Bot Advanced Orders
     */
    async botAdvancedOrdersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseArrayBotAdvancedOrder> {
        const response = await this.botAdvancedOrdersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for botAdvancedOrdersIdGet without sending the request
     */
    async botAdvancedOrdersIdGetRequestOpts(requestParameters: BotAdvancedOrdersIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling botAdvancedOrdersIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/bot-advanced-orders/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get bot advanced order details by ID
     * Get Bot Advanced Order by ID
     */
    async botAdvancedOrdersIdGetRaw(requestParameters: BotAdvancedOrdersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseBotAdvancedOrder>> {
        const requestOptions = await this.botAdvancedOrdersIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseBotAdvancedOrderFromJSON(jsonValue));
    }

    /**
     * Get bot advanced order details by ID
     * Get Bot Advanced Order by ID
     */
    async botAdvancedOrdersIdGet(requestParameters: BotAdvancedOrdersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseBotAdvancedOrder> {
        const response = await this.botAdvancedOrdersIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for botAdvancedOrdersPost without sending the request
     */
    async botAdvancedOrdersPostRequestOpts(requestParameters: BotAdvancedOrdersPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling botAdvancedOrdersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/bot-advanced-orders`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BotAdvancedOrderToJSON(requestParameters['request']),
        };
    }

    /**
     * Create a new bot advanced order configuration
     * Create Bot Advanced Order
     */
    async botAdvancedOrdersPostRaw(requestParameters: BotAdvancedOrdersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseBotAdvancedOrder>> {
        const requestOptions = await this.botAdvancedOrdersPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseBotAdvancedOrderFromJSON(jsonValue));
    }

    /**
     * Create a new bot advanced order configuration
     * Create Bot Advanced Order
     */
    async botAdvancedOrdersPost(requestParameters: BotAdvancedOrdersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseBotAdvancedOrder> {
        const response = await this.botAdvancedOrdersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
