/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BaseResponseAny,
  BaseResponseArrayBotType,
  BaseResponseBot,
  BaseResponseBotJSONSchemaResponse1,
  BaseResponseBotRunResponse,
  BaseResponseGetBotStatusResponse,
  BaseResponseTestTelegramResponse,
  BotBacktestRequest,
  BotLiveTradingRequest,
  BotPaperTradingRequest,
  CreateBotRequest,
  PaginatedResponseBot,
  TestTelegramRequest,
  UpdateBotRequest,
} from '../models/index';
import {
    BaseResponseAnyFromJSON,
    BaseResponseAnyToJSON,
    BaseResponseArrayBotTypeFromJSON,
    BaseResponseArrayBotTypeToJSON,
    BaseResponseBotFromJSON,
    BaseResponseBotToJSON,
    BaseResponseBotJSONSchemaResponse1FromJSON,
    BaseResponseBotJSONSchemaResponse1ToJSON,
    BaseResponseBotRunResponseFromJSON,
    BaseResponseBotRunResponseToJSON,
    BaseResponseGetBotStatusResponseFromJSON,
    BaseResponseGetBotStatusResponseToJSON,
    BaseResponseTestTelegramResponseFromJSON,
    BaseResponseTestTelegramResponseToJSON,
    BotBacktestRequestFromJSON,
    BotBacktestRequestToJSON,
    BotLiveTradingRequestFromJSON,
    BotLiveTradingRequestToJSON,
    BotPaperTradingRequestFromJSON,
    BotPaperTradingRequestToJSON,
    CreateBotRequestFromJSON,
    CreateBotRequestToJSON,
    PaginatedResponseBotFromJSON,
    PaginatedResponseBotToJSON,
    TestTelegramRequestFromJSON,
    TestTelegramRequestToJSON,
    UpdateBotRequestFromJSON,
    UpdateBotRequestToJSON,
} from '../models/index';

export interface BotsGetRequest {
    page?: number;
    pageSize?: number;
    status?: BotsGetStatusEnum;
    botTypeId?: number;
}

export interface BotsIdBacktestPostRequest {
    id: number;
    request: BotBacktestRequest;
}

export interface BotsIdDeleteRequest {
    id: number;
}

export interface BotsIdGetRequest {
    id: number;
}

export interface BotsIdLivePostRequest {
    id: number;
    request: BotLiveTradingRequest;
}

export interface BotsIdPaperPostRequest {
    id: number;
    request: BotPaperTradingRequest;
}

export interface BotsIdPutRequest {
    id: number;
    request: UpdateBotRequest;
}

export interface BotsIdStatusGetRequest {
    id: number;
}

export interface BotsPostRequest {
    request: CreateBotRequest;
}

export interface BotsTestTelegramPostRequest {
    request: TestTelegramRequest;
}

export interface BotsTypesIdConfigFieldsGetRequest {
    id: number;
    lang?: BotsTypesIdConfigFieldsGetLangEnum;
}

/**
 * 
 */
export class BotsApi extends runtime.BaseAPI {

    /**
     * Creates request options for botsGet without sending the request
     */
    async botsGetRequestOpts(requestParameters: BotsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['botTypeId'] != null) {
            queryParameters['bot_type_id'] = requestParameters['botTypeId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/bots`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a paginated list of bots for the authenticated user
     * List bots
     */
    async botsGetRaw(requestParameters: BotsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponseBot>> {
        const requestOptions = await this.botsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedResponseBotFromJSON(jsonValue));
    }

    /**
     * Get a paginated list of bots for the authenticated user
     * List bots
     */
    async botsGet(requestParameters: BotsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponseBot> {
        const response = await this.botsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for botsIdBacktestPost without sending the request
     */
    async botsIdBacktestPostRequestOpts(requestParameters: BotsIdBacktestPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling botsIdBacktestPost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling botsIdBacktestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/bots/{id}/backtest`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BotBacktestRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Start a bot backtest with the specified configuration
     * Start bot backtest
     */
    async botsIdBacktestPostRaw(requestParameters: BotsIdBacktestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseBotRunResponse>> {
        const requestOptions = await this.botsIdBacktestPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseBotRunResponseFromJSON(jsonValue));
    }

    /**
     * Start a bot backtest with the specified configuration
     * Start bot backtest
     */
    async botsIdBacktestPost(requestParameters: BotsIdBacktestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseBotRunResponse> {
        const response = await this.botsIdBacktestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for botsIdDelete without sending the request
     */
    async botsIdDeleteRequestOpts(requestParameters: BotsIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling botsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/bots/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a bot
     * Delete bot
     */
    async botsIdDeleteRaw(requestParameters: BotsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.botsIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a bot
     * Delete bot
     */
    async botsIdDelete(requestParameters: BotsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.botsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for botsIdGet without sending the request
     */
    async botsIdGetRequestOpts(requestParameters: BotsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling botsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/bots/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get detailed information about a specific bot
     * Get bot details
     */
    async botsIdGetRaw(requestParameters: BotsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseBot>> {
        const requestOptions = await this.botsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseBotFromJSON(jsonValue));
    }

    /**
     * Get detailed information about a specific bot
     * Get bot details
     */
    async botsIdGet(requestParameters: BotsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseBot> {
        const response = await this.botsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for botsIdLivePost without sending the request
     */
    async botsIdLivePostRequestOpts(requestParameters: BotsIdLivePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling botsIdLivePost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling botsIdLivePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/bots/{id}/live`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BotLiveTradingRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Start a bot live trading run with the specified configuration
     * Start bot live trading
     */
    async botsIdLivePostRaw(requestParameters: BotsIdLivePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseBotRunResponse>> {
        const requestOptions = await this.botsIdLivePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseBotRunResponseFromJSON(jsonValue));
    }

    /**
     * Start a bot live trading run with the specified configuration
     * Start bot live trading
     */
    async botsIdLivePost(requestParameters: BotsIdLivePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseBotRunResponse> {
        const response = await this.botsIdLivePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for botsIdPaperPost without sending the request
     */
    async botsIdPaperPostRequestOpts(requestParameters: BotsIdPaperPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling botsIdPaperPost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling botsIdPaperPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/bots/{id}/paper`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BotPaperTradingRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Start a bot paper trading run with the specified configuration
     * Start bot paper trading
     */
    async botsIdPaperPostRaw(requestParameters: BotsIdPaperPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseBotRunResponse>> {
        const requestOptions = await this.botsIdPaperPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseBotRunResponseFromJSON(jsonValue));
    }

    /**
     * Start a bot paper trading run with the specified configuration
     * Start bot paper trading
     */
    async botsIdPaperPost(requestParameters: BotsIdPaperPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseBotRunResponse> {
        const response = await this.botsIdPaperPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for botsIdPut without sending the request
     */
    async botsIdPutRequestOpts(requestParameters: BotsIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling botsIdPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling botsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/bots/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateBotRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Update bot configuration
     * Update bot
     */
    async botsIdPutRaw(requestParameters: BotsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseBot>> {
        const requestOptions = await this.botsIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseBotFromJSON(jsonValue));
    }

    /**
     * Update bot configuration
     * Update bot
     */
    async botsIdPut(requestParameters: BotsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseBot> {
        const response = await this.botsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for botsIdStatusGet without sending the request
     */
    async botsIdStatusGetRequestOpts(requestParameters: BotsIdStatusGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling botsIdStatusGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/bots/{id}/status`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the current runtime status of a bot
     * Get bot status
     */
    async botsIdStatusGetRaw(requestParameters: BotsIdStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseGetBotStatusResponse>> {
        const requestOptions = await this.botsIdStatusGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseGetBotStatusResponseFromJSON(jsonValue));
    }

    /**
     * Get the current runtime status of a bot
     * Get bot status
     */
    async botsIdStatusGet(requestParameters: BotsIdStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseGetBotStatusResponse> {
        const response = await this.botsIdStatusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for botsPost without sending the request
     */
    async botsPostRequestOpts(requestParameters: BotsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling botsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/bots`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBotRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create a new bot with the provided configuration
     * Create a new bot
     */
    async botsPostRaw(requestParameters: BotsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseBot>> {
        const requestOptions = await this.botsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseBotFromJSON(jsonValue));
    }

    /**
     * Create a new bot with the provided configuration
     * Create a new bot
     */
    async botsPost(requestParameters: BotsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseBot> {
        const response = await this.botsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for botsTestTelegramPost without sending the request
     */
    async botsTestTelegramPostRequestOpts(requestParameters: BotsTestTelegramPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling botsTestTelegramPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/bots/test-telegram`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TestTelegramRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Test connection to Telegram Bot API with provided credentials
     * Test Telegram connection
     */
    async botsTestTelegramPostRaw(requestParameters: BotsTestTelegramPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseTestTelegramResponse>> {
        const requestOptions = await this.botsTestTelegramPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseTestTelegramResponseFromJSON(jsonValue));
    }

    /**
     * Test connection to Telegram Bot API with provided credentials
     * Test Telegram connection
     */
    async botsTestTelegramPost(requestParameters: BotsTestTelegramPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseTestTelegramResponse> {
        const response = await this.botsTestTelegramPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for botsTypesGet without sending the request
     */
    async botsTypesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bots/types`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all active bot types
     * Get all bot types
     */
    async botsTypesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseArrayBotType>> {
        const requestOptions = await this.botsTypesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseArrayBotTypeFromJSON(jsonValue));
    }

    /**
     * Get all active bot types
     * Get all bot types
     */
    async botsTypesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseArrayBotType> {
        const response = await this.botsTypesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for botsTypesIdConfigFieldsGet without sending the request
     */
    async botsTypesIdConfigFieldsGetRequestOpts(requestParameters: BotsTypesIdConfigFieldsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling botsTypesIdConfigFieldsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['lang'] != null) {
            headerParameters['lang'] = String(requestParameters['lang']);
        }


        let urlPath = `/bots/types/{id}/config-fields`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get configuration fields for a bot type in JSON Schema format
     * Get bot configuration fields
     */
    async botsTypesIdConfigFieldsGetRaw(requestParameters: BotsTypesIdConfigFieldsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseBotJSONSchemaResponse1>> {
        const requestOptions = await this.botsTypesIdConfigFieldsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseBotJSONSchemaResponse1FromJSON(jsonValue));
    }

    /**
     * Get configuration fields for a bot type in JSON Schema format
     * Get bot configuration fields
     */
    async botsTypesIdConfigFieldsGet(requestParameters: BotsTypesIdConfigFieldsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseBotJSONSchemaResponse1> {
        const response = await this.botsTypesIdConfigFieldsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum BotsGetStatusEnum {
    Active = 'ACTIVE',
    Inactive = 'INACTIVE',
    Error = 'ERROR',
    Pending = 'PENDING'
}
/**
  * @export
  * @enum {string}
  */
export enum BotsTypesIdConfigFieldsGetLangEnum {
    En = 'en',
    Vi = 'vi'
}
