/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BaseResponseAny,
  BaseResponseArrayAssetsSummaryPoint,
  BaseResponseArrayPortfolioAnalysis,
  BaseResponseArrayPortfolioSummaryItem,
  BaseResponseSyncPortfolioResponse,
  BaseResponseTotalAssets,
} from '../models/index';
import {
    BaseResponseAnyFromJSON,
    BaseResponseAnyToJSON,
    BaseResponseArrayAssetsSummaryPointFromJSON,
    BaseResponseArrayAssetsSummaryPointToJSON,
    BaseResponseArrayPortfolioAnalysisFromJSON,
    BaseResponseArrayPortfolioAnalysisToJSON,
    BaseResponseArrayPortfolioSummaryItemFromJSON,
    BaseResponseArrayPortfolioSummaryItemToJSON,
    BaseResponseSyncPortfolioResponseFromJSON,
    BaseResponseSyncPortfolioResponseToJSON,
    BaseResponseTotalAssetsFromJSON,
    BaseResponseTotalAssetsToJSON,
} from '../models/index';

export interface PortfoliosAssetsSummaryGetRequest {
    currency: PortfoliosAssetsSummaryGetCurrencyEnum;
    period: number;
    provider?: string;
    tradingClientId?: number;
}

export interface PortfoliosSummaryGetRequest {
    currency: PortfoliosSummaryGetCurrencyEnum;
    provider?: string;
    tradingClientId?: number;
}

export interface PortfoliosTotalAssetsGetRequest {
    currency: PortfoliosTotalAssetsGetCurrencyEnum;
}

/**
 * 
 */
export class PortfolioApi extends runtime.BaseAPI {

    /**
     * Creates request options for portfoliosAnalysisGet without sending the request
     */
    async portfoliosAnalysisGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/portfolios/analysis`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get detailed portfolio analysis including asset distribution and profit/loss metrics. Analysis is grouped by brokerage account.
     * Get portfolio analysis
     */
    async portfoliosAnalysisGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseArrayPortfolioAnalysis>> {
        const requestOptions = await this.portfoliosAnalysisGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseArrayPortfolioAnalysisFromJSON(jsonValue));
    }

    /**
     * Get detailed portfolio analysis including asset distribution and profit/loss metrics. Analysis is grouped by brokerage account.
     * Get portfolio analysis
     */
    async portfoliosAnalysisGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseArrayPortfolioAnalysis> {
        const response = await this.portfoliosAnalysisGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for portfoliosAssetsSummaryGet without sending the request
     */
    async portfoliosAssetsSummaryGetRequestOpts(requestParameters: PortfoliosAssetsSummaryGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling portfoliosAssetsSummaryGet().'
            );
        }

        if (requestParameters['period'] == null) {
            throw new runtime.RequiredError(
                'period',
                'Required parameter "period" was null or undefined when calling portfoliosAssetsSummaryGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['period'] != null) {
            queryParameters['period'] = requestParameters['period'];
        }

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        if (requestParameters['tradingClientId'] != null) {
            queryParameters['tradingClientId'] = requestParameters['tradingClientId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/portfolios/assets-summary`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get time series of total assets over a period. Returns array of daily totals for the requested period.
     * Get assets summary
     */
    async portfoliosAssetsSummaryGetRaw(requestParameters: PortfoliosAssetsSummaryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseArrayAssetsSummaryPoint>> {
        const requestOptions = await this.portfoliosAssetsSummaryGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseArrayAssetsSummaryPointFromJSON(jsonValue));
    }

    /**
     * Get time series of total assets over a period. Returns array of daily totals for the requested period.
     * Get assets summary
     */
    async portfoliosAssetsSummaryGet(requestParameters: PortfoliosAssetsSummaryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseArrayAssetsSummaryPoint> {
        const response = await this.portfoliosAssetsSummaryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for portfoliosSummaryGet without sending the request
     */
    async portfoliosSummaryGetRequestOpts(requestParameters: PortfoliosSummaryGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling portfoliosSummaryGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        if (requestParameters['tradingClientId'] != null) {
            queryParameters['tradingClientId'] = requestParameters['tradingClientId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/portfolios/summary`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get summary of all holdings across portfolio sorted by value. All values are converted to the requested currency.
     * Get portfolio summary
     */
    async portfoliosSummaryGetRaw(requestParameters: PortfoliosSummaryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseArrayPortfolioSummaryItem>> {
        const requestOptions = await this.portfoliosSummaryGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseArrayPortfolioSummaryItemFromJSON(jsonValue));
    }

    /**
     * Get summary of all holdings across portfolio sorted by value. All values are converted to the requested currency.
     * Get portfolio summary
     */
    async portfoliosSummaryGet(requestParameters: PortfoliosSummaryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseArrayPortfolioSummaryItem> {
        const response = await this.portfoliosSummaryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for portfoliosSyncPost without sending the request
     */
    async portfoliosSyncPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/portfolios/sync`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Manually sync portfolio data from all connected brokerage accounts. Creates a new portfolio history with type MANUAL. Rate limited to prevent too frequent syncs.
     * Sync portfolio manually
     */
    async portfoliosSyncPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseSyncPortfolioResponse>> {
        const requestOptions = await this.portfoliosSyncPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseSyncPortfolioResponseFromJSON(jsonValue));
    }

    /**
     * Manually sync portfolio data from all connected brokerage accounts. Creates a new portfolio history with type MANUAL. Rate limited to prevent too frequent syncs.
     * Sync portfolio manually
     */
    async portfoliosSyncPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseSyncPortfolioResponse> {
        const response = await this.portfoliosSyncPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for portfoliosTotalAssetsGet without sending the request
     */
    async portfoliosTotalAssetsGetRequestOpts(requestParameters: PortfoliosTotalAssetsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling portfoliosTotalAssetsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/portfolios/total-assets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get total assets across all brokerage accounts, grouped by brokerage. All values are converted to the requested currency.
     * Get total assets
     */
    async portfoliosTotalAssetsGetRaw(requestParameters: PortfoliosTotalAssetsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseTotalAssets>> {
        const requestOptions = await this.portfoliosTotalAssetsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseTotalAssetsFromJSON(jsonValue));
    }

    /**
     * Get total assets across all brokerage accounts, grouped by brokerage. All values are converted to the requested currency.
     * Get total assets
     */
    async portfoliosTotalAssetsGet(requestParameters: PortfoliosTotalAssetsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseTotalAssets> {
        const response = await this.portfoliosTotalAssetsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum PortfoliosAssetsSummaryGetCurrencyEnum {
    Usd = 'USD',
    Vnd = 'VND',
    Usdt = 'USDT'
}
/**
  * @export
  * @enum {string}
  */
export enum PortfoliosSummaryGetCurrencyEnum {
    Usd = 'USD',
    Vnd = 'VND',
    Usdt = 'USDT'
}
/**
  * @export
  * @enum {string}
  */
export enum PortfoliosTotalAssetsGetCurrencyEnum {
    Usd = 'USD',
    Vnd = 'VND',
    Usdt = 'USDT'
}
