/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BaseResponseAny,
  HTTPListResearchStrategiesResponse,
  HTTPSubmitResearchRequest,
  SubmitResearchResponse,
} from '../models/index';
import {
    BaseResponseAnyFromJSON,
    BaseResponseAnyToJSON,
    HTTPListResearchStrategiesResponseFromJSON,
    HTTPListResearchStrategiesResponseToJSON,
    HTTPSubmitResearchRequestFromJSON,
    HTTPSubmitResearchRequestToJSON,
    SubmitResearchResponseFromJSON,
    SubmitResearchResponseToJSON,
} from '../models/index';

export interface StrategiesResearchMineGetRequest {
    tags?: Array<string>;
    status?: string;
    startDate?: string;
    endDate?: string;
    minReturn?: number;
    maxReturn?: number;
    page?: number;
    limit?: number;
}

export interface StrategiesResearchSubmitAndBacktestPostRequest {
    request: HTTPSubmitResearchRequest;
}

/**
 * 
 */
export class ResearchApi extends runtime.BaseAPI {

    /**
     * Creates request options for strategiesResearchMineGet without sending the request
     */
    async strategiesResearchMineGetRequestOpts(requestParameters: StrategiesResearchMineGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['tags'] != null) {
            queryParameters['tags'] = requestParameters['tags']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['startDate'] != null) {
            queryParameters['start_date'] = requestParameters['startDate'];
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['end_date'] = requestParameters['endDate'];
        }

        if (requestParameters['minReturn'] != null) {
            queryParameters['min_return'] = requestParameters['minReturn'];
        }

        if (requestParameters['maxReturn'] != null) {
            queryParameters['max_return'] = requestParameters['maxReturn'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/research/mine`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get paginated list of research strategies for the authenticated user with filtering options
     * List My Research Strategies
     */
    async strategiesResearchMineGetRaw(requestParameters: StrategiesResearchMineGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HTTPListResearchStrategiesResponse>> {
        const requestOptions = await this.strategiesResearchMineGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HTTPListResearchStrategiesResponseFromJSON(jsonValue));
    }

    /**
     * Get paginated list of research strategies for the authenticated user with filtering options
     * List My Research Strategies
     */
    async strategiesResearchMineGet(requestParameters: StrategiesResearchMineGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HTTPListResearchStrategiesResponse> {
        const response = await this.strategiesResearchMineGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesResearchSubmitAndBacktestPost without sending the request
     */
    async strategiesResearchSubmitAndBacktestPostRequestOpts(requestParameters: StrategiesResearchSubmitAndBacktestPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling strategiesResearchSubmitAndBacktestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/research/submit-and-backtest`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HTTPSubmitResearchRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Submit a new research strategy and automatically run a backtest on it
     * Submit Research and Backtest
     */
    async strategiesResearchSubmitAndBacktestPostRaw(requestParameters: StrategiesResearchSubmitAndBacktestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubmitResearchResponse>> {
        const requestOptions = await this.strategiesResearchSubmitAndBacktestPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubmitResearchResponseFromJSON(jsonValue));
    }

    /**
     * Submit a new research strategy and automatically run a backtest on it
     * Submit Research and Backtest
     */
    async strategiesResearchSubmitAndBacktestPost(requestParameters: StrategiesResearchSubmitAndBacktestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubmitResearchResponse> {
        const response = await this.strategiesResearchSubmitAndBacktestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
