/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdjustRulesRequest,
  BaseResponseAdjustRulesResponse,
  BaseResponseAny,
  BaseResponseArrayStrategyAlert,
  BaseResponseCreateAlertResponse,
  BaseResponseCreateBacktestResponse,
  BaseResponseRollbackToVersionResponse,
  BaseResponseStrategy,
  BaseResponseStrategyAlert,
  BaseResponseStrategySchedule,
  BaseResponseString,
  CreateAlertRequest,
  CreateBacktestRequest,
  CreateLiveTradingRequest,
  CreatePaperTradingRequest,
  CreateStrategyRequest,
  ScheduleStrategyRequest,
  UpdateAlertRequest,
  UpdateStrategyRequest,
} from '../models/index';
import {
    AdjustRulesRequestFromJSON,
    AdjustRulesRequestToJSON,
    BaseResponseAdjustRulesResponseFromJSON,
    BaseResponseAdjustRulesResponseToJSON,
    BaseResponseAnyFromJSON,
    BaseResponseAnyToJSON,
    BaseResponseArrayStrategyAlertFromJSON,
    BaseResponseArrayStrategyAlertToJSON,
    BaseResponseCreateAlertResponseFromJSON,
    BaseResponseCreateAlertResponseToJSON,
    BaseResponseCreateBacktestResponseFromJSON,
    BaseResponseCreateBacktestResponseToJSON,
    BaseResponseRollbackToVersionResponseFromJSON,
    BaseResponseRollbackToVersionResponseToJSON,
    BaseResponseStrategyFromJSON,
    BaseResponseStrategyToJSON,
    BaseResponseStrategyAlertFromJSON,
    BaseResponseStrategyAlertToJSON,
    BaseResponseStrategyScheduleFromJSON,
    BaseResponseStrategyScheduleToJSON,
    BaseResponseStringFromJSON,
    BaseResponseStringToJSON,
    CreateAlertRequestFromJSON,
    CreateAlertRequestToJSON,
    CreateBacktestRequestFromJSON,
    CreateBacktestRequestToJSON,
    CreateLiveTradingRequestFromJSON,
    CreateLiveTradingRequestToJSON,
    CreatePaperTradingRequestFromJSON,
    CreatePaperTradingRequestToJSON,
    CreateStrategyRequestFromJSON,
    CreateStrategyRequestToJSON,
    ScheduleStrategyRequestFromJSON,
    ScheduleStrategyRequestToJSON,
    UpdateAlertRequestFromJSON,
    UpdateAlertRequestToJSON,
    UpdateStrategyRequestFromJSON,
    UpdateStrategyRequestToJSON,
} from '../models/index';

export interface StrategiesGetRequest {
    page?: number;
    pageSize?: number;
    keyword?: string;
}

export interface StrategiesIdAdjustRulesPostRequest {
    id: number;
    request: AdjustRulesRequest;
}

export interface StrategiesIdAlertsAlertIdDeleteRequest {
    id: number;
    alertId: number;
}

export interface StrategiesIdAlertsAlertIdPutRequest {
    id: number;
    alertId: number;
    request: UpdateAlertRequest;
}

export interface StrategiesIdAlertsGetRequest {
    id: number;
}

export interface StrategiesIdAlertsPostRequest {
    id: number;
    request: CreateAlertRequest;
}

export interface StrategiesIdBacktestPostRequest {
    id: number;
    request: CreateBacktestRequest;
}

export interface StrategiesIdDeleteRequest {
    id: number;
}

export interface StrategiesIdExecutionHistoryGetRequest {
    id: number;
    page?: number;
    pageSize?: number;
    status?: string;
}

export interface StrategiesIdGetRequest {
    id: number;
}

export interface StrategiesIdLivePostRequest {
    id: number;
    request: CreateLiveTradingRequest;
}

export interface StrategiesIdPaperPostRequest {
    id: number;
    request: CreatePaperTradingRequest;
}

export interface StrategiesIdPutRequest {
    id: number;
    request: UpdateStrategyRequest;
}

export interface StrategiesIdScheduleGetRequest {
    id: number;
}

export interface StrategiesIdSchedulePostRequest {
    id: number;
    request: ScheduleStrategyRequest;
}

export interface StrategiesIdVersionsGetRequest {
    id: number;
    page?: number;
    pageSize?: number;
}

export interface StrategiesIdVersionsVersionIdRollbackPostRequest {
    id: number;
    versionId: number;
}

export interface StrategiesPostRequest {
    request: CreateStrategyRequest;
}

export interface StrategiesSchedulesScheduleIdDeleteRequest {
    scheduleId: number;
}

export interface StrategiesSchedulesScheduleIdPutRequest {
    scheduleId: number;
    request: ScheduleStrategyRequest;
}

/**
 * 
 */
export class StrategiesApi extends runtime.BaseAPI {

    /**
     * Creates request options for strategiesGet without sending the request
     */
    async strategiesGetRequestOpts(requestParameters: StrategiesGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['keyword'] != null) {
            queryParameters['keyword'] = requestParameters['keyword'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get paginated list of strategies for the authenticated user
     * List strategies
     */
    async strategiesGetRaw(requestParameters: StrategiesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseAny>> {
        const requestOptions = await this.strategiesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseAnyFromJSON(jsonValue));
    }

    /**
     * Get paginated list of strategies for the authenticated user
     * List strategies
     */
    async strategiesGet(requestParameters: StrategiesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseAny> {
        const response = await this.strategiesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdAdjustRulesPost without sending the request
     */
    async strategiesIdAdjustRulesPostRequestOpts(requestParameters: StrategiesIdAdjustRulesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdAdjustRulesPost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling strategiesIdAdjustRulesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}/adjust-rules`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdjustRulesRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Optimize strategy parameters using machine learning (shadow mode recommended for safety)
     * Optimize strategy parameters
     */
    async strategiesIdAdjustRulesPostRaw(requestParameters: StrategiesIdAdjustRulesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseAdjustRulesResponse>> {
        const requestOptions = await this.strategiesIdAdjustRulesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseAdjustRulesResponseFromJSON(jsonValue));
    }

    /**
     * Optimize strategy parameters using machine learning (shadow mode recommended for safety)
     * Optimize strategy parameters
     */
    async strategiesIdAdjustRulesPost(requestParameters: StrategiesIdAdjustRulesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseAdjustRulesResponse> {
        const response = await this.strategiesIdAdjustRulesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdAlertsAlertIdDelete without sending the request
     */
    async strategiesIdAlertsAlertIdDeleteRequestOpts(requestParameters: StrategiesIdAlertsAlertIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdAlertsAlertIdDelete().'
            );
        }

        if (requestParameters['alertId'] == null) {
            throw new runtime.RequiredError(
                'alertId',
                'Required parameter "alertId" was null or undefined when calling strategiesIdAlertsAlertIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}/alerts/{alertId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"alertId"}}`, encodeURIComponent(String(requestParameters['alertId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a risk management alert for a strategy
     * Delete strategy alert
     */
    async strategiesIdAlertsAlertIdDeleteRaw(requestParameters: StrategiesIdAlertsAlertIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseAny>> {
        const requestOptions = await this.strategiesIdAlertsAlertIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseAnyFromJSON(jsonValue));
    }

    /**
     * Delete a risk management alert for a strategy
     * Delete strategy alert
     */
    async strategiesIdAlertsAlertIdDelete(requestParameters: StrategiesIdAlertsAlertIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseAny> {
        const response = await this.strategiesIdAlertsAlertIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdAlertsAlertIdPut without sending the request
     */
    async strategiesIdAlertsAlertIdPutRequestOpts(requestParameters: StrategiesIdAlertsAlertIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdAlertsAlertIdPut().'
            );
        }

        if (requestParameters['alertId'] == null) {
            throw new runtime.RequiredError(
                'alertId',
                'Required parameter "alertId" was null or undefined when calling strategiesIdAlertsAlertIdPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling strategiesIdAlertsAlertIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}/alerts/{alertId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"alertId"}}`, encodeURIComponent(String(requestParameters['alertId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAlertRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Update a risk management alert for a strategy
     * Update strategy alert
     */
    async strategiesIdAlertsAlertIdPutRaw(requestParameters: StrategiesIdAlertsAlertIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseStrategyAlert>> {
        const requestOptions = await this.strategiesIdAlertsAlertIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseStrategyAlertFromJSON(jsonValue));
    }

    /**
     * Update a risk management alert for a strategy
     * Update strategy alert
     */
    async strategiesIdAlertsAlertIdPut(requestParameters: StrategiesIdAlertsAlertIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseStrategyAlert> {
        const response = await this.strategiesIdAlertsAlertIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdAlertsGet without sending the request
     */
    async strategiesIdAlertsGetRequestOpts(requestParameters: StrategiesIdAlertsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdAlertsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}/alerts`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all risk management alerts for a specific strategy
     * Get strategy alerts
     */
    async strategiesIdAlertsGetRaw(requestParameters: StrategiesIdAlertsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseArrayStrategyAlert>> {
        const requestOptions = await this.strategiesIdAlertsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseArrayStrategyAlertFromJSON(jsonValue));
    }

    /**
     * Get all risk management alerts for a specific strategy
     * Get strategy alerts
     */
    async strategiesIdAlertsGet(requestParameters: StrategiesIdAlertsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseArrayStrategyAlert> {
        const response = await this.strategiesIdAlertsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdAlertsPost without sending the request
     */
    async strategiesIdAlertsPostRequestOpts(requestParameters: StrategiesIdAlertsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdAlertsPost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling strategiesIdAlertsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}/alerts`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAlertRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create a risk management alert (circuit breaker) for a strategy
     * Create strategy alert
     */
    async strategiesIdAlertsPostRaw(requestParameters: StrategiesIdAlertsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseCreateAlertResponse>> {
        const requestOptions = await this.strategiesIdAlertsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseCreateAlertResponseFromJSON(jsonValue));
    }

    /**
     * Create a risk management alert (circuit breaker) for a strategy
     * Create strategy alert
     */
    async strategiesIdAlertsPost(requestParameters: StrategiesIdAlertsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseCreateAlertResponse> {
        const response = await this.strategiesIdAlertsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdBacktestPost without sending the request
     */
    async strategiesIdBacktestPostRequestOpts(requestParameters: StrategiesIdBacktestPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdBacktestPost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling strategiesIdBacktestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}/backtest`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBacktestRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create and execute a backtest for a specific strategy
     * Create Backtest for Strategy
     */
    async strategiesIdBacktestPostRaw(requestParameters: StrategiesIdBacktestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseString>> {
        const requestOptions = await this.strategiesIdBacktestPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseStringFromJSON(jsonValue));
    }

    /**
     * Create and execute a backtest for a specific strategy
     * Create Backtest for Strategy
     */
    async strategiesIdBacktestPost(requestParameters: StrategiesIdBacktestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseString> {
        const response = await this.strategiesIdBacktestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdDelete without sending the request
     */
    async strategiesIdDeleteRequestOpts(requestParameters: StrategiesIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a specific strategy by ID for authenticated user
     * Delete strategy
     */
    async strategiesIdDeleteRaw(requestParameters: StrategiesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseAny>> {
        const requestOptions = await this.strategiesIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseAnyFromJSON(jsonValue));
    }

    /**
     * Delete a specific strategy by ID for authenticated user
     * Delete strategy
     */
    async strategiesIdDelete(requestParameters: StrategiesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseAny> {
        const response = await this.strategiesIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdExecutionHistoryGet without sending the request
     */
    async strategiesIdExecutionHistoryGetRequestOpts(requestParameters: StrategiesIdExecutionHistoryGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdExecutionHistoryGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}/execution-history`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the execution history for a specific strategy
     * Get execution history
     */
    async strategiesIdExecutionHistoryGetRaw(requestParameters: StrategiesIdExecutionHistoryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseAny>> {
        const requestOptions = await this.strategiesIdExecutionHistoryGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseAnyFromJSON(jsonValue));
    }

    /**
     * Get the execution history for a specific strategy
     * Get execution history
     */
    async strategiesIdExecutionHistoryGet(requestParameters: StrategiesIdExecutionHistoryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseAny> {
        const response = await this.strategiesIdExecutionHistoryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdGet without sending the request
     */
    async strategiesIdGetRequestOpts(requestParameters: StrategiesIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a specific strategy by ID for the authenticated user
     * Get strategy by ID
     */
    async strategiesIdGetRaw(requestParameters: StrategiesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseStrategy>> {
        const requestOptions = await this.strategiesIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseStrategyFromJSON(jsonValue));
    }

    /**
     * Get a specific strategy by ID for the authenticated user
     * Get strategy by ID
     */
    async strategiesIdGet(requestParameters: StrategiesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseStrategy> {
        const response = await this.strategiesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdLivePost without sending the request
     */
    async strategiesIdLivePostRequestOpts(requestParameters: StrategiesIdLivePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdLivePost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling strategiesIdLivePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}/live`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateLiveTradingRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create and execute a live trading run for a specific strategy
     * Create Live Trading for Strategy
     */
    async strategiesIdLivePostRaw(requestParameters: StrategiesIdLivePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseCreateBacktestResponse>> {
        const requestOptions = await this.strategiesIdLivePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseCreateBacktestResponseFromJSON(jsonValue));
    }

    /**
     * Create and execute a live trading run for a specific strategy
     * Create Live Trading for Strategy
     */
    async strategiesIdLivePost(requestParameters: StrategiesIdLivePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseCreateBacktestResponse> {
        const response = await this.strategiesIdLivePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdPaperPost without sending the request
     */
    async strategiesIdPaperPostRequestOpts(requestParameters: StrategiesIdPaperPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdPaperPost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling strategiesIdPaperPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}/paper`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePaperTradingRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create and execute a paper trading run for a specific strategy
     * Create Paper Trading for Strategy
     */
    async strategiesIdPaperPostRaw(requestParameters: StrategiesIdPaperPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseCreateBacktestResponse>> {
        const requestOptions = await this.strategiesIdPaperPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseCreateBacktestResponseFromJSON(jsonValue));
    }

    /**
     * Create and execute a paper trading run for a specific strategy
     * Create Paper Trading for Strategy
     */
    async strategiesIdPaperPost(requestParameters: StrategiesIdPaperPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseCreateBacktestResponse> {
        const response = await this.strategiesIdPaperPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdPut without sending the request
     */
    async strategiesIdPutRequestOpts(requestParameters: StrategiesIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling strategiesIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateStrategyRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Update a specific strategy by ID for the authenticated user
     * Update strategy
     */
    async strategiesIdPutRaw(requestParameters: StrategiesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseStrategy>> {
        const requestOptions = await this.strategiesIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseStrategyFromJSON(jsonValue));
    }

    /**
     * Update a specific strategy by ID for the authenticated user
     * Update strategy
     */
    async strategiesIdPut(requestParameters: StrategiesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseStrategy> {
        const response = await this.strategiesIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdScheduleGet without sending the request
     */
    async strategiesIdScheduleGetRequestOpts(requestParameters: StrategiesIdScheduleGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdScheduleGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}/schedule`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the schedule configuration for a specific strategy
     * Get strategy schedule
     */
    async strategiesIdScheduleGetRaw(requestParameters: StrategiesIdScheduleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseStrategySchedule>> {
        const requestOptions = await this.strategiesIdScheduleGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseStrategyScheduleFromJSON(jsonValue));
    }

    /**
     * Get the schedule configuration for a specific strategy
     * Get strategy schedule
     */
    async strategiesIdScheduleGet(requestParameters: StrategiesIdScheduleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseStrategySchedule> {
        const response = await this.strategiesIdScheduleGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdSchedulePost without sending the request
     */
    async strategiesIdSchedulePostRequestOpts(requestParameters: StrategiesIdSchedulePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdSchedulePost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling strategiesIdSchedulePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}/schedule`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleStrategyRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Schedule a strategy to run automatically with a cron expression
     * Schedule a strategy
     */
    async strategiesIdSchedulePostRaw(requestParameters: StrategiesIdSchedulePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseStrategySchedule>> {
        const requestOptions = await this.strategiesIdSchedulePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseStrategyScheduleFromJSON(jsonValue));
    }

    /**
     * Schedule a strategy to run automatically with a cron expression
     * Schedule a strategy
     */
    async strategiesIdSchedulePost(requestParameters: StrategiesIdSchedulePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseStrategySchedule> {
        const response = await this.strategiesIdSchedulePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdVersionsGet without sending the request
     */
    async strategiesIdVersionsGetRequestOpts(requestParameters: StrategiesIdVersionsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdVersionsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}/versions`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get paginated list of versions for a specific strategy
     * List strategy versions
     */
    async strategiesIdVersionsGetRaw(requestParameters: StrategiesIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseAny>> {
        const requestOptions = await this.strategiesIdVersionsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseAnyFromJSON(jsonValue));
    }

    /**
     * Get paginated list of versions for a specific strategy
     * List strategy versions
     */
    async strategiesIdVersionsGet(requestParameters: StrategiesIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseAny> {
        const response = await this.strategiesIdVersionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesIdVersionsVersionIdRollbackPost without sending the request
     */
    async strategiesIdVersionsVersionIdRollbackPostRequestOpts(requestParameters: StrategiesIdVersionsVersionIdRollbackPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling strategiesIdVersionsVersionIdRollbackPost().'
            );
        }

        if (requestParameters['versionId'] == null) {
            throw new runtime.RequiredError(
                'versionId',
                'Required parameter "versionId" was null or undefined when calling strategiesIdVersionsVersionIdRollbackPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/{id}/versions/{versionId}/rollback`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"versionId"}}`, encodeURIComponent(String(requestParameters['versionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Rollback a strategy to a specific version
     * Rollback strategy to version
     */
    async strategiesIdVersionsVersionIdRollbackPostRaw(requestParameters: StrategiesIdVersionsVersionIdRollbackPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseRollbackToVersionResponse>> {
        const requestOptions = await this.strategiesIdVersionsVersionIdRollbackPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseRollbackToVersionResponseFromJSON(jsonValue));
    }

    /**
     * Rollback a strategy to a specific version
     * Rollback strategy to version
     */
    async strategiesIdVersionsVersionIdRollbackPost(requestParameters: StrategiesIdVersionsVersionIdRollbackPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseRollbackToVersionResponse> {
        const response = await this.strategiesIdVersionsVersionIdRollbackPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesPost without sending the request
     */
    async strategiesPostRequestOpts(requestParameters: StrategiesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling strategiesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateStrategyRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create a new strategy for the authenticated user
     * Create a new strategy
     */
    async strategiesPostRaw(requestParameters: StrategiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseStrategy>> {
        const requestOptions = await this.strategiesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseStrategyFromJSON(jsonValue));
    }

    /**
     * Create a new strategy for the authenticated user
     * Create a new strategy
     */
    async strategiesPost(requestParameters: StrategiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseStrategy> {
        const response = await this.strategiesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesSchedulesScheduleIdDelete without sending the request
     */
    async strategiesSchedulesScheduleIdDeleteRequestOpts(requestParameters: StrategiesSchedulesScheduleIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scheduleId'] == null) {
            throw new runtime.RequiredError(
                'scheduleId',
                'Required parameter "scheduleId" was null or undefined when calling strategiesSchedulesScheduleIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/schedules/{scheduleId}`;
        urlPath = urlPath.replace(`{${"scheduleId"}}`, encodeURIComponent(String(requestParameters['scheduleId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete the schedule configuration for a specific strategy
     * Delete strategy schedule
     */
    async strategiesSchedulesScheduleIdDeleteRaw(requestParameters: StrategiesSchedulesScheduleIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseAny>> {
        const requestOptions = await this.strategiesSchedulesScheduleIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseAnyFromJSON(jsonValue));
    }

    /**
     * Delete the schedule configuration for a specific strategy
     * Delete strategy schedule
     */
    async strategiesSchedulesScheduleIdDelete(requestParameters: StrategiesSchedulesScheduleIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseAny> {
        const response = await this.strategiesSchedulesScheduleIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for strategiesSchedulesScheduleIdPut without sending the request
     */
    async strategiesSchedulesScheduleIdPutRequestOpts(requestParameters: StrategiesSchedulesScheduleIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scheduleId'] == null) {
            throw new runtime.RequiredError(
                'scheduleId',
                'Required parameter "scheduleId" was null or undefined when calling strategiesSchedulesScheduleIdPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling strategiesSchedulesScheduleIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/strategies/schedules/{scheduleId}`;
        urlPath = urlPath.replace(`{${"scheduleId"}}`, encodeURIComponent(String(requestParameters['scheduleId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleStrategyRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Update the schedule configuration for a specific strategy
     * Update strategy schedule
     */
    async strategiesSchedulesScheduleIdPutRaw(requestParameters: StrategiesSchedulesScheduleIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseStrategySchedule>> {
        const requestOptions = await this.strategiesSchedulesScheduleIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseStrategyScheduleFromJSON(jsonValue));
    }

    /**
     * Update the schedule configuration for a specific strategy
     * Update strategy schedule
     */
    async strategiesSchedulesScheduleIdPut(requestParameters: StrategiesSchedulesScheduleIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseStrategySchedule> {
        const response = await this.strategiesSchedulesScheduleIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
