/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BaseResponseAny,
  BaseResponseArrayTradingClientListItem,
  BaseResponseTradingClient,
  CreateTradingClientRequest,
  UpdateTradingClientRequest,
} from '../models/index';
import {
    BaseResponseAnyFromJSON,
    BaseResponseAnyToJSON,
    BaseResponseArrayTradingClientListItemFromJSON,
    BaseResponseArrayTradingClientListItemToJSON,
    BaseResponseTradingClientFromJSON,
    BaseResponseTradingClientToJSON,
    CreateTradingClientRequestFromJSON,
    CreateTradingClientRequestToJSON,
    UpdateTradingClientRequestFromJSON,
    UpdateTradingClientRequestToJSON,
} from '../models/index';

export interface TradingClientsGetRequest {
    lang?: TradingClientsGetLangEnum;
}

export interface TradingClientsIdDeleteRequest {
    id: number;
    lang?: TradingClientsIdDeleteLangEnum;
}

export interface TradingClientsIdPutRequest {
    id: number;
    request: UpdateTradingClientRequest;
    lang?: TradingClientsIdPutLangEnum;
}

export interface TradingClientsPostRequest {
    request: CreateTradingClientRequest;
    lang?: TradingClientsPostLangEnum;
}

/**
 * 
 */
export class TradingClientsApi extends runtime.BaseAPI {

    /**
     * Creates request options for tradingClientsGet without sending the request
     */
    async tradingClientsGetRequestOpts(requestParameters: TradingClientsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['lang'] != null) {
            headerParameters['lang'] = String(requestParameters['lang']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/trading-clients`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all active trading clients for the authenticated user
     * Get all trading clients
     */
    async tradingClientsGetRaw(requestParameters: TradingClientsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseArrayTradingClientListItem>> {
        const requestOptions = await this.tradingClientsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseArrayTradingClientListItemFromJSON(jsonValue));
    }

    /**
     * Get all active trading clients for the authenticated user
     * Get all trading clients
     */
    async tradingClientsGet(requestParameters: TradingClientsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseArrayTradingClientListItem> {
        const response = await this.tradingClientsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for tradingClientsIdDelete without sending the request
     */
    async tradingClientsIdDeleteRequestOpts(requestParameters: TradingClientsIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling tradingClientsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['lang'] != null) {
            headerParameters['lang'] = String(requestParameters['lang']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/trading-clients/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a trading client (soft delete by setting status to false)
     * Delete trading client
     */
    async tradingClientsIdDeleteRaw(requestParameters: TradingClientsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseTradingClient>> {
        const requestOptions = await this.tradingClientsIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseTradingClientFromJSON(jsonValue));
    }

    /**
     * Delete a trading client (soft delete by setting status to false)
     * Delete trading client
     */
    async tradingClientsIdDelete(requestParameters: TradingClientsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseTradingClient> {
        const response = await this.tradingClientsIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for tradingClientsIdPut without sending the request
     */
    async tradingClientsIdPutRequestOpts(requestParameters: TradingClientsIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling tradingClientsIdPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling tradingClientsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['lang'] != null) {
            headerParameters['lang'] = String(requestParameters['lang']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/trading-clients/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTradingClientRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Update an existing trading client
     * Update trading client
     */
    async tradingClientsIdPutRaw(requestParameters: TradingClientsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseTradingClient>> {
        const requestOptions = await this.tradingClientsIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseTradingClientFromJSON(jsonValue));
    }

    /**
     * Update an existing trading client
     * Update trading client
     */
    async tradingClientsIdPut(requestParameters: TradingClientsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseTradingClient> {
        const response = await this.tradingClientsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for tradingClientsPost without sending the request
     */
    async tradingClientsPostRequestOpts(requestParameters: TradingClientsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling tradingClientsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['lang'] != null) {
            headerParameters['lang'] = String(requestParameters['lang']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/trading-clients`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTradingClientRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create a new trading client for the authenticated user
     * Create trading client
     */
    async tradingClientsPostRaw(requestParameters: TradingClientsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseTradingClient>> {
        const requestOptions = await this.tradingClientsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseTradingClientFromJSON(jsonValue));
    }

    /**
     * Create a new trading client for the authenticated user
     * Create trading client
     */
    async tradingClientsPost(requestParameters: TradingClientsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseTradingClient> {
        const response = await this.tradingClientsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum TradingClientsGetLangEnum {
    En = 'en',
    Vi = 'vi'
}
/**
  * @export
  * @enum {string}
  */
export enum TradingClientsIdDeleteLangEnum {
    En = 'en',
    Vi = 'vi'
}
/**
  * @export
  * @enum {string}
  */
export enum TradingClientsIdPutLangEnum {
    En = 'en',
    Vi = 'vi'
}
/**
  * @export
  * @enum {string}
  */
export enum TradingClientsPostLangEnum {
    En = 'en',
    Vi = 'vi'
}
