/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BaseResponseAny,
  CoreUploadTransportHttpGetPresignedUploadURLResponse,
  GetPresignedUploadURLRequest,
} from '../models/index';
import {
    BaseResponseAnyFromJSON,
    BaseResponseAnyToJSON,
    CoreUploadTransportHttpGetPresignedUploadURLResponseFromJSON,
    CoreUploadTransportHttpGetPresignedUploadURLResponseToJSON,
    GetPresignedUploadURLRequestFromJSON,
    GetPresignedUploadURLRequestToJSON,
} from '../models/index';

export interface UploadPresignedUrlPostRequest {
    request: GetPresignedUploadURLRequest;
}

/**
 * 
 */
export class UploadApi extends runtime.BaseAPI {

    /**
     * Creates request options for uploadPresignedUrlPost without sending the request
     */
    async uploadPresignedUrlPostRequestOpts(requestParameters: UploadPresignedUrlPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling uploadPresignedUrlPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/upload/presigned-url`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetPresignedUploadURLRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Get a presigned URL for uploading files to S3. The folder parameter determines upload path.
     * Get presigned upload URL
     */
    async uploadPresignedUrlPostRaw(requestParameters: UploadPresignedUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoreUploadTransportHttpGetPresignedUploadURLResponse>> {
        const requestOptions = await this.uploadPresignedUrlPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoreUploadTransportHttpGetPresignedUploadURLResponseFromJSON(jsonValue));
    }

    /**
     * Get a presigned URL for uploading files to S3. The folder parameter determines upload path.
     * Get presigned upload URL
     */
    async uploadPresignedUrlPost(requestParameters: UploadPresignedUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoreUploadTransportHttpGetPresignedUploadURLResponse> {
        const response = await this.uploadPresignedUrlPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
