/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BaseResponseAny,
  BaseResponseArrayStockItemWatchList,
  CoreWatchlistTransportHttpBulkCreateItemsRequest,
  CoreWatchlistTransportHttpBulkCreateItemsResponse,
  CoreWatchlistTransportHttpBulkDeleteItemsRequest,
  CoreWatchlistTransportHttpCreateItemRequest,
  CoreWatchlistTransportHttpCreateItemResponse,
  CoreWatchlistTransportHttpCreateWatchListRequest,
  CoreWatchlistTransportHttpCreateWatchListResponse,
  CoreWatchlistTransportHttpGetStockItemResponse,
  CoreWatchlistTransportHttpGetWatchListResponse,
  CoreWatchlistTransportHttpListWatchListsResponse,
  CoreWatchlistTransportHttpReorderItemsRequest,
  CoreWatchlistTransportHttpUpdateItemRequest,
  CoreWatchlistTransportHttpUpdateItemResponse,
  CoreWatchlistTransportHttpUpdateWatchListRequest,
  CoreWatchlistTransportHttpUpdateWatchListResponse,
} from '../models/index';
import {
    BaseResponseAnyFromJSON,
    BaseResponseAnyToJSON,
    BaseResponseArrayStockItemWatchListFromJSON,
    BaseResponseArrayStockItemWatchListToJSON,
    CoreWatchlistTransportHttpBulkCreateItemsRequestFromJSON,
    CoreWatchlistTransportHttpBulkCreateItemsRequestToJSON,
    CoreWatchlistTransportHttpBulkCreateItemsResponseFromJSON,
    CoreWatchlistTransportHttpBulkCreateItemsResponseToJSON,
    CoreWatchlistTransportHttpBulkDeleteItemsRequestFromJSON,
    CoreWatchlistTransportHttpBulkDeleteItemsRequestToJSON,
    CoreWatchlistTransportHttpCreateItemRequestFromJSON,
    CoreWatchlistTransportHttpCreateItemRequestToJSON,
    CoreWatchlistTransportHttpCreateItemResponseFromJSON,
    CoreWatchlistTransportHttpCreateItemResponseToJSON,
    CoreWatchlistTransportHttpCreateWatchListRequestFromJSON,
    CoreWatchlistTransportHttpCreateWatchListRequestToJSON,
    CoreWatchlistTransportHttpCreateWatchListResponseFromJSON,
    CoreWatchlistTransportHttpCreateWatchListResponseToJSON,
    CoreWatchlistTransportHttpGetStockItemResponseFromJSON,
    CoreWatchlistTransportHttpGetStockItemResponseToJSON,
    CoreWatchlistTransportHttpGetWatchListResponseFromJSON,
    CoreWatchlistTransportHttpGetWatchListResponseToJSON,
    CoreWatchlistTransportHttpListWatchListsResponseFromJSON,
    CoreWatchlistTransportHttpListWatchListsResponseToJSON,
    CoreWatchlistTransportHttpReorderItemsRequestFromJSON,
    CoreWatchlistTransportHttpReorderItemsRequestToJSON,
    CoreWatchlistTransportHttpUpdateItemRequestFromJSON,
    CoreWatchlistTransportHttpUpdateItemRequestToJSON,
    CoreWatchlistTransportHttpUpdateItemResponseFromJSON,
    CoreWatchlistTransportHttpUpdateItemResponseToJSON,
    CoreWatchlistTransportHttpUpdateWatchListRequestFromJSON,
    CoreWatchlistTransportHttpUpdateWatchListRequestToJSON,
    CoreWatchlistTransportHttpUpdateWatchListResponseFromJSON,
    CoreWatchlistTransportHttpUpdateWatchListResponseToJSON,
} from '../models/index';

export interface WatchListsGetRequest {
    page?: number;
    pageSize?: number;
}

export interface WatchListsIdDeleteRequest {
    id: number;
}

export interface WatchListsIdGetRequest {
    id: number;
}

export interface WatchListsIdItemsBulkPostRequest {
    id: number;
    request: CoreWatchlistTransportHttpBulkCreateItemsRequest;
}

export interface WatchListsIdItemsDeletePostRequest {
    id: number;
    request: CoreWatchlistTransportHttpBulkDeleteItemsRequest;
}

export interface WatchListsIdItemsGetRequest {
    id: number;
}

export interface WatchListsIdItemsItemIdDeleteRequest {
    id: number;
    itemId: number;
}

export interface WatchListsIdItemsItemIdGetRequest {
    id: number;
    itemId: number;
}

export interface WatchListsIdItemsItemIdPutRequest {
    id: number;
    itemId: number;
    request: CoreWatchlistTransportHttpUpdateItemRequest;
}

export interface WatchListsIdItemsPostRequest {
    id: number;
    request: CoreWatchlistTransportHttpCreateItemRequest;
}

export interface WatchListsIdItemsReorderPutRequest {
    id: number;
    request: CoreWatchlistTransportHttpReorderItemsRequest;
}

export interface WatchListsIdPutRequest {
    id: number;
    request: CoreWatchlistTransportHttpUpdateWatchListRequest;
}

export interface WatchListsPostRequest {
    request: CoreWatchlistTransportHttpCreateWatchListRequest;
}

/**
 * 
 */
export class WatchlistsApi extends runtime.BaseAPI {

    /**
     * Creates request options for watchListsGet without sending the request
     */
    async watchListsGetRequestOpts(requestParameters: WatchListsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/watch-lists`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get paginated list of watch lists for the authenticated user
     * List Watch Lists
     */
    async watchListsGetRaw(requestParameters: WatchListsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoreWatchlistTransportHttpListWatchListsResponse>> {
        const requestOptions = await this.watchListsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoreWatchlistTransportHttpListWatchListsResponseFromJSON(jsonValue));
    }

    /**
     * Get paginated list of watch lists for the authenticated user
     * List Watch Lists
     */
    async watchListsGet(requestParameters: WatchListsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoreWatchlistTransportHttpListWatchListsResponse> {
        const response = await this.watchListsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for watchListsIdDelete without sending the request
     */
    async watchListsIdDeleteRequestOpts(requestParameters: WatchListsIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling watchListsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/watch-lists/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a watch list
     * Delete Watch List
     */
    async watchListsIdDeleteRaw(requestParameters: WatchListsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.watchListsIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a watch list
     * Delete Watch List
     */
    async watchListsIdDelete(requestParameters: WatchListsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.watchListsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for watchListsIdGet without sending the request
     */
    async watchListsIdGetRequestOpts(requestParameters: WatchListsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling watchListsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/watch-lists/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a specific watch list by ID
     * Get Watch List by ID
     */
    async watchListsIdGetRaw(requestParameters: WatchListsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoreWatchlistTransportHttpGetWatchListResponse>> {
        const requestOptions = await this.watchListsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoreWatchlistTransportHttpGetWatchListResponseFromJSON(jsonValue));
    }

    /**
     * Get a specific watch list by ID
     * Get Watch List by ID
     */
    async watchListsIdGet(requestParameters: WatchListsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoreWatchlistTransportHttpGetWatchListResponse> {
        const response = await this.watchListsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for watchListsIdItemsBulkPost without sending the request
     */
    async watchListsIdItemsBulkPostRequestOpts(requestParameters: WatchListsIdItemsBulkPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling watchListsIdItemsBulkPost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling watchListsIdItemsBulkPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/watch-lists/{id}/items/bulk`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CoreWatchlistTransportHttpBulkCreateItemsRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Add multiple stock items to a watch list
     * Bulk Add Stock Items
     */
    async watchListsIdItemsBulkPostRaw(requestParameters: WatchListsIdItemsBulkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoreWatchlistTransportHttpBulkCreateItemsResponse>> {
        const requestOptions = await this.watchListsIdItemsBulkPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoreWatchlistTransportHttpBulkCreateItemsResponseFromJSON(jsonValue));
    }

    /**
     * Add multiple stock items to a watch list
     * Bulk Add Stock Items
     */
    async watchListsIdItemsBulkPost(requestParameters: WatchListsIdItemsBulkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoreWatchlistTransportHttpBulkCreateItemsResponse> {
        const response = await this.watchListsIdItemsBulkPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for watchListsIdItemsDeletePost without sending the request
     */
    async watchListsIdItemsDeletePostRequestOpts(requestParameters: WatchListsIdItemsDeletePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling watchListsIdItemsDeletePost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling watchListsIdItemsDeletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/watch-lists/{id}/items/delete`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CoreWatchlistTransportHttpBulkDeleteItemsRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Delete multiple items from a watch list
     * Bulk Delete Stock Items
     */
    async watchListsIdItemsDeletePostRaw(requestParameters: WatchListsIdItemsDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.watchListsIdItemsDeletePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete multiple items from a watch list
     * Bulk Delete Stock Items
     */
    async watchListsIdItemsDeletePost(requestParameters: WatchListsIdItemsDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.watchListsIdItemsDeletePostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for watchListsIdItemsGet without sending the request
     */
    async watchListsIdItemsGetRequestOpts(requestParameters: WatchListsIdItemsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling watchListsIdItemsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/watch-lists/{id}/items`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all items in a watch list
     * Get Watch List Items
     */
    async watchListsIdItemsGetRaw(requestParameters: WatchListsIdItemsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseArrayStockItemWatchList>> {
        const requestOptions = await this.watchListsIdItemsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseArrayStockItemWatchListFromJSON(jsonValue));
    }

    /**
     * Get all items in a watch list
     * Get Watch List Items
     */
    async watchListsIdItemsGet(requestParameters: WatchListsIdItemsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseArrayStockItemWatchList> {
        const response = await this.watchListsIdItemsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for watchListsIdItemsItemIdDelete without sending the request
     */
    async watchListsIdItemsItemIdDeleteRequestOpts(requestParameters: WatchListsIdItemsItemIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling watchListsIdItemsItemIdDelete().'
            );
        }

        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling watchListsIdItemsItemIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/watch-lists/{id}/items/{itemId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a stock item from watch list
     * Delete Stock Item
     */
    async watchListsIdItemsItemIdDeleteRaw(requestParameters: WatchListsIdItemsItemIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.watchListsIdItemsItemIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a stock item from watch list
     * Delete Stock Item
     */
    async watchListsIdItemsItemIdDelete(requestParameters: WatchListsIdItemsItemIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.watchListsIdItemsItemIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for watchListsIdItemsItemIdGet without sending the request
     */
    async watchListsIdItemsItemIdGetRequestOpts(requestParameters: WatchListsIdItemsItemIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling watchListsIdItemsItemIdGet().'
            );
        }

        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling watchListsIdItemsItemIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/watch-lists/{id}/items/{itemId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a specific stock item by ID
     * Get Stock Item by ID
     */
    async watchListsIdItemsItemIdGetRaw(requestParameters: WatchListsIdItemsItemIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoreWatchlistTransportHttpGetStockItemResponse>> {
        const requestOptions = await this.watchListsIdItemsItemIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoreWatchlistTransportHttpGetStockItemResponseFromJSON(jsonValue));
    }

    /**
     * Get a specific stock item by ID
     * Get Stock Item by ID
     */
    async watchListsIdItemsItemIdGet(requestParameters: WatchListsIdItemsItemIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoreWatchlistTransportHttpGetStockItemResponse> {
        const response = await this.watchListsIdItemsItemIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for watchListsIdItemsItemIdPut without sending the request
     */
    async watchListsIdItemsItemIdPutRequestOpts(requestParameters: WatchListsIdItemsItemIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling watchListsIdItemsItemIdPut().'
            );
        }

        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling watchListsIdItemsItemIdPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling watchListsIdItemsItemIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/watch-lists/{id}/items/{itemId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CoreWatchlistTransportHttpUpdateItemRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Update an existing stock item
     * Update Stock Item
     */
    async watchListsIdItemsItemIdPutRaw(requestParameters: WatchListsIdItemsItemIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoreWatchlistTransportHttpUpdateItemResponse>> {
        const requestOptions = await this.watchListsIdItemsItemIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoreWatchlistTransportHttpUpdateItemResponseFromJSON(jsonValue));
    }

    /**
     * Update an existing stock item
     * Update Stock Item
     */
    async watchListsIdItemsItemIdPut(requestParameters: WatchListsIdItemsItemIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoreWatchlistTransportHttpUpdateItemResponse> {
        const response = await this.watchListsIdItemsItemIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for watchListsIdItemsPost without sending the request
     */
    async watchListsIdItemsPostRequestOpts(requestParameters: WatchListsIdItemsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling watchListsIdItemsPost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling watchListsIdItemsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/watch-lists/{id}/items`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CoreWatchlistTransportHttpCreateItemRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Add a new stock item to a watch list
     * Add Stock Item to Watch List
     */
    async watchListsIdItemsPostRaw(requestParameters: WatchListsIdItemsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoreWatchlistTransportHttpCreateItemResponse>> {
        const requestOptions = await this.watchListsIdItemsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoreWatchlistTransportHttpCreateItemResponseFromJSON(jsonValue));
    }

    /**
     * Add a new stock item to a watch list
     * Add Stock Item to Watch List
     */
    async watchListsIdItemsPost(requestParameters: WatchListsIdItemsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoreWatchlistTransportHttpCreateItemResponse> {
        const response = await this.watchListsIdItemsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for watchListsIdItemsReorderPut without sending the request
     */
    async watchListsIdItemsReorderPutRequestOpts(requestParameters: WatchListsIdItemsReorderPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling watchListsIdItemsReorderPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling watchListsIdItemsReorderPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/watch-lists/{id}/items/reorder`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CoreWatchlistTransportHttpReorderItemsRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Reorder items in a watch list
     * Reorder Stock Items
     */
    async watchListsIdItemsReorderPutRaw(requestParameters: WatchListsIdItemsReorderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.watchListsIdItemsReorderPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Reorder items in a watch list
     * Reorder Stock Items
     */
    async watchListsIdItemsReorderPut(requestParameters: WatchListsIdItemsReorderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.watchListsIdItemsReorderPutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for watchListsIdPut without sending the request
     */
    async watchListsIdPutRequestOpts(requestParameters: WatchListsIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling watchListsIdPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling watchListsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/watch-lists/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CoreWatchlistTransportHttpUpdateWatchListRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Update an existing watch list
     * Update Watch List
     */
    async watchListsIdPutRaw(requestParameters: WatchListsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoreWatchlistTransportHttpUpdateWatchListResponse>> {
        const requestOptions = await this.watchListsIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoreWatchlistTransportHttpUpdateWatchListResponseFromJSON(jsonValue));
    }

    /**
     * Update an existing watch list
     * Update Watch List
     */
    async watchListsIdPut(requestParameters: WatchListsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoreWatchlistTransportHttpUpdateWatchListResponse> {
        const response = await this.watchListsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for watchListsPost without sending the request
     */
    async watchListsPostRequestOpts(requestParameters: WatchListsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling watchListsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/watch-lists`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CoreWatchlistTransportHttpCreateWatchListRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create a new watch list for the authenticated user
     * Create Watch List
     */
    async watchListsPostRaw(requestParameters: WatchListsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoreWatchlistTransportHttpCreateWatchListResponse>> {
        const requestOptions = await this.watchListsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoreWatchlistTransportHttpCreateWatchListResponseFromJSON(jsonValue));
    }

    /**
     * Create a new watch list for the authenticated user
     * Create Watch List
     */
    async watchListsPost(requestParameters: WatchListsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoreWatchlistTransportHttpCreateWatchListResponse> {
        const response = await this.watchListsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
