/* tslint:disable */
/* eslint-disable */
/**
 * Beetrade API
 * API documentation for Beetrade
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BaseResponseAny,
  BaseResponseStopWorkloadResponse,
  BaseResponseWorkload,
} from '../models/index';
import {
    BaseResponseAnyFromJSON,
    BaseResponseAnyToJSON,
    BaseResponseStopWorkloadResponseFromJSON,
    BaseResponseStopWorkloadResponseToJSON,
    BaseResponseWorkloadFromJSON,
    BaseResponseWorkloadToJSON,
} from '../models/index';

export interface WorkloadsGetRequest {
    type?: WorkloadsGetTypeEnum;
    status?: WorkloadsGetStatusEnum;
    page?: number;
    limit?: number;
}

export interface WorkloadsIdGetRequest {
    id: number;
}

export interface WorkloadsIdStopPostRequest {
    id: number;
}

/**
 * 
 */
export class WorkloadsApi extends runtime.BaseAPI {

    /**
     * Creates request options for workloadsGet without sending the request
     */
    async workloadsGetRequestOpts(requestParameters: WorkloadsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/workloads`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all workloads for the authenticated user with optional filters
     * List Workloads
     */
    async workloadsGetRaw(requestParameters: WorkloadsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseStopWorkloadResponse>> {
        const requestOptions = await this.workloadsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseStopWorkloadResponseFromJSON(jsonValue));
    }

    /**
     * Get all workloads for the authenticated user with optional filters
     * List Workloads
     */
    async workloadsGet(requestParameters: WorkloadsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseStopWorkloadResponse> {
        const response = await this.workloadsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workloadsIdGet without sending the request
     */
    async workloadsIdGetRequestOpts(requestParameters: WorkloadsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workloadsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/workloads/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get workload details by ID
     * Get Workload by ID
     */
    async workloadsIdGetRaw(requestParameters: WorkloadsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseWorkload>> {
        const requestOptions = await this.workloadsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseWorkloadFromJSON(jsonValue));
    }

    /**
     * Get workload details by ID
     * Get Workload by ID
     */
    async workloadsIdGet(requestParameters: WorkloadsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseWorkload> {
        const response = await this.workloadsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workloadsIdStopPost without sending the request
     */
    async workloadsIdStopPostRequestOpts(requestParameters: WorkloadsIdStopPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workloadsIdStopPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/workloads/{id}/stop`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Stop a running workload by ID
     * Stop Workload
     */
    async workloadsIdStopPostRaw(requestParameters: WorkloadsIdStopPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseStopWorkloadResponse>> {
        const requestOptions = await this.workloadsIdStopPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseStopWorkloadResponseFromJSON(jsonValue));
    }

    /**
     * Stop a running workload by ID
     * Stop Workload
     */
    async workloadsIdStopPost(requestParameters: WorkloadsIdStopPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseStopWorkloadResponse> {
        const response = await this.workloadsIdStopPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum WorkloadsGetTypeEnum {
    LiveTrading = 'LIVE_TRADING',
    Backtest = 'BACKTEST',
    AdvanceOrder = 'ADVANCE_ORDER',
    LoadData = 'LOAD_DATA',
    Alert = 'ALERT',
    BotAdvancedOrder = 'BOT_ADVANCED_ORDER'
}
/**
  * @export
  * @enum {string}
  */
export enum WorkloadsGetStatusEnum {
    Init = 'INIT',
    Running = 'RUNNING',
    Stopped = 'STOPPED',
    Failed = 'FAILED'
}
